[[header]]

[[content]]
[[header_unordered_node_set]]
== `<boost/unordered/unordered_node_set.hpp>` 概要

定义
link:reference/unordered_node_set.html#unordered_node_set[`boost::unordered_node_set`]
及其相关函数和别名模板。

....
namespace boost {
namespace unordered {

  template,
           class Pred = std::equal_to,
           class Allocator = std::allocator>
  class unordered_node_set;

  // 相等比较
  template
    bool operator==(const unordered_node_set& x,
                    const unordered_node_set& y);

  template
    bool operator!=(const unordered_node_set& x,
                    const unordered_node_set& y);

  // 交换
  template
    void swap(unordered_node_set& x,
              unordered_node_set& y)
      noexcept(noexcept(x.swap(y)));

  // 擦除
  template
    typename unordered_node_set::size_type
      erase_if(unordered_node_set& c, Predicate pred);

  // Pmr别名（C++17及以上）
  namespace pmr {
    template,
             class Pred = std::equal_to>
    using unordered_node_set =
      boost::unordered::unordered_node_set>;
  } // 命名空间 pmr

} // 命名空间 unordered

using unordered::unordered_node_set;

} // 命名空间 boost
....

[[footer]]
[[footer-text]]
最后更新于2025年10月31日 21:39:18 UTC
