[[header]]

[[content]]
[[header_concurrent_node_set]]
== `<boost/unordered/concurrent_node_set.hpp>` 概要

定义
link:reference/concurrent_node_set.html#concurrent_node_set[`boost::concurrent_node_set`]
及其相关函数和别名模板。

....
namespace boost {
namespace unordered {

  template,
           class Pred = std::equal_to,
           class Allocator = std::allocator>
  class concurrent_node_set;

  // 相等比较
  template
    bool operator==(const concurrent_node_set& x,
                    const concurrent_node_set& y);

  template
    bool operator!=(const concurrent_node_set& x,
                    const concurrent_node_set& y);

  // 交换
  template
    void swap(concurrent_node_set& x,
              concurrent_node_set& y)
      noexcept(noexcept(x.swap(y)));

  // 擦除
  template
    typename concurrent_node_set::size_type
      erase_if(concurrent_node_set& c, Predicate pred);

  // Pmr别名（C++17及以上）
  namespace pmr {
    template,
             class Pred = std::equal_to>
    using concurrent_node_set =
      boost::unordered::concurrent_node_set>;
  } // 命名空间 pmr

} // 命名空间 unordered

using unordered::concurrent_node_set;

} // 命名空间 boost
....

[[footer]]
[[footer-text]]
最后更新于 2025-10-31 21:36:21 UTC
