[[header]]

[[content]]
[[header_unordered_node_map]]
== `<boost/unordered/unordered_node_map.hpp>` 概要

定义
link:reference/unordered_node_map.html#unordered_node_map[`boost::unordered_node_map`]
及相关函数和别名模板。

....
namespace boost {
namespace unordered {

  template,
           class Pred = std::equal_to,
           class Allocator = std::allocator>>
  class unordered_node_map;

  // 相等比较
  template
    bool operator==(const unordered_node_map& x,
                    const unordered_node_map& y);

  template
    bool operator!=(const unordered_node_map& x,
                    const unordered_node_map& y);

  // 交换
  template
    void swap(unordered_node_map& x,
              unordered_node_map& y)
      noexcept(noexcept(x.swap(y)));

  // 擦除
  template
    typename unordered_node_map::size_type
      erase_if(unordered_node_map& c, Predicate pred);

  // Pmr别名（C++17及以上版本）
  namespace pmr {
    template,
             class Pred = std::equal_to>
    using unordered_node_map =
      boost::unordered::unordered_node_map>>;
  } // 命名空间 pmr

} // 命名空间 unordered

using unordered::unordered_node_map;

} // 命名空间 boost
....

[[footer]]
[[footer-text]]
最后更新于2025-10-31 21:38:46 UTC
