[[header]]

[[content]]
[[unordered_multimap]]
=== Class Template unordered++_++multimap

`boost::unordered++_++multimap` — An unordered associative container
that associates keys with another value. The same key can be stored
multiple times.

[[unordered_multimap_synopsis]]
==== Synopsis

....
// #include <boost/unordered/unordered_map.hpp>

namespace boost {
namespace unordered {

  template<class Key,
           class T,
           class Hash = boost::hash<Key>,
           class Pred = std::equal_to<Key>,
           class Allocator = std::allocator<std::pair<const Key, T>>>
  class unordered_multimap {
  public:
    // types
    using key_type             = Key;
    using mapped_type          = T;
    using value_type           = std::pair<const Key, T>;
    using hasher               = Hash;
    using key_equal            = Pred;
    using allocator_type       = Allocator;
    using pointer              = typename std::allocator_traits<Allocator>::pointer;
    using const_pointer        = typename std::allocator_traits<Allocator>::const_pointer;
    using reference            = value_type&;
    using const_reference      = const value_type&;
    using size_type            = std::size_t;
    using difference_type      = std::ptrdiff_t;

    using iterator             = implementation-defined;
    using const_iterator       = implementation-defined;
    using local_iterator       = implementation-defined;
    using const_local_iterator = implementation-defined;
    using node_type            = implementation-defined;

    // construct/copy/destroy
    unordered_multimap();
    explicit unordered_multimap(size_type n,
                                const hasher& hf = hasher(),
                                const key_equal& eql = key_equal(),
                                const allocator_type& a = allocator_type());
    template<class InputIterator>
      unordered_multimap(InputIterator f, InputIterator l,
                         size_type n = implementation-defined,
                         const hasher& hf = hasher(),
                         const key_equal& eql = key_equal(),
                         const allocator_type& a = allocator_type());
    unordered_multimap(const unordered_multimap& other);
    unordered_multimap(unordered_multimap&& other);
    template<class InputIterator>
      unordered_multimap(InputIterator f, InputIterator l, const allocator_type& a);
    explicit unordered_multimap(const Allocator& a);
    unordered_multimap(const unordered_multimap& other, const Allocator& a);
    unordered_multimap(unordered_multimap&& other, const Allocator& a);
    unordered_multimap(std::initializer_list<value_type> il,
                       size_type n = implementation-defined,
                       const hasher& hf = hasher(),
                       const key_equal& eql = key_equal(),
                       const allocator_type& a = allocator_type());
    unordered_multimap(size_type n, const allocator_type& a);
    unordered_multimap(size_type n, const hasher& hf, const allocator_type& a);
    template<class InputIterator>
      unordered_multimap(InputIterator f, InputIterator l, size_type n, const allocator_type& a);
    template<class InputIterator>
      unordered_multimap(InputIterator f, InputIterator l, size_type n, const hasher& hf,
                         const allocator_type& a);
    unordered_multimap(std::initializer_list<value_type> il, const allocator_type& a);
    unordered_multimap(std::initializer_list<value_type> il, size_type n,
                       const allocator_type& a);
    unordered_multimap(std::initializer_list<value_type> il, size_type n, const hasher& hf,
                       const allocator_type& a);
    ~unordered_multimap();
    unordered_multimap& operator=(const unordered_multimap& other);
    unordered_multimap& operator=(unordered_multimap&& other)
      noexcept(boost::allocator_traits<Allocator>::is_always_equal::value &&
               boost::is_nothrow_move_assignable_v<Hash> &&
               boost::is_nothrow_move_assignable_v<Pred>);
    unordered_multimap& operator=(std::initializer_list<value_type> il);
    allocator_type get_allocator() const noexcept;

    // iterators
    iterator       begin() noexcept;
    const_iterator begin() const noexcept;
    iterator       end() noexcept;
    const_iterator end() const noexcept;
    const_iterator cbegin() const noexcept;
    const_iterator cend() const noexcept;

    // capacity
    [[nodiscard]] bool empty() const noexcept;
    size_type size() const noexcept;
    size_type max_size() const noexcept;

    // modifiers
    template<class... Args> iterator emplace(Args&&... args);
    template<class... Args> iterator emplace_hint(const_iterator position, Args&&... args);
    iterator insert(const value_type& obj);
    iterator insert(value_type&& obj);
    template<class P> iterator insert(P&& obj);
    iterator insert(const_iterator hint, const value_type& obj);
    iterator insert(const_iterator hint, value_type&& obj);
    template<class P> iterator insert(const_iterator hint, P&& obj);
    template<class InputIterator> void insert(InputIterator first, InputIterator last);
    void insert(std::initializer_list<value_type> il);

    node_type extract(const_iterator position);
    node_type extract(const key_type& k);
    template<class K> node_type extract(K&& k);
    iterator insert(node_type&& nh);
    iterator insert(const_iterator hint, node_type&& nh);

    iterator  erase(iterator position);
    iterator  erase(const_iterator position);
    size_type erase(const key_type& k);
    template<class K> size_type erase(K&& k);
    iterator  erase(const_iterator first, const_iterator last);
    void      quick_erase(const_iterator position);
    void      erase_return_void(const_iterator position);
    void      swap(unordered_multimap& other)
      noexcept(boost::allocator_traits<Allocator>::is_always_equal::value &&
               boost::is_nothrow_swappable_v<Hash> &&
               boost::is_nothrow_swappable_v<Pred>);
    void      clear() noexcept;

    template<class H2, class P2>
      void merge(unordered_multimap<Key, T, H2, P2, Allocator>& source);
    template<class H2, class P2>
      void merge(unordered_multimap<Key, T, H2, P2, Allocator>&& source);
    template<class H2, class P2>
      void merge(unordered_map<Key, T, H2, P2, Allocator>& source);
    template<class H2, class P2>
      void merge(unordered_map<Key, T, H2, P2, Allocator>&& source);

    // observers
    hasher hash_function() const;
    key_equal key_eq() const;

    // map operations
    iterator         find(const key_type& k);
    const_iterator   find(const key_type& k) const;
    template<class K>
      iterator       find(const K& k);
    template<class K>
      const_iterator find(const K& k) const;
    template<typename CompatibleKey, typename CompatibleHash, typename CompatiblePredicate>
      iterator       find(CompatibleKey const& k, CompatibleHash const& hash,
                          CompatiblePredicate const& eq);
    template<typename CompatibleKey, typename CompatibleHash, typename CompatiblePredicate>
      const_iterator find(CompatibleKey const& k, CompatibleHash const& hash,
                          CompatiblePredicate const& eq) const;
    size_type        count(const key_type& k) const;
    template<class K>
      size_type      count(const K& k) const;
    bool             contains(const key_type& k) const;
    template<class K>
      bool           contains(const K& k) const;
    std::pair<iterator, iterator>               equal_range(const key_type& k);
    std::pair<const_iterator, const_iterator>   equal_range(const key_type& k) const;
    template<class K>
      std::pair<iterator, iterator>             equal_range(const K& k);
    template<class K>
      std::pair<const_iterator, const_iterator> equal_range(const K& k) const;

    // bucket interface
    size_type bucket_count() const noexcept;
    size_type max_bucket_count() const noexcept;
    size_type bucket_size(size_type n) const;
    size_type bucket(const key_type& k) const;
    template<class K> size_type bucket(const K& k) const;
    local_iterator begin(size_type n);
    const_local_iterator begin(size_type n) const;
    local_iterator end(size_type n);
    const_local_iterator end(size_type n) const;
    const_local_iterator cbegin(size_type n) const;
    const_local_iterator cend(size_type n) const;

    // hash policy
    float load_factor() const noexcept;
    float max_load_factor() const noexcept;
    void max_load_factor(float z);
    void rehash(size_type n);
    void reserve(size_type n);
  };

  // Deduction Guides
  template<class InputIterator,
           class Hash = boost::hash<iter-key-type<InputIterator>>,
           class Pred = std::equal_to<iter-key-type<InputIterator>>,
           class Allocator = std::allocator<iter-to-alloc-type<InputIterator>>>
    unordered_multimap(InputIterator, InputIterator, typename see below::size_type = see below,
                       Hash = Hash(), Pred = Pred(), Allocator = Allocator())
      -> unordered_multimap<iter-key-type<InputIterator>, iter-mapped-type<InputIterator>, Hash,
                            Pred, Allocator>;

  template<class Key, class T, class Hash = boost::hash<Key>,
           class Pred = std::equal_to<Key>,
           class Allocator = std::allocator<std::pair<const Key, T>>>
    unordered_multimap(std::initializer_list<std::pair<Key, T>>,
                       typename see below::size_type = see below, Hash = Hash(),
                       Pred = Pred(), Allocator = Allocator())
      -> unordered_multimap<Key, T, Hash, Pred, Allocator>;

  template<class InputIterator, class Allocator>
    unordered_multimap(InputIterator, InputIterator, typename see below::size_type, Allocator)
      -> unordered_multimap<iter-key-type<InputIterator>, iter-mapped-type<InputIterator>,
                            boost::hash<iter-key-type<InputIterator>>,
                            std::equal_to<iter-key-type<InputIterator>>, Allocator>;

  template<class InputIterator, class Allocator>
    unordered_multimap(InputIterator, InputIterator, Allocator)
      -> unordered_multimap<iter-key-type<InputIterator>, iter-mapped-type<InputIterator>,
                            boost::hash<iter-key-type<InputIterator>>,
                            std::equal_to<iter-key-type<InputIterator>>, Allocator>;

  template<class InputIterator, class Hash, class Allocator>
    unordered_multimap(InputIterator, InputIterator, typename see below::size_type, Hash,
                       Allocator)
      -> unordered_multimap<iter-key-type<InputIterator>, iter-mapped-type<InputIterator>, Hash,
                            std::equal_to<iter-key-type<InputIterator>>, Allocator>;

  template<class Key, class T, class Allocator>
    unordered_multimap(std::initializer_list<std::pair<Key, T>>, typename see below::size_type,
                       Allocator)
      -> unordered_multimap<Key, T, boost::hash<Key>, std::equal_to<Key>, Allocator>;

  template<class Key, class T, class Allocator>
    unordered_multimap(std::initializer_list<std::pair<Key, T>>, Allocator)
      -> unordered_multimap<Key, T, boost::hash<Key>, std::equal_to<Key>, Allocator>;

  template<class Key, class T, class Hash, class Allocator>
    unordered_multimap(std::initializer_list<std::pair<Key, T>>, typename see below::size_type,
                       Hash, Allocator)
      -> unordered_multimap<Key, T, Hash, std::equal_to<Key>, Allocator>;

} // namespace unordered
} // namespace boost
....

'''''

[[unordered_multimap_description]]
==== Description

*Template Parameters*

[width="100%",cols="50%,50%",]
|===
|_Key_ |`Key` must be
https://en.cppreference.com/w/cpp/named_req/Erasable[Erasable] from the
container (i.e. `allocator++_++traits` can destroy it).

|_T_ |`T` must be
https://en.cppreference.com/w/cpp/named_req/Erasable[Erasable] from the
container (i.e. `allocator++_++traits` can destroy it).

|_Hash_ |A unary function object type that acts a hash function for a
`Key`. It takes a single argument of type `Key` and returns a value of
type `std::size++_++t`.

|_Pred_ |A binary function object that implements an equivalence
relation on values of type `Key`. A binary function object that induces
an equivalence relation on values of type `Key`. It takes two arguments
of type `Key` and returns a value of type bool.

|_Allocator_ |An allocator whose value type is the same as the
container’s value type. Allocators using
https://en.cppreference.com/w/cpp/named_req/Allocator#Fancy_pointers[fancy
pointers] are supported.
|===

The elements are organized into buckets. Keys with the same hash code
are stored in the same bucket.

The number of buckets can be automatically increased by a call to
insert, or as the result of calling rehash.

[[unordered_multimap_configuration_macros]]
==== Configuration macros

[[unordered_multimap_boost_unordered_enable_serialization_compatibility_v0]]
===== `BOOST++_++UNORDERED++_++ENABLE++_++SERIALIZATION++_++COMPATIBILITY++_++V0`

Globally define this macro to support loading of
`unordered++_++multimap`s saved to a Boost.Serialization archive with a
version of Boost prior to Boost 1.84.

[[unordered_multimap_typedefs]]
==== Typedefs

[source,highlight]
----
typedef implementation-defined iterator;
----

An iterator whose value type is `value++_++type`.

The iterator category is at least a forward iterator.

Convertible to `const++_++iterator`.

'''''

[source,highlight]
----
typedef implementation-defined const_iterator;
----

A constant iterator whose value type is `value++_++type`.

The iterator category is at least a forward iterator.

'''''

[source,highlight]
----
typedef implementation-defined local_iterator;
----

An iterator with the same value type, difference type and pointer and
reference type as iterator.

A `local++_++iterator` object can be used to iterate through a single
bucket.

'''''

[source,highlight]
----
typedef implementation-defined const_local_iterator;
----

A constant iterator with the same value type, difference type and
pointer and reference type as const++_++iterator.

A const++_++local++_++iterator object can be used to iterate through a
single bucket.

'''''

[source,highlight]
----
typedef implementation-defined node_type;
----

See node++_++handle++_++map for details.

'''''

[[unordered_multimap_constructors]]
==== Constructors

[[unordered_multimap_default_constructor]]
===== Default Constructor

[source,highlight]
----
unordered_multimap();
----

Constructs an empty container using `hasher()` as the hash function,
`key++_++equal()` as the key equality predicate, `allocator++_++type()`
as the allocator and a maximum load factor of `1.0`.

[cols=",",]
|===
|Postconditions: |`size() == 0`

|Requires: |If the defaults are used, `hasher`, `key++_++equal` and
`allocator++_++type` need to be
https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[DefaultConstructible].
|===

'''''

[[unordered_multimap_bucket_count_constructor]]
===== Bucket Count Constructor

[source,highlight]
----
explicit unordered_multimap(size_type n,
                            const hasher& hf = hasher(),
                            const key_equal& eql = key_equal(),
                            const allocator_type& a = allocator_type());
----

Constructs an empty container with at least `n` buckets, using `hf` as
the hash function, `eql` as the key equality predicate, `a` as the
allocator and a maximum load factor of `1.0`.

[cols=",",]
|===
|Postconditions: |`size() == 0`

|Requires: |If the defaults are used, `hasher`, `key++_++equal` and
`allocator++_++type` need to be
https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[DefaultConstructible].
|===

'''''

[[unordered_multimap_iterator_range_constructor]]
===== Iterator Range Constructor

[source,highlight]
----
template<class InputIterator>
unordered_multimap(InputIterator f, InputIterator l,
                   size_type n = implementation-defined,
                   const hasher& hf = hasher(),
                   const key_equal& eql = key_equal(),
                   const allocator_type& a = allocator_type());
----

Constructs an empty container with at least `n` buckets, using `hf` as
the hash function, `eql` as the key equality predicate, `a` as the
allocator and a maximum load factor of `1.0` and inserts the elements
from `++[++f, l)` into it.

[cols=",",]
|===
|Requires: |If the defaults are used, `hasher`, `key++_++equal` and
`allocator++_++type` need to be
https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[DefaultConstructible].
|===

'''''

[[unordered_multimap_copy_constructor]]
===== Copy Constructor

[source,highlight]
----
unordered_multimap(const unordered_multimap& other);
----

The copy constructor. Copies the contained elements, hash function,
predicate, maximum load factor and allocator.

If `Allocator::select++_++on++_++container++_++copy++_++construction`
exists and has the right signature, the allocator will be constructed
from its result.

[cols=",",]
|===
|Requires: |`value++_++type` is copy constructible
|===

'''''

[[unordered_multimap_move_constructor]]
===== Move Constructor

[source,highlight]
----
unordered_multimap(unordered_multimap&& other);
----

The move constructor.

[cols=",",]
|===
|Notes: |This is implemented using Boost.Move.
|Requires: |`value++_++type` is move-constructible.
|===

'''''

[[unordered_multimap_iterator_range_constructor_with_allocator]]
===== Iterator Range Constructor with Allocator

[source,highlight]
----
template<class InputIterator>
  unordered_multimap(InputIterator f, InputIterator l, const allocator_type& a);
----

Constructs an empty container using `a` as the allocator, with the
default hash function and key equality predicate and a maximum load
factor of `1.0` and inserts the elements from `++[++f, l)` into it.

[cols=",",]
|===
|Requires: |`hasher`, `key++_++equal` need to be
https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[DefaultConstructible].
|===

'''''

[[unordered_multimap_allocator_constructor]]
===== Allocator Constructor

[source,highlight]
----
explicit unordered_multimap(const Allocator& a);
----

Constructs an empty container, using allocator `a`.

'''''

[[unordered_multimap_copy_constructor_with_allocator]]
===== Copy Constructor with Allocator

[source,highlight]
----
unordered_multimap(const unordered_multimap& other, const Allocator& a);
----

Constructs an container, copying `other`'s contained elements, hash
function, predicate, maximum load factor, but using allocator `a`.

'''''

[[unordered_multimap_move_constructor_with_allocator]]
===== Move Constructor with Allocator

[source,highlight]
----
unordered_multimap(unordered_multimap&& other, const Allocator& a);
----

Construct a container moving `other`'s contained elements, and having
the hash function, predicate and maximum load factor, but using allocate
`a`.

[cols=",",]
|===
|Notes: |This is implemented using Boost.Move.
|Requires: |`value++_++type` is move insertable.
|===

'''''

[[unordered_multimap_initializer_list_constructor]]
===== Initializer List Constructor

[source,highlight]
----
unordered_multimap(std::initializer_list<value_type> il,
                   size_type n = implementation-defined,
                   const hasher& hf = hasher(),
                   const key_equal& eql = key_equal(),
                   const allocator_type& a = allocator_type());
----

Constructs an empty container with at least `n` buckets, using `hf` as
the hash function, `eql` as the key equality predicate, `a` as the
allocator and a maximum load factor of `1.0` and inserts the elements
from `il` into it.

[cols=",",]
|===
|Requires: |If the defaults are used, `hasher`, `key++_++equal` and
`allocator++_++type` need to be
https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[DefaultConstructible].
|===

'''''

[[unordered_multimap_bucket_count_constructor_with_allocator]]
===== Bucket Count Constructor with Allocator

[source,highlight]
----
unordered_multimap(size_type n, const allocator_type& a);
----

Constructs an empty container with at least `n` buckets, using `hf` as
the hash function, the default hash function and key equality predicate,
`a` as the allocator and a maximum load factor of `1.0`.

[cols=",",]
|===
|Postconditions: |`size() == 0`

|Requires: |`hasher` and `key++_++equal` need to be
https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[DefaultConstructible].
|===

'''''

[[unordered_multimap_bucket_count_constructor_with_hasher_and_allocator]]
===== Bucket Count Constructor with Hasher and Allocator

[source,highlight]
----
unordered_multimap(size_type n, const hasher& hf, const allocator_type& a);
----

Constructs an empty container with at least `n` buckets, using `hf` as
the hash function, the default key equality predicate, `a` as the
allocator and a maximum load factor of `1.0`.

[cols=",",]
|===
|Postconditions: |`size() == 0`

|Requires: |`key++_++equal` needs to be
https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[DefaultConstructible].
|===

'''''

[[unordered_multimap_iterator_range_constructor_with_bucket_count_and_allocator]]
===== Iterator Range Constructor with Bucket Count and Allocator

[source,highlight]
----
template<class InputIterator>
  unordered_multimap(InputIterator f, InputIterator l, size_type n, const allocator_type& a);
----

Constructs an empty container with at least `n` buckets, using `a` as
the allocator, with the default hash function and key equality predicate
and a maximum load factor of `1.0` and inserts the elements from
`++[++f, l)` into it.

[cols=",",]
|===
|Requires: |`hasher`, `key++_++equal` need to be
https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[DefaultConstructible].
|===

'''''

[[unordered_multimap_iterator_range_constructor_with_bucket_count_and_hasher]]
===== Iterator Range Constructor with Bucket Count and Hasher

[source,highlight]
----
template<class InputIterator>
  unordered_multimap(InputIterator f, InputIterator l, size_type n, const hasher& hf,
                     const allocator_type& a);
----

Constructs an empty container with at least `n` buckets, using `hf` as
the hash function, `a` as the allocator, with the default key equality
predicate and a maximum load factor of `1.0` and inserts the elements
from `++[++f, l)` into it.

[cols=",",]
|===
|Requires: |`key++_++equal` needs to be
https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[DefaultConstructible].
|===

'''''

[[unordered_multimap_initializer_list_constructor_with_allocator]]
===== initializer++_++list Constructor with Allocator

[source,highlight]
----
unordered_multimap(std::initializer_list<value_type> il, const allocator_type& a);
----

Constructs an empty container using `a` as the allocator and a maximum
load factor of 1.0 and inserts the elements from `il` into it.

[cols=",",]
|===
|Requires: |`hasher` and `key++_++equal` need to be
https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[DefaultConstructible].
|===

'''''

[[unordered_multimap_initializer_list_constructor_with_bucket_count_and_allocator]]
===== initializer++_++list Constructor with Bucket Count and Allocator

[source,highlight]
----
unordered_multimap(std::initializer_list<value_type> il, size_type n, const allocator_type& a);
----

Constructs an empty container with at least `n` buckets, using `a` as
the allocator and a maximum load factor of 1.0 and inserts the elements
from `il` into it.

[cols=",",]
|===
|Requires: |`hasher` and `key++_++equal` need to be
https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[DefaultConstructible].
|===

'''''

[[unordered_multimap_initializer_list_constructor_with_bucket_count_and_hasher_and_allocator]]
===== initializer++_++list Constructor with Bucket Count and Hasher and Allocator

[source,highlight]
----
unordered_multimap(std::initializer_list<value_type> il, size_type n, const hasher& hf,
                   const allocator_type& a);
----

Constructs an empty container with at least `n` buckets, using `hf` as
the hash function, `a` as the allocator and a maximum load factor of 1.0
and inserts the elements from `il` into it.

[cols=",",]
|===
|Requires: |`key++_++equal` needs to be
https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[DefaultConstructible].
|===

'''''

[[unordered_multimap_destructor]]
==== Destructor

[source,highlight]
----
~unordered_multimap();
----

[cols=",",]
|===
|Note: |The destructor is applied to every element, and all memory is
deallocated
|===

'''''

[[unordered_multimap_assignment]]
==== Assignment

[[unordered_multimap_copy_assignment]]
===== Copy Assignment

[source,highlight]
----
unordered_multimap& operator=(const unordered_multimap& other);
----

The assignment operator. Copies the contained elements, hash function,
predicate and maximum load factor but not the allocator.

If `Alloc::propagate++_++on++_++container++_++copy++_++assignment`
exists and
`Alloc::propagate++_++on++_++container++_++copy++_++assignment::value`
is `true`, the allocator is overwritten, if not the copied elements are
created using the existing allocator.

[cols=",",]
|===
|Requires: |`value++_++type` is copy constructible
|===

'''''

[[unordered_multimap_move_assignment]]
===== Move Assignment

[source,highlight]
----
unordered_multimap& operator=(unordered_multimap&& other)
  noexcept(boost::allocator_traits<Allocator>::is_always_equal::value &&
           boost::is_nothrow_move_assignable_v<Hash> &&
           boost::is_nothrow_move_assignable_v<Pred>);
----

The move assignment operator.

If `Alloc::propagate++_++on++_++container++_++move++_++assignment`
exists and
`Alloc::propagate++_++on++_++container++_++move++_++assignment::value`
is `true`, the allocator is overwritten, if not the moved elements are
created using the existing allocator.

[cols=",",]
|===
|Requires: |`value++_++type` is move constructible.
|===

'''''

[[unordered_multimap_initializer_list_assignment]]
===== Initializer List Assignment

[source,highlight]
----
unordered_multimap& operator=(std::initializer_list<value_type> il);
----

Assign from values in initializer list. All existing elements are either
overwritten by the new elements or destroyed.

[cols=",",]
|===
|Requires: |`value++_++type` is
https://en.cppreference.com/w/cpp/named_req/CopyInsertable[CopyInsertable]
into the container and
https://en.cppreference.com/w/cpp/named_req/CopyAssignable[CopyAssignable].
|===

[[unordered_multimap_iterators]]
==== Iterators

[[unordered_multimap_begin]]
===== begin

[source,highlight]
----
iterator begin() noexcept;
const_iterator begin() const noexcept;
----

[cols=",",]
|===
|Returns: |An iterator referring to the first element of the container,
or if the container is empty the past-the-end value for the container.
|===

'''''

[[unordered_multimap_end]]
===== end

[source,highlight]
----
iterator       end() noexcept;
const_iterator end() const noexcept;
----

[cols=",",]
|===
|Returns: |An iterator which refers to the past-the-end value for the
container.
|===

'''''

[[unordered_multimap_cbegin]]
===== cbegin

[source,highlight]
----
const_iterator cbegin() const noexcept;
----

[cols=",",]
|===
|Returns: |A `const++_++iterator` referring to the first element of the
container, or if the container is empty the past-the-end value for the
container.
|===

'''''

[[unordered_multimap_cend]]
===== cend

[source,highlight]
----
const_iterator cend() const noexcept;
----

[cols=",",]
|===
|Returns: |A `const++_++iterator` which refers to the past-the-end value
for the container.
|===

'''''

[[unordered_multimap_size_and_capacity]]
==== Size and Capacity

[[unordered_multimap_empty]]
===== empty

[source,highlight]
----
[[nodiscard]] bool empty() const noexcept;
----

[cols=",",]
|===
|Returns: |`size() == 0`
|===

'''''

[[unordered_multimap_size]]
===== size

[source,highlight]
----
size_type size() const noexcept;
----

[cols=",",]
|===
|Returns: |`std::distance(begin(), end())`
|===

'''''

[[unordered_multimap_max_size]]
===== max++_++size

[source,highlight]
----
size_type max_size() const noexcept;
----

[cols=",",]
|===
|Returns: |`size()` of the largest possible container.
|===

'''''

[[unordered_multimap_modifiers]]
==== Modifiers

[[unordered_multimap_emplace]]
===== emplace

[source,highlight]
----
template<class... Args> iterator emplace(Args&&... args);
----

Inserts an object, constructed with the arguments `args`, in the
container.

[width="100%",cols="50%,50%",]
|===
|Requires: |`value++_++type` is
https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[EmplaceConstructible]
into `X` from `args`.

|Returns: |An iterator pointing to the inserted element.

|Throws: |If an exception is thrown by an operation other than a call to
`hasher` the function has no effect.

|Notes: a|
Can invalidate iterators, but only if the insert causes the load factor
to be greater to or equal to the maximum load factor. +

Pointers and references to elements are never invalidated.

|===

'''''

[[unordered_multimap_emplace_hint]]
===== emplace++_++hint

[source,highlight]
----
template<class... Args> iterator emplace_hint(const_iterator position, Args&&... args);
----

Inserts an object, constructed with the arguments args, in the
container.

`position` is a suggestion to where the element should be inserted.

[width="100%",cols="50%,50%",]
|===
|Requires: |`value++_++type` is
https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[EmplaceConstructible]
into `X` from `args`.

|Returns: |An iterator pointing to the inserted element.

|Throws: |If an exception is thrown by an operation other than a call to
`hasher` the function has no effect.

|Notes: a|
The standard is fairly vague on the meaning of the hint. But the only
practical way to use it, and the only way that Boost.Unordered supports
is to point to an existing element with the same key. +

Can invalidate iterators, but only if the insert causes the load factor
to be greater to or equal to the maximum load factor. +

Pointers and references to elements are never invalidated.

|===

'''''

[[unordered_multimap_copy_insert]]
===== Copy Insert

[source,highlight]
----
iterator insert(const value_type& obj);
----

Inserts `obj` in the container.

[width="100%",cols="50%,50%",]
|===
|Requires: |`value++_++type` is
https://en.cppreference.com/w/cpp/named_req/CopyInsertable[CopyInsertable].

|Returns: |An iterator pointing to the inserted element.

|Throws: |If an exception is thrown by an operation other than a call to
`hasher` the function has no effect.

|Notes: a|
Can invalidate iterators, but only if the insert causes the load factor
to be greater to or equal to the maximum load factor. +

Pointers and references to elements are never invalidated.

|===

'''''

[[unordered_multimap_move_insert]]
===== Move Insert

[source,highlight]
----
iterator insert(value_type&& obj);
----

Inserts `obj` in the container.

[width="100%",cols="50%,50%",]
|===
|Requires: |`value++_++type` is
https://en.cppreference.com/w/cpp/named_req/MoveInsertable[MoveInsertable].

|Returns: |An iterator pointing to the inserted element.

|Throws: |If an exception is thrown by an operation other than a call to
`hasher` the function has no effect.

|Notes: a|
Can invalidate iterators, but only if the insert causes the load factor
to be greater to or equal to the maximum load factor. +

Pointers and references to elements are never invalidated.

|===

'''''

[[unordered_multimap_emplace_insert]]
===== Emplace Insert

[source,highlight]
----
template<class P> iterator insert(P&& obj);
----

Inserts an element into the container by performing
`emplace(std::forward++<++P++>++(value))`.

Only participates in overload resolution if
`std::is++_++constructible++<++value++_++type, P&&++>++::value` is
`true`.

[cols=",",]
|===
|Returns: |An iterator pointing to the inserted element.
|===

'''''

[[unordered_multimap_copy_insert_with_hint]]
===== Copy Insert with Hint

[source,highlight]
----
iterator insert(const_iterator hint, const value_type& obj);
----

Inserts `obj` in the container.

`hint` is a suggestion to where the element should be inserted.

[width="100%",cols="50%,50%",]
|===
|Requires: |`value++_++type` is
https://en.cppreference.com/w/cpp/named_req/CopyInsertable[CopyInsertable].

|Returns: |An iterator pointing to the inserted element.

|Throws: |If an exception is thrown by an operation other than a call to
`hasher` the function has no effect.

|Notes: a|
The standard is fairly vague on the meaning of the hint. But the only
practical way to use it, and the only way that Boost.Unordered supports
is to point to an existing element with the same key. +

Can invalidate iterators, but only if the insert causes the load factor
to be greater to or equal to the maximum load factor. +

Pointers and references to elements are never invalidated.

|===

'''''

[[unordered_multimap_move_insert_with_hint]]
===== Move Insert with Hint

[source,highlight]
----
iterator insert(const_iterator hint, value_type&& obj);
----

Inserts `obj` in the container.

`hint` is a suggestion to where the element should be inserted.

[width="100%",cols="50%,50%",]
|===
|Requires: |`value++_++type` is
https://en.cppreference.com/w/cpp/named_req/MoveInsertable[MoveInsertable].

|Returns: |An iterator pointing to the inserted element.

|Throws: |If an exception is thrown by an operation other than a call to
`hasher` the function has no effect.

|Notes: a|
The standard is fairly vague on the meaning of the hint. But the only
practical way to use it, and the only way that Boost.Unordered supports
is to point to an existing element with the same key. +

Can invalidate iterators, but only if the insert causes the load factor
to be greater to or equal to the maximum load factor. +

Pointers and references to elements are never invalidated.

|===

'''''

[[unordered_multimap_emplace_insert_with_hint]]
===== Emplace Insert with Hint

[source,highlight]
----
template<class P> iterator insert(const_iterator hint, P&& obj);
----

Inserts an element into the container by performing
`emplace++_++hint(hint, std::forward++<++P++>++(value))`.

Only participates in overload resolution if
`std::is++_++constructible++<++value++_++type, P&&++>++::value` is
`true`.

`hint` is a suggestion to where the element should be inserted.

[width="100%",cols="50%,50%",]
|===
|Returns: |An iterator pointing to the inserted element.

|Notes: a|
The standard is fairly vague on the meaning of the hint. But the only
practical way to use it, and the only way that Boost.Unordered supports
is to point to an existing element with the same key. +

Can invalidate iterators, but only if the insert causes the load factor
to be greater to or equal to the maximum load factor. +

Pointers and references to elements are never invalidated.

|===

'''''

[[unordered_multimap_insert_iterator_range]]
===== Insert Iterator Range

[source,highlight]
----
template<class InputIterator> void insert(InputIterator first, InputIterator last);
----

Inserts a range of elements into the container.

[width="100%",cols="50%,50%",]
|===
|Requires: |`value++_++type` is
https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[EmplaceConstructible]
into `X` from `++*++first`.

|Throws: |When inserting a single element, if an exception is thrown by
an operation other than a call to `hasher` the function has no effect.

|Notes: a|
Can invalidate iterators, but only if the insert causes the load factor
to be greater to or equal to the maximum load factor. +

Pointers and references to elements are never invalidated.

|===

'''''

[[unordered_multimap_insert_initializer_list]]
===== Insert Initializer List

[source,highlight]
----
void insert(std::initializer_list<value_type> il);
----

Inserts a range of elements into the container.

[width="100%",cols="50%,50%",]
|===
|Requires: |`value++_++type` is
https://en.cppreference.com/w/cpp/named_req/CopyInsertable[CopyInsertable]
into the container.

|Throws: |When inserting a single element, if an exception is thrown by
an operation other than a call to `hasher` the function has no effect.

|Notes: a|
Can invalidate iterators, but only if the insert causes the load factor
to be greater to or equal to the maximum load factor. +

Pointers and references to elements are never invalidated.

|===

'''''

[[unordered_multimap_extract_by_iterator]]
===== Extract by Iterator

[source,highlight]
----
node_type extract(const_iterator position);
----

Removes the element pointed to by `position`.

[cols=",",]
|===
|Returns: |A `node++_++type` owning the element.

|Notes: |A node extracted using this method can be inserted into a
compatible `unordered++_++map`.
|===

'''''

[[unordered_multimap_extract_by_key]]
===== Extract by Key

[source,highlight]
----
node_type extract(const key_type& k);
template<class K> node_type extract(K&& k);
----

Removes an element with key equivalent to `k`.

[width="100%",cols="50%,50%",]
|===
|Returns: |A `node++_++type` owning the element if found, otherwise an
empty `node++_++type`.

|Throws: |Only throws an exception if it is thrown by `hasher` or
`key++_++equal`.

|Notes: a|
A node extracted using this method can be inserted into a compatible
`unordered++_++map`. +

The `template++<++class K++>++` overload only participates in overload
resolution if `Hash::is++_++transparent` and `Pred::is++_++transparent`
are valid member typedefs and neither `iterator` nor
`const++_++iterator` are implicitly convertible from `K`. The library
assumes that `Hash` is callable with both `K` and `Key` and that `Pred`
is transparent. This enables heterogeneous lookup which avoids the cost
of instantiating an instance of the `Key` type.

|===

'''''

[[unordered_multimap_insert_with_node_handle]]
===== Insert with `node++_++handle`

[source,highlight]
----
iterator insert(node_type&& nh);
----

If `nh` is empty, has no effect.

Otherwise inserts the element owned by `nh`.

[width="100%",cols="50%,50%",]
|===
|Requires: |`nh` is empty or `nh.get++_++allocator()` is equal to the
container’s allocator.

|Returns: a|
If `nh` was empty, returns `end()`. +

Otherwise returns an iterator pointing to the newly inserted element.

|Throws: |If an exception is thrown by an operation other than a call to
`hasher` the function has no effect.

|Notes: a|
Can invalidate iterators, but only if the insert causes the load factor
to be greater to or equal to the maximum load factor. +

Pointers and references to elements are never invalidated. +

This can be used to insert a node extracted from a compatible
`unordered++_++map`.

|===

'''''

[[unordered_multimap_insert_with_hint_and_node_handle]]
===== Insert with Hint and `node++_++handle`

[source,highlight]
----
iterator insert(const_iterator hint, node_type&& nh);
----

If `nh` is empty, has no effect.

Otherwise inserts the element owned by `nh`.

`hint` is a suggestion to where the element should be inserted.

[width="100%",cols="50%,50%",]
|===
|Requires: |`nh` is empty or `nh.get++_++allocator()` is equal to the
container’s allocator.

|Returns: a|
If `nh` was empty, returns `end()`. +

Otherwise returns an iterator pointing to the newly inserted element.

|Throws: |If an exception is thrown by an operation other than a call to
hasher the function has no effect.

|Notes: a|
The standard is fairly vague on the meaning of the hint. But the only
practical way to use it, and the only way that Boost.Unordered supports
is to point to an existing element with the same key. +

Can invalidate iterators, but only if the insert causes the load factor
to be greater to or equal to the maximum load factor. +

Pointers and references to elements are never invalidated. +

This can be used to insert a node extracted from a compatible
`unordered++_++map`.

|===

'''''

[[unordered_multimap_erase_by_position]]
===== Erase by Position

[source,highlight]
----
iterator erase(iterator position);
iterator erase(const_iterator position);
----

Erase the element pointed to by `position`.

[cols=",",]
|===
|Returns: |The iterator following `position` before the erasure.

|Throws: |Only throws an exception if it is thrown by `hasher` or
`key++_++equal`.

|Notes: |In older versions this could be inefficient because it had to
search through several buckets to find the position of the returned
iterator. The data structure has been changed so that this is no longer
the case, and the alternative erase methods have been deprecated.
|===

'''''

[[unordered_multimap_erase_by_key]]
===== Erase by Key

[source,highlight]
----
size_type erase(const key_type& k);
template<class K> size_type erase(K&& k);
----

Erase all elements with key equivalent to `k`.

[cols=",",]
|===
|Returns: |The number of elements erased.

|Throws: |Only throws an exception if it is thrown by `hasher` or
`key++_++equal`.

|Notes: |The `template++<++class K++>++` overload only participates in
overload resolution if `Hash::is++_++transparent` and
`Pred::is++_++transparent` are valid member typedefs and neither
`iterator` nor `const++_++iterator` are implicitly convertible from `K`.
The library assumes that `Hash` is callable with both `K` and `Key` and
that `Pred` is transparent. This enables heterogeneous lookup which
avoids the cost of instantiating an instance of the `Key` type.
|===

'''''

[[unordered_multimap_erase_range]]
===== Erase Range

[source,highlight]
----
iterator erase(const_iterator first, const_iterator last);
----

Erases the elements in the range from `first` to `last`.

[width="100%",cols="50%,50%",]
|===
|Returns: |The iterator following the erased elements - i.e. `last`.

|Throws: a|
Only throws an exception if it is thrown by `hasher` or
`key++_++equal`. +

In this implementation, this overload doesn’t call either function
object’s methods so it is no throw, but this might not be true in other
implementations.

|===

'''''

[[unordered_multimap_quick_erase]]
===== quick++_++erase

[source,highlight]
----
void quick_erase(const_iterator position);
----

Erase the element pointed to by `position`.

[width="100%",cols="50%,50%",]
|===
|Throws: a|
Only throws an exception if it is thrown by `hasher` or
`key++_++equal`. +

In this implementation, this overload doesn’t call either function
object’s methods so it is no throw, but this might not be true in other
implementations.

|Notes: |This method was implemented because returning an iterator to
the next element from erase was expensive, but the container has been
redesigned so that is no longer the case. So this method is now
deprecated.
|===

'''''

[[unordered_multimap_erase_return_void]]
===== erase++_++return++_++void

[source,highlight]
----
void erase_return_void(const_iterator position);
----

Erase the element pointed to by `position`.

[width="100%",cols="50%,50%",]
|===
|Throws: a|
Only throws an exception if it is thrown by `hasher` or
`key++_++equal`. +

In this implementation, this overload doesn’t call either function
object’s methods so it is no throw, but this might not be true in other
implementations.

|Notes: |This method was implemented because returning an iterator to
the next element from erase was expensive, but the container has been
redesigned so that is no longer the case. So this method is now
deprecated.
|===

'''''

[[unordered_multimap_swap]]
===== swap

[source,highlight]
----
void swap(unordered_multimap& other)
  noexcept(boost::allocator_traits<Allocator>::is_always_equal::value &&
           boost::is_nothrow_swappable_v<Hash> &&
           boost::is_nothrow_swappable_v<Pred>);
----

Swaps the contents of the container with the parameter.

If `Allocator::propagate++_++on++_++container++_++swap` is declared and
`Allocator::propagate++_++on++_++container++_++swap::value` is `true`
then the containers' allocators are swapped. Otherwise, swapping with
unequal allocators results in undefined behavior.

[cols=",",]
|===
|Throws: |Doesn’t throw an exception unless it is thrown by the copy
constructor or copy assignment operator of `key++_++equal` or `hasher`.

|Notes: |The exception specifications aren’t quite the same as the
C{plus}{plus}11 standard, as the equality predicate and hash function
are swapped using their copy constructors.
|===

'''''

[[unordered_multimap_clear]]
===== clear

[source,highlight]
----
void clear() noexcept;
----

Erases all elements in the container.

[cols=",",]
|===
|Postconditions: |`size() == 0`
|Throws: |Never throws an exception.
|===

'''''

[[unordered_multimap_merge]]
===== merge

[source,highlight]
----
template<class H2, class P2>
  void merge(unordered_multimap<Key, T, H2, P2, Allocator>& source);
template<class H2, class P2>
  void merge(unordered_multimap<Key, T, H2, P2, Allocator>&& source);
template<class H2, class P2>
  void merge(unordered_map<Key, T, H2, P2, Allocator>& source);
template<class H2, class P2>
  void merge(unordered_map<Key, T, H2, P2, Allocator>&& source);
----

Attempt to "merge" two containers by iterating `source` and extracting
all nodes in `source` and inserting them into `++*++this`.

Because `source` can have a different hash function and key equality
predicate, the key of each node in `source` is rehashed using
`this-++>++hash++_++function()` and then, if required, compared using
`this-++>++key++_++eq()`.

The behavior of this function is undefined if
`this-++>++get++_++allocator() != source.get++_++allocator()`.

This function does not copy or move any elements and instead simply
relocates the nodes from `source` into `++*++this`.

[width="100%",cols="50%,50%",]
|===
|Notes: a|
* Pointers and references to transferred elements remain valid.
* Invalidates iterators to transferred elements.
* Invalidates iterators belonging to `++*++this`.
* Iterators to non-transferred elements in `source` remain valid.

|===

'''''

[[unordered_multimap_observers]]
==== Observers

[[unordered_multimap_get_allocator]]
===== get++_++allocator

[source,highlight]
----
allocator_type get_allocator() const;
----

'''''

[[unordered_multimap_hash_function]]
===== hash++_++function

[source,highlight]
----
hasher hash_function() const;
----

[cols=",",]
|===
|Returns: |The container’s hash function.
|===

'''''

[[unordered_multimap_key_eq]]
===== key++_++eq

[source,highlight]
----
key_equal key_eq() const;
----

[cols=",",]
|===
|Returns: |The container’s key equality predicate
|===

'''''

[[unordered_multimap_lookup]]
==== Lookup

[[unordered_multimap_find]]
===== find

[source,highlight]
----
iterator         find(const key_type& k);
const_iterator   find(const key_type& k) const;
template<class K>
  iterator       find(const K& k);
template<class K>
  const_iterator find(const K& k) const;
template<typename CompatibleKey, typename CompatibleHash, typename CompatiblePredicate>
  iterator       find(CompatibleKey const& k, CompatibleHash const& hash,
                      CompatiblePredicate const& eq);
template<typename CompatibleKey, typename CompatibleHash, typename CompatiblePredicate>
  const_iterator find(CompatibleKey const& k, CompatibleHash const& hash,
                      CompatiblePredicate const& eq) const;
----

[width="100%",cols="50%,50%",]
|===
|Returns: |An iterator pointing to an element with key equivalent to
`k`, or `b.end()` if no such element exists.

|Notes: a|
The templated overloads containing `CompatibleKey`, `CompatibleHash` and
`CompatiblePredicate` are non-standard extensions which allow you to use
a compatible hash function and equality predicate for a key of a
different type in order to avoid an expensive type cast. In general, its
use is not encouraged and instead the `K` member function templates
should be used. +

The `template++<++class K++>++` overloads only participate in overload
resolution if `Hash::is++_++transparent` and `Pred::is++_++transparent`
are valid member typedefs. The library assumes that `Hash` is callable
with both `K` and `Key` and that `Pred` is transparent. This enables
heterogeneous lookup which avoids the cost of instantiating an instance
of the `Key` type.

|===

'''''

[[unordered_multimap_count]]
===== count

[source,highlight]
----
size_type        count(const key_type& k) const;
template<class K>
  size_type      count(const K& k) const;
----

[cols=",",]
|===
|Returns: |The number of elements with key equivalent to `k`.

|Notes: |The `template++<++class K++>++` overload only participates in
overload resolution if `Hash::is++_++transparent` and
`Pred::is++_++transparent` are valid member typedefs. The library
assumes that `Hash` is callable with both `K` and `Key` and that `Pred`
is transparent. This enables heterogeneous lookup which avoids the cost
of instantiating an instance of the `Key` type.
|===

'''''

[[unordered_multimap_contains]]
===== contains

[source,highlight]
----
bool             contains(const key_type& k) const;
template<class K>
  bool           contains(const K& k) const;
----

[cols=",",]
|===
|Returns: |A boolean indicating whether or not there is an element with
key equal to `key` in the container

|Notes: |The `template++<++class K++>++` overload only participates in
overload resolution if `Hash::is++_++transparent` and
`Pred::is++_++transparent` are valid member typedefs. The library
assumes that `Hash` is callable with both `K` and `Key` and that `Pred`
is transparent. This enables heterogeneous lookup which avoids the cost
of instantiating an instance of the `Key` type.
|===

'''''

[[unordered_multimap_equal_range]]
===== equal++_++range

[source,highlight]
----
std::pair<iterator, iterator>               equal_range(const key_type& k);
std::pair<const_iterator, const_iterator>   equal_range(const key_type& k) const;
template<class K>
  std::pair<iterator, iterator>             equal_range(const K& k);
template<class K>
  std::pair<const_iterator, const_iterator> equal_range(const K& k) const;
----

[cols=",",]
|===
|Returns: |A range containing all elements with key equivalent to `k`.
If the container doesn’t contain any such elements, returns
`std::make++_++pair(b.end(), b.end())`.

|Notes: |The `template++<++class K++>++` overloads only participate in
overload resolution if `Hash::is++_++transparent` and
`Pred::is++_++transparent` are valid member typedefs. The library
assumes that `Hash` is callable with both `K` and `Key` and that `Pred`
is transparent. This enables heterogeneous lookup which avoids the cost
of instantiating an instance of the `Key` type.
|===

'''''

[[unordered_multimap_bucket_interface]]
==== Bucket Interface

[[unordered_multimap_bucket_count]]
===== bucket++_++count

[source,highlight]
----
size_type bucket_count() const noexcept;
----

[cols=",",]
|===
|Returns: |The number of buckets.
|===

'''''

[[unordered_multimap_max_bucket_count]]
===== max++_++bucket++_++count

[source,highlight]
----
size_type max_bucket_count() const noexcept;
----

[cols=",",]
|===
|Returns: |An upper bound on the number of buckets.
|===

'''''

[[unordered_multimap_bucket_size]]
===== bucket++_++size

[source,highlight]
----
size_type bucket_size(size_type n) const;
----

[cols=",",]
|===
|Requires: |`n ++<++ bucket++_++count()`
|Returns: |The number of elements in bucket `n`.
|===

'''''

[[unordered_multimap_bucket]]
===== bucket

[source,highlight]
----
size_type bucket(const key_type& k) const;
template<class K> size_type bucket(const K& k) const;
----

[cols=",",]
|===
|Returns: |The index of the bucket which would contain an element with
key `k`.

|Postconditions: |The return value is less than `bucket++_++count()`.

|Notes: |The `template++<++class K++>++` overload only participates in
overload resolution if `Hash::is++_++transparent` and
`Pred::is++_++transparent` are valid member typedefs. The library
assumes that `Hash` is callable with both `K` and `Key` and that `Pred`
is transparent. This enables heterogeneous lookup which avoids the cost
of instantiating an instance of the `Key` type.
|===

'''''

[[unordered_multimap_begin_2]]
===== begin

[source,highlight]
----
local_iterator begin(size_type n);
const_local_iterator begin(size_type n) const;
----

[cols=",",]
|===
|Requires: |`n` shall be in the range `++[++0, bucket++_++count())`.

|Returns: |A local iterator pointing the first element in the bucket
with index `n`.
|===

'''''

[[unordered_multimap_end_2]]
===== end

[source,highlight]
----
local_iterator end(size_type n);
const_local_iterator end(size_type n) const;
----

[cols=",",]
|===
|Requires: |`n` shall be in the range `++[++0, bucket++_++count())`.

|Returns: |A local iterator pointing the 'one past the end' element in
the bucket with index `n`.
|===

'''''

[[unordered_multimap_cbegin_2]]
===== cbegin

[source,highlight]
----
const_local_iterator cbegin(size_type n) const;
----

[cols=",",]
|===
|Requires: |`n` shall be in the range `++[++0, bucket++_++count())`.

|Returns: |A constant local iterator pointing the first element in the
bucket with index `n`.
|===

'''''

[[unordered_multimap_cend_2]]
===== cend

[source,highlight]
----
const_local_iterator cend(size_type n) const;
----

[cols=",",]
|===
|Requires: |`n` shall be in the range `++[++0, bucket++_++count())`.

|Returns: |A constant local iterator pointing the 'one past the end'
element in the bucket with index `n`.
|===

'''''

[[unordered_multimap_hash_policy]]
==== Hash Policy

[[unordered_multimap_load_factor]]
===== load++_++factor

[source,highlight]
----
float load_factor() const noexcept;
----

[cols=",",]
|===
|Returns: |The average number of elements per bucket.
|===

'''''

[[unordered_multimap_max_load_factor]]
===== max++_++load++_++factor

[source,highlight]
----
float max_load_factor() const noexcept;
----

[cols=",",]
|===
|Returns: |Returns the current maximum load factor.
|===

'''''

[[unordered_multimap_set_max_load_factor]]
===== Set max++_++load++_++factor

[source,highlight]
----
void max_load_factor(float z);
----

[cols=",",]
|===
|Effects: |Changes the container’s maximum load factor, using `z` as a
hint.
|===

'''''

[[unordered_multimap_rehash]]
===== rehash

[source,highlight]
----
void rehash(size_type n);
----

Changes the number of buckets so that there are at least `n` buckets,
and so that the load factor is less than or equal to the maximum load
factor. When applicable, this will either grow or shrink the
`bucket++_++count()` associated with the container.

When `size() == 0`, `rehash(0)` will deallocate the underlying buckets
array.

Invalidates iterators, and changes the order of elements. Pointers and
references to elements are not invalidated.

[cols=",",]
|===
|Throws: |The function has no effect if an exception is thrown, unless
it is thrown by the container’s hash function or comparison function.
|===

'''''

[[unordered_multimap_reserve]]
===== reserve

[source,highlight]
----
void reserve(size_type n);
----

Equivalent to `a.rehash(ceil(n / a.max++_++load++_++factor()))`, or
`a.rehash(1)` if `n ++>++ 0` and
`a.max++_++load++_++factor() == std::numeric++_++limits++<++float++>++::infinity()`.

Similar to `rehash`, this function can be used to grow or shrink the
number of buckets in the container.

Invalidates iterators, and changes the order of elements. Pointers and
references to elements are not invalidated.

[cols=",",]
|===
|Throws: |The function has no effect if an exception is thrown, unless
it is thrown by the container’s hash function or comparison function.
|===

'''''

[[unordered_multimap_deduction_guides]]
==== Deduction Guides

A deduction guide will not participate in overload resolution if any of
the following are true:

* It has an `InputIterator` template parameter and a type that does not
qualify as an input iterator is deduced for that parameter.
* It has an `Allocator` template parameter and a type that does not
qualify as an allocator is deduced for that parameter.
* It has a `Hash` template parameter and an integral type or a type that
qualifies as an allocator is deduced for that parameter.
* It has a `Pred` template parameter and a type that qualifies as an
allocator is deduced for that parameter.

A `size++_++­type` parameter type in a deduction guide refers to the
`size++_++­type` member type of the container type deduced by the
deduction guide. Its default value coincides with the default value of
the constructor selected.

[[unordered_multimap_iter_value_type]]
===== _iter-value-type_

....
template<class InputIterator>
  using iter-value-type =
    typename std::iterator_traits<InputIterator>::value_type; // exposition only
....

[[unordered_multimap_iter_key_type]]
===== _iter-key-type_

....
template<class InputIterator>
  using iter-key-type = std::remove_const_t<
    std::tuple_element_t<0, iter-value-type<InputIterator>>>; // exposition only
....

[[unordered_multimap_iter_mapped_type]]
===== _iter-mapped-type_

....
template<class InputIterator>
  using iter-mapped-type =
    std::tuple_element_t<1, iter-value-type<InputIterator>>;  // exposition only
....

[[unordered_multimap_iter_to_alloc_type]]
===== _iter-to-alloc-type_

....
template<class InputIterator>
  using iter-to-alloc-type = std::pair<
    std::add_const_t<std::tuple_element_t<0, iter-value-type<InputIterator>>>,
    std::tuple_element_t<1, iter-value-type<InputIterator>>>; // exposition only
....

[[unordered_multimap_equality_comparisons]]
==== Equality Comparisons

[[unordered_multimap_operator]]
===== operator==

[source,highlight]
----
template<class Key, class T, class Hash, class Pred, class Alloc>
  bool operator==(const unordered_multimap<Key, T, Hash, Pred, Alloc>& x,
                  const unordered_multimap<Key, T, Hash, Pred, Alloc>& y);
----

Return `true` if `x.size() == y.size()` and for every equivalent key
group in `x`, there is a group in `y` for the same key, which is a
permutation (using `operator==` to compare the value types).

[cols=",",]
|===
|Notes: |Behavior is undefined if the two containers don’t have
equivalent equality predicates.
|===

'''''

[[unordered_multimap_operator_2]]
===== operator!=

[source,highlight]
----
template<class Key, class T, class Hash, class Pred, class Alloc>
  bool operator!=(const unordered_multimap<Key, T, Hash, Pred, Alloc>& x,
                  const unordered_multimap<Key, T, Hash, Pred, Alloc>& y);
----

Return `false` if `x.size() == y.size()` and for every equivalent key
group in `x`, there is a group in `y` for the same key, which is a
permutation (using `operator==` to compare the value types).

[cols=",",]
|===
|Notes: |Behavior is undefined if the two containers don’t have
equivalent equality predicates.
|===

'''''

[[unordered_multimap_swap_2]]
==== Swap

[source,highlight]
----
template<class Key, class T, class Hash, class Pred, class Alloc>
  void swap(unordered_multimap<Key, T, Hash, Pred, Alloc>& x,
            unordered_multimap<Key, T, Hash, Pred, Alloc>& y)
    noexcept(noexcept(x.swap(y)));
----

Swaps the contents of `x` and `y`.

If `Allocator::propagate++_++on++_++container++_++swap` is declared and
`Allocator::propagate++_++on++_++container++_++swap::value` is `true`
then the containers' allocators are swapped. Otherwise, swapping with
unequal allocators results in undefined behavior.

[cols=",",]
|===
|Effects: |`x.swap(y)`

|Throws: |Doesn’t throw an exception unless it is thrown by the copy
constructor or copy assignment operator of `key++_++equal` or `hasher`.

|Notes: |The exception specifications aren’t quite the same as the
C{plus}{plus}11 standard, as the equality predicate and hash function
are swapped using their copy constructors.
|===

'''''

[[unordered_multimap_erase_if]]
==== erase++_++if

[source,highlight]
----
template<class K, class T, class H, class P, class A, class Predicate>
  typename unordered_multimap<K, T, H, P, A>::size_type
    erase_if(unordered_multimap<K, T, H, P, A>& c, Predicate pred);
----

Traverses the container `c` and removes all elements for which the
supplied predicate returns `true`.

[width="100%",cols="50%,50%",]
|===
|Returns: |The number of erased elements.
|Notes: a|
Equivalent to: +

[source,highlight]
----
auto original_size = c.size();
for (auto i = c.begin(), last = c.end(); i != last; ) {
  if (pred(*i)) {
    i = c.erase(i);
  } else {
    ++i;
  }
}
return original_size - c.size();
----

Note that the references passed to `pred` are non-const.

|===

[[unordered_multimap_serialization]]
==== Serialization

`unordered++_++multimap`s can be archived/retrieved by means of
link:../../../../../serialization/index.html[Boost.Serialization] using
the API provided by this library. Both regular and XML archives are
supported.

[[unordered_multimap_saving_an_unordered_multimap_to_an_archive]]
===== Saving an unordered++_++multimap to an archive

Saves all the elements of an `unordered++_++multimap` `x` to an archive
(XML archive) `ar`.

[cols=",",]
|===
|Requires: |`std::remove++_++const++<++key++_++type++>++::type` and
`std::remove++_++const++<++mapped++_++type++>++::type` are serializable
(XML serializable), and they do support Boost.Serialization
`save++_++construct++_++data`/`load++_++construct++_++data` protocol
(automatically suported by
https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[DefaultConstructible]
types).
|===

'''''

[[unordered_multimap_loading_an_unordered_multimap_from_an_archive]]
===== Loading an unordered++_++multimap from an archive

Deletes all preexisting elements of an `unordered++_++multimap` `x` and
inserts from an archive (XML archive) `ar` restored copies of the
elements of the original `unordered++_++multimap` `other` saved to the
storage read by `ar`.

[cols=",",]
|===
|Requires: |`value++_++type` is
https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[EmplaceConstructible]
from
`(std::remove++_++const++<++key++_++type++>++::type&&, std::remove++_++const++<++mapped++_++type++>++::type&&)`.
`x.key++_++equal()` is functionally equivalent to
`other.key++_++equal()`.

|Note: |If the archive was saved using a release of Boost prior to Boost
1.84, the configuration macro
`BOOST++_++UNORDERED++_++ENABLE++_++SERIALIZATION++_++COMPATIBILITY++_++V0`
has to be globally defined for this operation to succeed; otherwise, an
exception is thrown.
|===

'''''

[[unordered_multimap_saving_an_iteratorconst_iterator_to_an_archive]]
===== Saving an iterator/const++_++iterator to an archive

Saves the positional information of an `iterator` (`const++_++iterator`)
`it` to an archive (XML archive) `ar`. `it` can be and `end()` iterator.

[cols=",",]
|===
|Requires: |The `unordered++_++multimap` `x` pointed to by `it` has been
previously saved to `ar`, and no modifying operations have been issued
on `x` between saving of `x` and saving of `it`.
|===

'''''

[[unordered_multimap_loading_an_iteratorconst_iterator_from_an_archive]]
===== Loading an iterator/const++_++iterator from an archive

Makes an `iterator` (`const++_++iterator`) `it` point to the restored
position of the original `iterator` (`const++_++iterator`) saved to the
storage read by an archive (XML archive) `ar`.

[cols=",",]
|===
|Requires: |If `x` is the `unordered++_++multimap` `it` points to, no
modifying operations have been issued on `x` between loading of `x` and
loading of `it`.
|===

[[footer]]
[[footer-text]]
Last updated 2025-10-31 11:07:48 UTC
