[[header]]

[[content]]
[[unordered_node_map]]
=== Class Template unordered++_++node++_++map

`boost::unordered++_++node++_++map` — A node-based, open-addressing
unordered associative container that associates unique keys with another
value.

`boost::unordered++_++node++_++map` uses an open-addressing layout like
`boost::unordered++_++flat++_++map`, but, being node-based, it provides
pointer stability and node handling functionalities. Its performance
lies between those of `boost::unordered++_++map` and
`boost::unordered++_++flat++_++map`.

As a result of its using open addressing, the interface of
`boost::unordered++_++node++_++map` deviates in a number of aspects from
that of `boost::unordered++_++map`/`std::unordered++_++map`:

* `begin()` is not constant-time.
* There is no API for bucket handling (except `bucket++_++count`).
* The maximum load factor of the container is managed internally and
can’t be set by the user.

Other than this, `boost::unordered++_++node++_++map` is mostly a drop-in
replacement of standard unordered associative containers.

[[unordered_node_map_synopsis]]
==== Synopsis

....
// #include <boost/unordered/unordered_node_map.hpp>

namespace boost {
namespace unordered {

  template<class Key,
           class T,
           class Hash = boost::hash<Key>,
           class Pred = std::equal_to<Key>,
           class Allocator = std::allocator<std::pair<const Key, T>>>
  class unordered_node_map {
  public:
    // types
    using key_type             = Key;
    using mapped_type          = T;
    using value_type           = std::pair<const Key, T>;
    using init_type            = std::pair<
                                   typename std::remove_const<Key>::type,
                                   typename std::remove_const<T>::type
                                 >;
    using hasher               = Hash;
    using key_equal            = Pred;
    using allocator_type       = Allocator;
    using pointer              = typename std::allocator_traits<Allocator>::pointer;
    using const_pointer        = typename std::allocator_traits<Allocator>::const_pointer;
    using reference            = value_type&;
    using const_reference      = const value_type&;
    using size_type            = std::size_t;
    using difference_type      = std::ptrdiff_t;

    using iterator             = implementation-defined;
    using const_iterator       = implementation-defined;

    using node_type            = implementation-defined;
    using insert_return_type   = implementation-defined;

    using stats                = stats-type; // if statistics are enabled

    // construct/copy/destroy
    unordered_node_map();
    explicit unordered_node_map(size_type n,
                                const hasher& hf = hasher(),
                                const key_equal& eql = key_equal(),
                                const allocator_type& a = allocator_type());
    template<class InputIterator>
      unordered_node_map(InputIterator f, InputIterator l,
                         size_type n = implementation-defined,
                         const hasher& hf = hasher(),
                         const key_equal& eql = key_equal(),
                         const allocator_type& a = allocator_type());
    unordered_node_map(const unordered_node_map& other);
    unordered_node_map(unordered_node_map&& other);
    template<class InputIterator>
      unordered_node_map(InputIterator f, InputIterator l, const allocator_type& a);
    explicit unordered_node_map(const Allocator& a);
    unordered_node_map(const unordered_node_map& other, const Allocator& a);
    unordered_node_map(unordered_node_map&& other, const Allocator& a);
    unordered_node_map(concurrent_node_map<Key, T, Hash, Pred, Allocator>&& other);
    unordered_node_map(std::initializer_list<value_type> il,
                       size_type n = implementation-defined
                       const hasher& hf = hasher(),
                       const key_equal& eql = key_equal(),
                       const allocator_type& a = allocator_type());
    unordered_node_map(size_type n, const allocator_type& a);
    unordered_node_map(size_type n, const hasher& hf, const allocator_type& a);
    template<class InputIterator>
      unordered_node_map(InputIterator f, InputIterator l, size_type n, const allocator_type& a);
    template<class InputIterator>
      unordered_node_map(InputIterator f, InputIterator l, size_type n, const hasher& hf,
                         const allocator_type& a);
    unordered_node_map(std::initializer_list<value_type> il, const allocator_type& a);
    unordered_node_map(std::initializer_list<value_type> il, size_type n,
                       const allocator_type& a);
    unordered_node_map(std::initializer_list<value_type> il, size_type n, const hasher& hf,
                       const allocator_type& a);
    ~unordered_node_map();
    unordered_node_map& operator=(const unordered_node_map& other);
    unordered_node_map& operator=(unordered_node_map&& other) noexcept(
      (boost::allocator_traits<Allocator>::is_always_equal::value ||
       boost::allocator_traits<Allocator>::propagate_on_container_move_assignment::value) &&
       std::is_same<pointer, value_type*>::value);
    unordered_node_map& operator=(std::initializer_list<value_type>);
    allocator_type get_allocator() const noexcept;

    // iterators
    iterator       begin() noexcept;
    const_iterator begin() const noexcept;
    iterator       end() noexcept;
    const_iterator end() const noexcept;
    const_iterator cbegin() const noexcept;
    const_iterator cend() const noexcept;

    // capacity
    [[nodiscard]] bool empty() const noexcept;
    size_type size() const noexcept;
    size_type max_size() const noexcept;

    // modifiers
    template<class... Args> std::pair<iterator, bool> emplace(Args&&... args);
    template<class... Args> iterator emplace_hint(const_iterator position, Args&&... args);
    std::pair<iterator, bool> insert(const value_type& obj);
    std::pair<iterator, bool> insert(const init_type& obj);
    std::pair<iterator, bool> insert(value_type&& obj);
    std::pair<iterator, bool> insert(init_type&& obj);
    iterator       insert(const_iterator hint, const value_type& obj);
    iterator       insert(const_iterator hint, const init_type& obj);
    iterator       insert(const_iterator hint, value_type&& obj);
    iterator       insert(const_iterator hint, init_type&& obj);
    template<class InputIterator> void insert(InputIterator first, InputIterator last);
    void insert(std::initializer_list<value_type>);
    insert_return_type insert(node_type&& nh);
    iterator insert(const_iterator hint, node_type&& nh);

    template<class... Args>
      std::pair<iterator, bool> try_emplace(const key_type& k, Args&&... args);
    template<class... Args>
      std::pair<iterator, bool> try_emplace(key_type&& k, Args&&... args);
    template<class K, class... Args>
      std::pair<iterator, bool> try_emplace(K&& k, Args&&... args);
    template<class... Args>
      iterator try_emplace(const_iterator hint, const key_type& k, Args&&... args);
    template<class... Args>
      iterator try_emplace(const_iterator hint, key_type&& k, Args&&... args);
    template<class K, class... Args>
      iterator try_emplace(const_iterator hint, K&& k, Args&&... args);
    template<class M>
      std::pair<iterator, bool> insert_or_assign(const key_type& k, M&& obj);
    template<class M>
      std::pair<iterator, bool> insert_or_assign(key_type&& k, M&& obj);
    template<class K, class M>
      std::pair<iterator, bool> insert_or_assign(K&& k, M&& obj);
    template<class M>
      iterator insert_or_assign(const_iterator hint, const key_type& k, M&& obj);
    template<class M>
      iterator insert_or_assign(const_iterator hint, key_type&& k, M&& obj);
    template<class K, class M>
      iterator insert_or_assign(const_iterator hint, K&& k, M&& obj);

    convertible-to-iterator     erase(iterator position);
    convertible-to-iterator     erase(const_iterator position);
    size_type                   erase(const key_type& k);
    template<class K> size_type erase(K&& k);
    iterator  erase(const_iterator first, const_iterator last);
    void      swap(unordered_node_map& other)
      noexcept(boost::allocator_traits<Allocator>::is_always_equal::value ||
               boost::allocator_traits<Allocator>::propagate_on_container_swap::value);
    node_type extract(const_iterator position);
    node_type extract(const key_type& key);
    template<class K> node_type extract(K&& key);
    init_type pull(const_iterator position);
    void      clear() noexcept;

    template<class H2, class P2>
      void merge(unordered_node_map<Key, T, H2, P2, Allocator>& source);
    template<class H2, class P2>
      void merge(unordered_node_map<Key, T, H2, P2, Allocator>&& source);

    // observers
    hasher hash_function() const;
    key_equal key_eq() const;

    // map operations
    iterator         find(const key_type& k);
    const_iterator   find(const key_type& k) const;
    template<class K>
      iterator       find(const K& k);
    template<class K>
      const_iterator find(const K& k) const;
    size_type        count(const key_type& k) const;
    template<class K>
      size_type      count(const K& k) const;
    bool             contains(const key_type& k) const;
    template<class K>
      bool           contains(const K& k) const;
    std::pair<iterator, iterator>               equal_range(const key_type& k);
    std::pair<const_iterator, const_iterator>   equal_range(const key_type& k) const;
    template<class K>
      std::pair<iterator, iterator>             equal_range(const K& k);
    template<class K>
      std::pair<const_iterator, const_iterator> equal_range(const K& k) const;

    // element access
    mapped_type& operator[](const key_type& k);
    mapped_type& operator[](key_type&& k);
    template<class K> mapped_type& operator[](K&& k);
    mapped_type& at(const key_type& k);
    const mapped_type& at(const key_type& k) const;
    template<class K> mapped_type& at(const K& k);
    template<class K> const mapped_type& at(const K& k) const;

    // bucket interface
    size_type bucket_count() const noexcept;

    // hash policy
    float load_factor() const noexcept;
    float max_load_factor() const noexcept;
    void max_load_factor(float z);
    size_type max_load() const noexcept;
    void rehash(size_type n);
    void reserve(size_type n);

    // statistics (if enabled)
    stats get_stats() const;
    void reset_stats() noexcept;
  };

  // Deduction Guides
  template<class InputIterator,
           class Hash = boost::hash<iter-key-type<InputIterator>>,
           class Pred = std::equal_to<iter-key-type<InputIterator>>,
           class Allocator = std::allocator<iter-to-alloc-type<InputIterator>>>
    unordered_node_map(InputIterator, InputIterator, typename see below::size_type = see below,
                       Hash = Hash(), Pred = Pred(), Allocator = Allocator())
      -> unordered_node_map<iter-key-type<InputIterator>, iter-mapped-type<InputIterator>, Hash,
                            Pred, Allocator>;

  template<class Key, class T, class Hash = boost::hash<Key>,
           class Pred = std::equal_to<Key>,
           class Allocator = std::allocator<std::pair<const Key, T>>>
    unordered_node_map(std::initializer_list<std::pair<Key, T>>,
                       typename see below::size_type = see below, Hash = Hash(),
                       Pred = Pred(), Allocator = Allocator())
      -> unordered_node_map<Key, T, Hash, Pred, Allocator>;

  template<class InputIterator, class Allocator>
    unordered_node_map(InputIterator, InputIterator, typename see below::size_type, Allocator)
      -> unordered_node_map<iter-key-type<InputIterator>, iter-mapped-type<InputIterator>,
                            boost::hash<iter-key-type<InputIterator>>,
                            std::equal_to<iter-key-type<InputIterator>>, Allocator>;

  template<class InputIterator, class Allocator>
    unordered_node_map(InputIterator, InputIterator, Allocator)
      -> unordered_node_map<iter-key-type<InputIterator>, iter-mapped-type<InputIterator>,
                            boost::hash<iter-key-type<InputIterator>>,
                            std::equal_to<iter-key-type<InputIterator>>, Allocator>;

  template<class InputIterator, class Hash, class Allocator>
    unordered_node_map(InputIterator, InputIterator, typename see below::size_type, Hash,
                       Allocator)
      -> unordered_node_map<iter-key-type<InputIterator>, iter-mapped-type<InputIterator>, Hash,
                            std::equal_to<iter-key-type<InputIterator>>, Allocator>;

  template<class Key, class T, class Allocator>
    unordered_node_map(std::initializer_list<std::pair<Key, T>>, typename see below::size_type,
                       Allocator)
      -> unordered_node_map<Key, T, boost::hash<Key>, std::equal_to<Key>, Allocator>;

  template<class Key, class T, class Allocator>
    unordered_node_map(std::initializer_list<std::pair<Key, T>>, Allocator)
      -> unordered_node_map<Key, T, boost::hash<Key>, std::equal_to<Key>, Allocator>;

  template<class Key, class T, class Hash, class Allocator>
    unordered_node_map(std::initializer_list<std::pair<Key, T>>, typename see below::size_type,
                       Hash, Allocator)
      -> unordered_node_map<Key, T, Hash, std::equal_to<Key>, Allocator>;

} // namespace unordered
} // namespace boost
....

'''''

[[unordered_node_map_description]]
==== Description

*Template Parameters*

[width="100%",cols="50%,50%",]
|===
|_Key_ |`std::pair++<++const Key, T++>++` must be
https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[EmplaceConstructible]
into the container from any `std::pair` object convertible to it, and it
also must be
https://en.cppreference.com/w/cpp/named_req/Erasable[Erasable] from the
container.

|_T_ |

|_Hash_ |A unary function object type that acts a hash function for a
`Key`. It takes a single argument of type `Key` and returns a value of
type `std::size++_++t`.

|_Pred_ |A binary function object that induces an equivalence relation
on values of type `Key`. It takes two arguments of type `Key` and
returns a value of type `bool`.

|_Allocator_ |An allocator whose value type is the same as the
container’s value type. Allocators using
https://en.cppreference.com/w/cpp/named_req/Allocator#Fancy_pointers[fancy
pointers] are supported.
|===

The element nodes of the container are held into an internal _bucket
array_. A node is inserted into a bucket determined by the hash code of
its element, but if the bucket is already occupied (a _collision_), an
available one in the vicinity of the original position is used.

The size of the bucket array can be automatically increased by a call to
`insert`/`emplace`, or as a result of calling `rehash`/`reserve`. The
_load factor_ of the container (number of elements divided by number of
buckets) is never greater than `max++_++load++_++factor()`, except
possibly for small sizes where the implementation may decide to allow
for higher loads.

If
link:../../../../../container_hash/doc/html/hash.html#ref_hash_is_avalanchinghash[`hash++_++is++_++avalanching`]`++<++Hash++>++::value`
is `true`, the hash function is used as-is; otherwise, a bit-mixing
post-processing stage is added to increase the quality of hashing at the
expense of extra computational cost.

'''''

[[unordered_node_map_configuration_macros]]
==== Configuration Macros

[[unordered_node_map_boost_unordered_enable_stats]]
===== `BOOST++_++UNORDERED++_++ENABLE++_++STATS`

Globally define this macro to enable
link:reference/stats.html#stats[statistics calculation] for the
container. Note that this option decreases the overall performance of
many operations.

'''''

[[unordered_node_map_typedefs]]
==== Typedefs

[source,highlight]
----
typedef implementation-defined iterator;
----

An iterator whose value type is `value++_++type`.

The iterator category is at least a forward iterator.

Convertible to `const++_++iterator`.

'''''

[source,highlight]
----
typedef implementation-defined const_iterator;
----

A constant iterator whose value type is `value++_++type`.

The iterator category is at least a forward iterator.

'''''

[source,highlight]
----
typedef implementation-defined node_type;
----

A class for holding extracted container elements, modelling
https://en.cppreference.com/w/cpp/container/node_handle[NodeHandle].

'''''

[source,highlight]
----
typedef implementation-defined insert_return_type;
----

A specialization of an internal class template:

[source,highlight]
----
template<class Iterator, class NodeType>
struct insert_return_type // name is exposition only
{
  Iterator position;
  bool     inserted;
  NodeType node;
};
----

with `Iterator` = `iterator` and `NodeType` = `node++_++type`.

'''''

[[unordered_node_map_constructors]]
==== Constructors

[[unordered_node_map_default_constructor]]
===== Default Constructor

[source,highlight]
----
unordered_node_map();
----

Constructs an empty container using `hasher()` as the hash function,
`key++_++equal()` as the key equality predicate and
`allocator++_++type()` as the allocator.

[cols=",",]
|===
|Postconditions: |`size() == 0`

|Requires: |If the defaults are used, `hasher`, `key++_++equal` and
`allocator++_++type` need to be
https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[DefaultConstructible].
|===

'''''

[[unordered_node_map_bucket_count_constructor]]
===== Bucket Count Constructor

[source,highlight]
----
explicit unordered_node_map(size_type n,
                            const hasher& hf = hasher(),
                            const key_equal& eql = key_equal(),
                            const allocator_type& a = allocator_type());
----

Constructs an empty container with at least `n` buckets, using `hf` as
the hash function, `eql` as the key equality predicate, and `a` as the
allocator.

[cols=",",]
|===
|Postconditions: |`size() == 0`

|Requires: |If the defaults are used, `hasher`, `key++_++equal` and
`allocator++_++type` need to be
https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[DefaultConstructible].
|===

'''''

[[unordered_node_map_iterator_range_constructor]]
===== Iterator Range Constructor

[source,highlight]
----
template<class InputIterator>
  unordered_node_map(InputIterator f, InputIterator l,
                     size_type n = implementation-defined,
                     const hasher& hf = hasher(),
                     const key_equal& eql = key_equal(),
                     const allocator_type& a = allocator_type());
----

Constructs an empty container with at least `n` buckets, using `hf` as
the hash function, `eql` as the key equality predicate and `a` as the
allocator, and inserts the elements from `++[++f, l)` into it.

[cols=",",]
|===
|Requires: |If the defaults are used, `hasher`, `key++_++equal` and
`allocator++_++type` need to be
https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[DefaultConstructible].
|===

'''''

[[unordered_node_map_copy_constructor]]
===== Copy Constructor

[source,highlight]
----
unordered_node_map(unordered_node_map const& other);
----

The copy constructor. Copies the contained elements, hash function,
predicate and allocator.

If `Allocator::select++_++on++_++container++_++copy++_++construction`
exists and has the right signature, the allocator will be constructed
from its result.

'''''

[[unordered_node_map_move_constructor]]
===== Move Constructor

[source,highlight]
----
unordered_node_map(unordered_node_map&& other);
----

The move constructor. The internal bucket array of `other` is
transferred directly to the new container. The hash function, predicate
and allocator are moved-constructed from `other`. If statistics are
link:#unordered_node_map_boost_unordered_enable_stats[enabled],
transfers the internal statistical information from `other` and calls
`other.reset++_++stats()`.

'''''

[[unordered_node_map_iterator_range_constructor_with_allocator]]
===== Iterator Range Constructor with Allocator

[source,highlight]
----
template<class InputIterator>
  unordered_node_map(InputIterator f, InputIterator l, const allocator_type& a);
----

Constructs an empty container using `a` as the allocator, with the
default hash function and key equality predicate and inserts the
elements from `++[++f, l)` into it.

[cols=",",]
|===
|Requires: |`hasher`, `key++_++equal` need to be
https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[DefaultConstructible].
|===

'''''

[[unordered_node_map_allocator_constructor]]
===== Allocator Constructor

[source,highlight]
----
explicit unordered_node_map(Allocator const& a);
----

Constructs an empty container, using allocator `a`.

'''''

[[unordered_node_map_copy_constructor_with_allocator]]
===== Copy Constructor with Allocator

[source,highlight]
----
unordered_node_map(unordered_node_map const& other, Allocator const& a);
----

Constructs a container, copying `other`'s contained elements, hash
function, and predicate, but using allocator `a`.

'''''

[[unordered_node_map_move_constructor_with_allocator]]
===== Move Constructor with Allocator

[source,highlight]
----
unordered_node_map(unordered_node_map&& other, Allocator const& a);
----

If `a == other.get++_++allocator()`, the element nodes of `other` are
transferred directly to the new container; otherwise, elements are
moved-constructed from those of `other`. The hash function and predicate
are moved-constructed from `other`, and the allocator is
copy-constructed from `a`. If statistics are
link:#unordered_node_map_boost_unordered_enable_stats[enabled],
transfers the internal statistical information from `other` iff
`a == other.get++_++allocator()`, and always calls
`other.reset++_++stats()`.

'''''

[[unordered_node_map_move_constructor_from_concurrent_node_map]]
===== Move Constructor from concurrent++_++node++_++map

[source,highlight]
----
unordered_node_map(concurrent_node_map<Key, T, Hash, Pred, Allocator>&& other);
----

Move construction from a
link:#concurrent_node_map[`concurrent++_++node++_++map`]. The internal
bucket array of `other` is transferred directly to the new container.
The hash function, predicate and allocator are moved-constructed from
`other`. If statistics are
link:#unordered_node_map_boost_unordered_enable_stats[enabled],
transfers the internal statistical information from `other` and calls
`other.reset++_++stats()`.

[cols=",",]
|===
|Complexity: |Constant time.
|Concurrency: |Blocking on `other`.
|===

'''''

[[unordered_node_map_initializer_list_constructor]]
===== Initializer List Constructor

[source,highlight]
----
unordered_node_map(std::initializer_list<value_type> il,
              size_type n = implementation-defined
              const hasher& hf = hasher(),
              const key_equal& eql = key_equal(),
              const allocator_type& a = allocator_type());
----

Constructs an empty container with at least `n` buckets, using `hf` as
the hash function, `eql` as the key equality predicate and `a`, and
inserts the elements from `il` into it.

[cols=",",]
|===
|Requires: |If the defaults are used, `hasher`, `key++_++equal` and
`allocator++_++type` need to be
https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[DefaultConstructible].
|===

'''''

[[unordered_node_map_bucket_count_constructor_with_allocator]]
===== Bucket Count Constructor with Allocator

[source,highlight]
----
unordered_node_map(size_type n, allocator_type const& a);
----

Constructs an empty container with at least `n` buckets, using `hf` as
the hash function, the default hash function and key equality predicate
and `a` as the allocator.

[cols=",",]
|===
|Postconditions: |`size() == 0`

|Requires: |`hasher` and `key++_++equal` need to be
https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[DefaultConstructible].
|===

'''''

[[unordered_node_map_bucket_count_constructor_with_hasher_and_allocator]]
===== Bucket Count Constructor with Hasher and Allocator

[source,highlight]
----
unordered_node_map(size_type n, hasher const& hf, allocator_type const& a);
----

Constructs an empty container with at least `n` buckets, using `hf` as
the hash function, the default key equality predicate and `a` as the
allocator.

[cols=",",]
|===
|Postconditions: |`size() == 0`

|Requires: |`key++_++equal` needs to be
https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[DefaultConstructible].
|===

'''''

[[unordered_node_map_iterator_range_constructor_with_bucket_count_and_allocator]]
===== Iterator Range Constructor with Bucket Count and Allocator

[source,highlight]
----
template<class InputIterator>
  unordered_node_map(InputIterator f, InputIterator l, size_type n, const allocator_type& a);
----

Constructs an empty container with at least `n` buckets, using `a` as
the allocator and default hash function and key equality predicate, and
inserts the elements from `++[++f, l)` into it.

[cols=",",]
|===
|Requires: |`hasher`, `key++_++equal` need to be
https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[DefaultConstructible].
|===

'''''

[[unordered_node_map_iterator_range_constructor_with_bucket_count_and_hasher]]
===== Iterator Range Constructor with Bucket Count and Hasher

[source,highlight]
----
    template<class InputIterator>
      unordered_node_map(InputIterator f, InputIterator l, size_type n, const hasher& hf,
                         const allocator_type& a);
----

Constructs an empty container with at least `n` buckets, using `hf` as
the hash function, `a` as the allocator, with the default key equality
predicate, and inserts the elements from `++[++f, l)` into it.

[cols=",",]
|===
|Requires: |`key++_++equal` needs to be
https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[DefaultConstructible].
|===

'''''

[[unordered_node_map_initializer_list_constructor_with_allocator]]
===== initializer++_++list Constructor with Allocator

[source,highlight]
----
unordered_node_map(std::initializer_list<value_type> il, const allocator_type& a);
----

Constructs an empty container using `a` and default hash function and
key equality predicate, and inserts the elements from `il` into it.

[cols=",",]
|===
|Requires: |`hasher` and `key++_++equal` need to be
https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[DefaultConstructible].
|===

'''''

[[unordered_node_map_initializer_list_constructor_with_bucket_count_and_allocator]]
===== initializer++_++list Constructor with Bucket Count and Allocator

[source,highlight]
----
unordered_node_map(std::initializer_list<value_type> il, size_type n, const allocator_type& a);
----

Constructs an empty container with at least `n` buckets, using `a` and
default hash function and key equality predicate, and inserts the
elements from `il` into it.

[cols=",",]
|===
|Requires: |`hasher` and `key++_++equal` need to be
https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[DefaultConstructible].
|===

'''''

[[unordered_node_map_initializer_list_constructor_with_bucket_count_and_hasher_and_allocator]]
===== initializer++_++list Constructor with Bucket Count and Hasher and Allocator

[source,highlight]
----
unordered_node_map(std::initializer_list<value_type> il, size_type n, const hasher& hf,
                   const allocator_type& a);
----

Constructs an empty container with at least `n` buckets, using `hf` as
the hash function, `a` as the allocator and default key equality
predicate,and inserts the elements from `il` into it.

[cols=",",]
|===
|Requires: |`key++_++equal` needs to be
https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[DefaultConstructible].
|===

'''''

[[unordered_node_map_destructor]]
==== Destructor

[source,highlight]
----
~unordered_node_map();
----

[cols=",",]
|===
|Note: |The destructor is applied to every element, and all memory is
deallocated
|===

'''''

[[unordered_node_map_assignment]]
==== Assignment

[[unordered_node_map_copy_assignment]]
===== Copy Assignment

[source,highlight]
----
unordered_node_map& operator=(unordered_node_map const& other);
----

The assignment operator. Destroys previously existing elements,
copy-assigns the hash function and predicate from `other`, copy-assigns
the allocator from `other` if
`Alloc::propagate++_++on++_++container++_++copy++_++assignment` exists
and
`Alloc::propagate++_++on++_++container++_++copy++_++assignment::value`
is `true`, and finally inserts copies of the elements of `other`.

[cols=",",]
|===
|Requires: |`value++_++type` is
https://en.cppreference.com/w/cpp/named_req/CopyInsertable[CopyInsertable]
|===

'''''

[[unordered_node_map_move_assignment]]
===== Move Assignment

[source,highlight]
----
unordered_node_map& operator=(unordered_node_map&& other)
  noexcept((boost::allocator_traits<Allocator>::is_always_equal::value ||
            boost::allocator_traits<Allocator>::propagate_on_container_move_assignment::value) &&
            std::is_same<pointer, value_type*>::value);
----

The move assignment operator. Destroys previously existing elements,
swaps the hash function and predicate from `other`, and move-assigns the
allocator from `other` if
`Alloc::propagate++_++on++_++container++_++move++_++assignment` exists
and
`Alloc::propagate++_++on++_++container++_++move++_++assignment::value`
is `true`. If at this point the allocator is equal to
`other.get++_++allocator()`, the internal bucket array of `other` is
transferred directly to the new container; otherwise, inserts
move-constructed copies of the elements of `other`. If statistics are
link:#unordered_node_map_boost_unordered_enable_stats[enabled],
transfers the internal statistical information from `other` iff the
final allocator is equal to `other.get++_++allocator()`, and always
calls `other.reset++_++stats()`.

'''''

[[unordered_node_map_initializer_list_assignment]]
===== Initializer List Assignment

[source,highlight]
----
unordered_node_map& operator=(std::initializer_list<value_type> il);
----

Assign from values in initializer list. All previously existing elements
are destroyed.

[cols=",",]
|===
|Requires: |`value++_++type` is
https://en.cppreference.com/w/cpp/named_req/CopyInsertable[CopyInsertable]
|===

[[unordered_node_map_iterators]]
==== Iterators

[[unordered_node_map_begin]]
===== begin

[source,highlight]
----
iterator begin() noexcept;
const_iterator begin() const noexcept;
----

[cols=",",]
|===
|Returns: |An iterator referring to the first element of the container,
or if the container is empty the past-the-end value for the container.

|Complexity: |O(`bucket++_++count()`)
|===

'''''

[[unordered_node_map_end]]
===== end

[source,highlight]
----
iterator end() noexcept;
const_iterator end() const noexcept;
----

[cols=",",]
|===
|Returns: |An iterator which refers to the past-the-end value for the
container.
|===

'''''

[[unordered_node_map_cbegin]]
===== cbegin

[source,highlight]
----
const_iterator cbegin() const noexcept;
----

[cols=",",]
|===
|Returns: |A `const++_++iterator` referring to the first element of the
container, or if the container is empty the past-the-end value for the
container.

|Complexity: |O(`bucket++_++count()`)
|===

'''''

[[unordered_node_map_cend]]
===== cend

[source,highlight]
----
const_iterator cend() const noexcept;
----

[cols=",",]
|===
|Returns: |A `const++_++iterator` which refers to the past-the-end value
for the container.
|===

'''''

[[unordered_node_map_size_and_capacity]]
==== Size and Capacity

[[unordered_node_map_empty]]
===== empty

[source,highlight]
----
[[nodiscard]] bool empty() const noexcept;
----

[cols=",",]
|===
|Returns: |`size() == 0`
|===

'''''

[[unordered_node_map_size]]
===== size

[source,highlight]
----
size_type size() const noexcept;
----

[cols=",",]
|===
|Returns: |`std::distance(begin(), end())`
|===

'''''

[[unordered_node_map_max_size]]
===== max++_++size

[source,highlight]
----
size_type max_size() const noexcept;
----

[cols=",",]
|===
|Returns: |`size()` of the largest possible container.
|===

'''''

[[unordered_node_map_modifiers]]
==== Modifiers

[[unordered_node_map_emplace]]
===== emplace

[source,highlight]
----
template<class... Args> std::pair<iterator, bool> emplace(Args&&... args);
----

Inserts an object, constructed with the arguments `args`, in the
container if and only if there is no element in the container with an
equivalent key.

[width="100%",cols="50%,50%",]
|===
|Requires: |`value++_++type` is constructible from `args`.

|Returns: a|
The `bool` component of the return type is `true` if an insert took
place. +

If an insert took place, then the iterator points to the newly inserted
element. Otherwise, it points to the element with equivalent key.

|Throws: |If an exception is thrown by an operation other than a call to
`hasher` the function has no effect.

|Notes: a|
Can invalidate iterators, but only if the insert causes the load to be
greater than the maximum load. +

If `args…​` is of the form `k,v`, it delays constructing the whole object
until it is certain that an element should be inserted, using only the
`k` argument to check. This optimization happens when `key++_++type` is
move constructible or when the `k` argument is a `key++_++type`.

|===

'''''

[[unordered_node_map_emplace_hint]]
===== emplace++_++hint

[source,highlight]
----
    template<class... Args> iterator emplace_hint(const_iterator position, Args&&... args);
----

Inserts an object, constructed with the arguments `args`, in the
container if and only if there is no element in the container with an
equivalent key.

`position` is a suggestion to where the element should be inserted. This
implementation ignores it.

[width="100%",cols="50%,50%",]
|===
|Requires: |`value++_++type` is constructible from `args`.

|Returns: a|
The `bool` component of the return type is `true` if an insert took
place. +

If an insert took place, then the iterator points to the newly inserted
element. Otherwise, it points to the element with equivalent key.

|Throws: |If an exception is thrown by an operation other than a call to
`hasher` the function has no effect.

|Notes: a|
Can invalidate iterators, but only if the insert causes the load to be
greater than the maximum load. +

If `args…​` is of the form `k,v`, it delays constructing the whole object
until it is certain that an element should be inserted, using only the
`k` argument to check. This optimization happens when `key++_++type` is
move constructible or when the `k` argument is a `key++_++type`.

|===

'''''

[[unordered_node_map_copy_insert]]
===== Copy Insert

[source,highlight]
----
std::pair<iterator, bool> insert(const value_type& obj);
std::pair<iterator, bool> insert(const init_type& obj);
----

Inserts `obj` in the container if and only if there is no element in the
container with an equivalent key.

[width="100%",cols="50%,50%",]
|===
|Requires: |`value++_++type` is
https://en.cppreference.com/w/cpp/named_req/CopyInsertable[CopyInsertable].

|Returns: a|
The `bool` component of the return type is `true` if an insert took
place. +

If an insert took place, then the iterator points to the newly inserted
element. Otherwise, it points to the element with equivalent key.

|Throws: |If an exception is thrown by an operation other than a call to
`hasher` the function has no effect.

|Notes: a|
Can invalidate iterators, but only if the insert causes the load to be
greater than the maximum load. +

A call of the form `insert(x)`, where `x` is equally convertible to both
`const value++_++type&` and `const init++_++type&`, is not ambiguous and
selects the `init++_++type` overload.

|===

'''''

[[unordered_node_map_move_insert]]
===== Move Insert

[source,highlight]
----
std::pair<iterator, bool> insert(value_type&& obj);
std::pair<iterator, bool> insert(init_type&& obj);
----

Inserts `obj` in the container if and only if there is no element in the
container with an equivalent key.

[width="100%",cols="50%,50%",]
|===
|Requires: |`value++_++type` is
https://en.cppreference.com/w/cpp/named_req/MoveInsertable[MoveInsertable].

|Returns: a|
The `bool` component of the return type is `true` if an insert took
place. +

If an insert took place, then the iterator points to the newly inserted
element. Otherwise, it points to the element with equivalent key.

|Throws: |If an exception is thrown by an operation other than a call to
`hasher` the function has no effect.

|Notes: a|
Can invalidate iterators, but only if the insert causes the load to be
greater than the maximum load. +

A call of the form `insert(x)`, where `x` is equally convertible to both
`value++_++type&&` and `init++_++type&&`, is not ambiguous and selects
the `init++_++type` overload.

|===

'''''

[[unordered_node_map_copy_insert_with_hint]]
===== Copy Insert with Hint

[source,highlight]
----
iterator insert(const_iterator hint, const value_type& obj);
iterator insert(const_iterator hint, const init_type& obj);
----

Inserts `obj` in the container if and only if there is no element in the
container with an equivalent key.

`hint` is a suggestion to where the element should be inserted. This
implementation ignores it.

[width="100%",cols="50%,50%",]
|===
|Requires: |`value++_++type` is
https://en.cppreference.com/w/cpp/named_req/CopyInsertable[CopyInsertable].

|Returns: a|
The `bool` component of the return type is `true` if an insert took
place. +

If an insert took place, then the iterator points to the newly inserted
element. Otherwise, it points to the element with equivalent key.

|Throws: |If an exception is thrown by an operation other than a call to
`hasher` the function has no effect.

|Notes: a|
Can invalidate iterators, but only if the insert causes the load to be
greater than the maximum load. +

A call of the form `insert(hint, x)`, where `x` is equally convertible
to both `const value++_++type&` and `const init++_++type&`, is not
ambiguous and selects the `init++_++type` overload.

|===

'''''

[[unordered_node_map_move_insert_with_hint]]
===== Move Insert with Hint

[source,highlight]
----
iterator insert(const_iterator hint, value_type&& obj);
iterator insert(const_iterator hint, init_type&& obj);
----

Inserts `obj` in the container if and only if there is no element in the
container with an equivalent key.

`hint` is a suggestion to where the element should be inserted. This
implementation ignores it.

[width="100%",cols="50%,50%",]
|===
|Requires: |`value++_++type` is
https://en.cppreference.com/w/cpp/named_req/MoveInsertable[MoveInsertable].

|Returns: a|
The `bool` component of the return type is `true` if an insert took
place. +

If an insert took place, then the iterator points to the newly inserted
element. Otherwise, it points to the element with equivalent key.

|Throws: |If an exception is thrown by an operation other than a call to
`hasher` the function has no effect.

|Notes: a|
Can invalidate iterators, but only if the insert causes the load to be
greater than the maximum load. +

A call of the form `insert(hint, x)`, where `x` is equally convertible
to both `value++_++type&&` and `init++_++type&&`, is not ambiguous and
selects the `init++_++type` overload.

|===

'''''

[[unordered_node_map_insert_iterator_range]]
===== Insert Iterator Range

[source,highlight]
----
template<class InputIterator> void insert(InputIterator first, InputIterator last);
----

Inserts a range of elements into the container. Elements are inserted if
and only if there is no element in the container with an equivalent key.

[cols=",",]
|===
|Requires: |`value++_++type` is
https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[EmplaceConstructible]
into the container from `++*++first`.

|Throws: |When inserting a single element, if an exception is thrown by
an operation other than a call to `hasher` the function has no effect.

|Notes: |Can invalidate iterators, but only if the insert causes the
load to be greater than the maximum load.
|===

'''''

[[unordered_node_map_insert_initializer_list]]
===== Insert Initializer List

[source,highlight]
----
void insert(std::initializer_list<value_type>);
----

Inserts a range of elements into the container. Elements are inserted if
and only if there is no element in the container with an equivalent key.

[cols=",",]
|===
|Requires: |`value++_++type` is
https://en.cppreference.com/w/cpp/named_req/CopyInsertable[CopyInsertable]
into the container.

|Throws: |When inserting a single element, if an exception is thrown by
an operation other than a call to `hasher` the function has no effect.

|Notes: |Can invalidate iterators, but only if the insert causes the
load to be greater than the maximum load.
|===

'''''

[[unordered_node_map_insert_node]]
===== Insert Node

[source,highlight]
----
insert_return_type insert(node_type&& nh);
----

If `nh` is not empty, inserts the associated element in the container if
and only if there is no element in the container with a key equivalent
to `nh.key()`. `nh` is empty when the function returns.

[width="100%",cols="50%,50%",]
|===
|Returns: a|
An `insert++_++return++_++type` object constructed from `position`,
`inserted` and `node`: +

* If `nh` is empty, `inserted` is `false`, `position` is `end()`, and
`node` is empty.
* Otherwise if the insertion took place, `inserted` is true, `position`
points to the inserted element, and `node` is empty.
* If the insertion failed, `inserted` is false, `node` has the previous
value of `nh`, and `position` points to an element with a key equivalent
to `nh.key()`.

|Throws: |If an exception is thrown by an operation other than a call to
`hasher` the function has no effect.

|Notes: |Behavior is undefined if `nh` is not empty and the allocators
of `nh` and the container are not equal.
|===

'''''

[[unordered_node_map_insert_node_with_hint]]
===== Insert Node with Hint

[source,highlight]
----
iterator insert(const_iterator hint, node_type&& nh);
----

If `nh` is not empty, inserts the associated element in the container if
and only if there is no element in the container with a key equivalent
to `nh.key()`. `nh` becomes empty if insertion took place, otherwise it
is not changed.

`hint` is a suggestion to where the element should be inserted. This
implementation ignores it.

[cols=",",]
|===
|Returns: |The iterator returned is `end()` if `nh` is empty. If
insertion took place, then the iterator points to the newly inserted
element; otherwise, it points to the element with equivalent key.

|Throws: |If an exception is thrown by an operation other than a call to
`hasher` the function has no effect.

|Notes: |Behavior is undefined if `nh` is not empty and the allocators
of `nh` and the container are not equal.
|===

'''''

[[unordered_node_map_try_emplace]]
===== try++_++emplace

[source,highlight]
----
template<class... Args>
  std::pair<iterator, bool> try_emplace(const key_type& k, Args&&... args);
template<class... Args>
  std::pair<iterator, bool> try_emplace(key_type&& k, Args&&... args);
template<class K, class... Args>
  std::pair<iterator, bool> try_emplace(K&& k, Args&&... args);
----

Inserts a new element into the container if there is no existing element
with key `k` contained within it.

If there is an existing element with key `k` this function does nothing.

[width="100%",cols="50%,50%",]
|===
|Returns: a|
The `bool` component of the return type is `true` if an insert took
place. +

If an insert took place, then the iterator points to the newly inserted
element. Otherwise, it points to the element with equivalent key.

|Throws: |If an exception is thrown by an operation other than a call to
`hasher` the function has no effect.

|Notes: a|
This function is similiar to link:#unordered_node_map_emplace[emplace],
with the difference that no `value++_++type` is constructed if there is
an element with an equivalent key; otherwise, the construction is of the
form: +

[source,highlight]
----
// first two overloads
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<Key>(k)),
           std::forward_as_tuple(std::forward<Args>(args)...))

// third overload
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<K>(k)),
           std::forward_as_tuple(std::forward<Args>(args)...))
----

unlike link:#unordered_node_map_emplace[emplace], which simply forwards
all arguments to `value++_++type`'s constructor.

Can invalidate iterators, but only if the insert causes the load to be
greater than the maximum load.

The `template++<++class K, class... Args++>++` overload only
participates in overload resolution if `Hash::is++_++transparent` and
`Pred::is++_++transparent` are valid member typedefs and neither
`iterator` nor `const++_++iterator` are implicitly convertible from `K`.
The library assumes that `Hash` is callable with both `K` and `Key` and
that `Pred` is transparent. This enables heterogeneous lookup which
avoids the cost of instantiating an instance of the `Key` type.

|===

'''''

[[unordered_node_map_try_emplace_with_hint]]
===== try++_++emplace with Hint

[source,highlight]
----
template<class... Args>
  iterator try_emplace(const_iterator hint, const key_type& k, Args&&... args);
template<class... Args>
  iterator try_emplace(const_iterator hint, key_type&& k, Args&&... args);
template<class K, class... Args>
  iterator try_emplace(const_iterator hint, K&& k, Args&&... args);
----

Inserts a new element into the container if there is no existing element
with key `k` contained within it.

If there is an existing element with key `k` this function does nothing.

`hint` is a suggestion to where the element should be inserted. This
implementation ignores it.

[width="100%",cols="50%,50%",]
|===
|Returns: |If an insert took place, then the iterator points to the
newly inserted element. Otherwise, it points to the element with
equivalent key.

|Throws: |If an exception is thrown by an operation other than a call to
`hasher` the function has no effect.

|Notes: a|
This function is similiar to
link:#unordered_node_map_emplace_hint[emplace++_++hint], with the
difference that no `value++_++type` is constructed if there is an
element with an equivalent key; otherwise, the construction is of the
form: +

[source,highlight]
----
// first two overloads
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<Key>(k)),
           std::forward_as_tuple(std::forward<Args>(args)...))

// third overload
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<K>(k)),
           std::forward_as_tuple(std::forward<Args>(args)...))
----

unlike link:#unordered_node_map_emplace_hint[emplace++_++hint], which
simply forwards all arguments to `value++_++type`'s constructor.

Can invalidate iterators, but only if the insert causes the load to be
greater than the maximum load.

The `template++<++class K, class... Args++>++` overload only
participates in overload resolution if `Hash::is++_++transparent` and
`Pred::is++_++transparent` are valid member typedefs and neither
`iterator` nor `const++_++iterator` are implicitly convertible from `K`.
The library assumes that `Hash` is callable with both `K` and `Key` and
that `Pred` is transparent. This enables heterogeneous lookup which
avoids the cost of instantiating an instance of the `Key` type.

|===

'''''

[[unordered_node_map_insert_or_assign]]
===== insert++_++or++_++assign

[source,highlight]
----
template<class M>
  std::pair<iterator, bool> insert_or_assign(const key_type& k, M&& obj);
template<class M>
  std::pair<iterator, bool> insert_or_assign(key_type&& k, M&& obj);
template<class K, class M>
  std::pair<iterator, bool> insert_or_assign(K&& k, M&& obj);
----

Inserts a new element into the container or updates an existing one by
assigning to the contained value.

If there is an element with key `k`, then it is updated by assigning
`std::forward++<++M++>++(obj)`.

If there is no such element, it is added to the container as:

[source,highlight]
----
// first two overloads
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<Key>(k)),
           std::forward_as_tuple(std::forward<M>(obj)))

// third overload
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<K>(k)),
           std::forward_as_tuple(std::forward<M>(obj)))
----

[width="100%",cols="50%,50%",]
|===
|Returns: a|
The `bool` component of the return type is `true` if an insert took
place. +

If an insert took place, then the iterator points to the newly inserted
element. Otherwise, it points to the element with equivalent key.

|Throws: |If an exception is thrown by an operation other than a call to
`hasher` the function has no effect.

|Notes: a|
Can invalidate iterators, but only if the insert causes the load to be
greater than the maximum load. +

The `template++<++class K, class M++>++` only participates in overload
resolution if `Hash::is++_++transparent` and `Pred::is++_++transparent`
are valid member typedefs. The library assumes that `Hash` is callable
with both `K` and `Key` and that `Pred` is transparent. This enables
heterogeneous lookup which avoids the cost of instantiating an instance
of the `Key` type.

|===

'''''

[[unordered_node_map_insert_or_assign_with_hint]]
===== insert++_++or++_++assign with Hint

[source,highlight]
----
template<class M>
  iterator insert_or_assign(const_iterator hint, const key_type& k, M&& obj);
template<class M>
  iterator insert_or_assign(const_iterator hint, key_type&& k, M&& obj);
template<class K, class M>
  iterator insert_or_assign(const_iterator hint, K&& k, M&& obj);
----

Inserts a new element into the container or updates an existing one by
assigning to the contained value.

If there is an element with key `k`, then it is updated by assigning
`std::forward++<++M++>++(obj)`.

If there is no such element, it is added to the container as:

[source,highlight]
----
// first two overloads
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<Key>(k)),
           std::forward_as_tuple(std::forward<M>(obj)))

// third overload
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<K>(k)),
           std::forward_as_tuple(std::forward<M>(obj)))
----

`hint` is a suggestion to where the element should be inserted. This
implementation ignores it.

[width="100%",cols="50%,50%",]
|===
|Returns: |If an insert took place, then the iterator points to the
newly inserted element. Otherwise, it points to the element with
equivalent key.

|Throws: |If an exception is thrown by an operation other than a call to
`hasher` the function has no effect.

|Notes: a|
Can invalidate iterators, but only if the insert causes the load to be
greater than the maximum load. +

The `template++<++class K, class M++>++` only participates in overload
resolution if `Hash::is++_++transparent` and `Pred::is++_++transparent`
are valid member typedefs. The library assumes that `Hash` is callable
with both `K` and `Key` and that `Pred` is transparent. This enables
heterogeneous lookup which avoids the cost of instantiating an instance
of the `Key` type.

|===

'''''

[[unordered_node_map_erase_by_position]]
===== Erase by Position

[source,highlight]
----
convertible-to-iterator erase(iterator position);
convertible-to-iterator erase(const_iterator position);
----

Erase the element pointed to by `position`.

[cols=",",]
|===
|Returns: |An opaque object implicitly convertible to the `iterator` or
`const++_++iterator` immediately following `position` prior to the
erasure.

|Throws: |Nothing.

|Notes: |The opaque object returned must only be discarded or
immediately converted to `iterator` or `const++_++iterator`.
|===

'''''

[[unordered_node_map_erase_by_key]]
===== Erase by Key

[source,highlight]
----
size_type erase(const key_type& k);
template<class K> size_type erase(K&& k);
----

Erase all elements with key equivalent to `k`.

[cols=",",]
|===
|Returns: |The number of elements erased.

|Throws: |Only throws an exception if it is thrown by `hasher` or
`key++_++equal`.

|Notes: |The `template++<++class K++>++` overload only participates in
overload resolution if `Hash::is++_++transparent` and
`Pred::is++_++transparent` are valid member typedefs and neither
`iterator` nor `const++_++iterator` are implicitly convertible from `K`.
The library assumes that `Hash` is callable with both `K` and `Key` and
that `Pred` is transparent. This enables heterogeneous lookup which
avoids the cost of instantiating an instance of the `Key` type.
|===

'''''

[[unordered_node_map_erase_range]]
===== Erase Range

[source,highlight]
----
iterator erase(const_iterator first, const_iterator last);
----

Erases the elements in the range from `first` to `last`.

[cols=",",]
|===
|Returns: |The iterator following the erased elements - i.e. `last`.

|Throws: |Nothing in this implementation (neither the `hasher` nor the
`key++_++equal` objects are called).
|===

'''''

[[unordered_node_map_swap]]
===== swap

[source,highlight]
----
void swap(unordered_node_map& other)
  noexcept(boost::allocator_traits<Allocator>::is_always_equal::value ||
           boost::allocator_traits<Allocator>::propagate_on_container_swap::value);
----

Swaps the contents of the container with the parameter.

If `Allocator::propagate++_++on++_++container++_++swap` is declared and
`Allocator::propagate++_++on++_++container++_++swap::value` is `true`
then the containers' allocators are swapped. Otherwise, swapping with
unequal allocators results in undefined behavior.

[cols=",",]
|===
|Throws: |Nothing unless `key++_++equal` or `hasher` throw on swapping.
|===

'''''

[[unordered_node_map_extract_by_position]]
===== Extract by Position

[source,highlight]
----
node_type extract(const_iterator position);
----

Extracts the element pointed to by `position`.

[cols=",",]
|===
|Returns: |A `node++_++type` object holding the extracted element.
|Throws: |Nothing.
|===

'''''

[[unordered_node_map_extract_by_key]]
===== Extract by Key

[source,highlight]
----
node_type extract(const key_type& k);
template<class K> node_type extract(K&& k);
----

Extracts the element with key equivalent to `k`, if it exists.

[cols=",",]
|===
|Returns: |A `node++_++type` object holding the extracted element, or
empty if no element was extracted.

|Throws: |Only throws an exception if it is thrown by `hasher` or
`key++_++equal`.

|Notes: |The `template++<++class K++>++` overload only participates in
overload resolution if `Hash::is++_++transparent` and
`Pred::is++_++transparent` are valid member typedefs. The library
assumes that `Hash` is callable with both `K` and `Key` and that `Pred`
is transparent. This enables heterogeneous lookup which avoids the cost
of instantiating an instance of the `Key` type.
|===

'''''

[[unordered_node_map_pull]]
===== pull

[source,highlight]
----
init_type pull(const_iterator position);
----

Move-constructs an `init++_++value` `x` from the element pointed to by
`position`, erases the element and returns `x`.

'''''

[[unordered_node_map_clear]]
===== clear

[source,highlight]
----
void clear() noexcept;
----

Erases all elements in the container.

[cols=",",]
|===
|Postconditions: |`size() == 0`,
`max++_++load() ++>++= max++_++load++_++factor() ++*++ bucket++_++count()`
|===

'''''

[[unordered_node_map_merge]]
===== merge

[source,highlight]
----
template<class H2, class P2>
  void merge(unordered_node_map<Key, T, H2, P2, Allocator>& source);
template<class H2, class P2>
  void merge(unordered_node_map<Key, T, H2, P2, Allocator>&& source);
----

Transfers all the element nodes from `source` whose key is not already
present in `++*++this`.

[cols=",",]
|===
|Requires:
|`this-++>++get++_++allocator() == source.get++_++allocator()`.

|Notes: |Invalidates iterators to the elements transferred. If the
resulting size of `++*++this` is greater than its original maximum load,
invalidates all iterators associated to `++*++this`.
|===

'''''

[[unordered_node_map_observers]]
==== Observers

[[unordered_node_map_get_allocator]]
===== get++_++allocator

[source,highlight]
----
allocator_type get_allocator() const noexcept;
----

[cols=",",]
|===
|Returns: |The container’s allocator.
|===

'''''

[[unordered_node_map_hash_function]]
===== hash++_++function

[source,highlight]
----
hasher hash_function() const;
----

[cols=",",]
|===
|Returns: |The container’s hash function.
|===

'''''

[[unordered_node_map_key_eq]]
===== key++_++eq

[source,highlight]
----
key_equal key_eq() const;
----

[cols=",",]
|===
|Returns: |The container’s key equality predicate
|===

'''''

[[unordered_node_map_lookup]]
==== Lookup

[[unordered_node_map_find]]
===== find

[source,highlight]
----
iterator         find(const key_type& k);
const_iterator   find(const key_type& k) const;
template<class K>
  iterator       find(const K& k);
----

[cols=",",]
|===
|Returns: |An iterator pointing to an element with key equivalent to
`k`, or `end()` if no such element exists.

|Notes: |The `template++<++class K++>++` overloads only participate in
overload resolution if `Hash::is++_++transparent` and
`Pred::is++_++transparent` are valid member typedefs. The library
assumes that `Hash` is callable with both `K` and `Key` and that `Pred`
is transparent. This enables heterogeneous lookup which avoids the cost
of instantiating an instance of the `Key` type.
|===

'''''

[[unordered_node_map_count]]
===== count

[source,highlight]
----
size_type        count(const key_type& k) const;
template<class K>
  size_type      count(const K& k) const;
----

[cols=",",]
|===
|Returns: |The number of elements with key equivalent to `k`.

|Notes: |The `template++<++class K++>++` overload only participates in
overload resolution if `Hash::is++_++transparent` and
`Pred::is++_++transparent` are valid member typedefs. The library
assumes that `Hash` is callable with both `K` and `Key` and that `Pred`
is transparent. This enables heterogeneous lookup which avoids the cost
of instantiating an instance of the `Key` type.
|===

'''''

[[unordered_node_map_contains]]
===== contains

[source,highlight]
----
bool             contains(const key_type& k) const;
template<class K>
  bool           contains(const K& k) const;
----

[cols=",",]
|===
|Returns: |A boolean indicating whether or not there is an element with
key equal to `key` in the container

|Notes: |The `template++<++class K++>++` overload only participates in
overload resolution if `Hash::is++_++transparent` and
`Pred::is++_++transparent` are valid member typedefs. The library
assumes that `Hash` is callable with both `K` and `Key` and that `Pred`
is transparent. This enables heterogeneous lookup which avoids the cost
of instantiating an instance of the `Key` type.
|===

'''''

[[unordered_node_map_equal_range]]
===== equal++_++range

[source,highlight]
----
std::pair<iterator, iterator>               equal_range(const key_type& k);
std::pair<const_iterator, const_iterator>   equal_range(const key_type& k) const;
template<class K>
  std::pair<iterator, iterator>             equal_range(const K& k);
template<class K>
  std::pair<const_iterator, const_iterator> equal_range(const K& k) const;
----

[cols=",",]
|===
|Returns: |A range containing all elements with key equivalent to `k`.
If the container doesn’t contain any such elements, returns
`std::make++_++pair(b.end(), b.end())`.

|Notes: |The `template++<++class K++>++` overloads only participate in
overload resolution if `Hash::is++_++transparent` and
`Pred::is++_++transparent` are valid member typedefs. The library
assumes that `Hash` is callable with both `K` and `Key` and that `Pred`
is transparent. This enables heterogeneous lookup which avoids the cost
of instantiating an instance of the `Key` type.
|===

'''''

[[unordered_node_map_operator]]
===== operator++[]++

[source,highlight]
----
mapped_type& operator[](const key_type& k);
mapped_type& operator[](key_type&& k);
template<class K> mapped_type& operator[](K&& k);
----

[width="100%",cols="50%,50%",]
|===
|Effects: |If the container does not already contain an element with a
key equivalent to `k`, inserts the value
`std::pair++<++key++_++type const, mapped++_++type++>++(k, mapped++_++type())`.

|Returns: |A reference to `x.second` where `x` is the element already in
the container, or the newly inserted element with a key equivalent to
`k`.

|Throws: |If an exception is thrown by an operation other than a call to
`hasher` the function has no effect.

|Notes: a|
Can invalidate iterators, but only if the insert causes the load to be
greater than the maximum load. +

The `template++<++class K++>++` overload only participates in overload
resolution if `Hash::is++_++transparent` and `Pred::is++_++transparent`
are valid member typedefs. The library assumes that `Hash` is callable
with both `K` and `Key` and that `Pred` is transparent. This enables
heterogeneous lookup which avoids the cost of instantiating an instance
of the `Key` type.

|===

'''''

[[unordered_node_map_at]]
===== at

[source,highlight]
----
mapped_type& at(const key_type& k);
const mapped_type& at(const key_type& k) const;
template<class K> mapped_type& at(const K& k);
template<class K> const mapped_type& at(const K& k) const;
----

[cols=",",]
|===
|Returns: |A reference to `x.second` where `x` is the (unique) element
whose key is equivalent to `k`.

|Throws: |An exception object of type `std::out++_++of++_++range` if no
such element is present.

|Notes: |The `template++<++class K++>++` overloads only participate in
overload resolution if `Hash::is++_++transparent` and
`Pred::is++_++transparent` are valid member typedefs. The library
assumes that `Hash` is callable with both `K` and `Key` and that `Pred`
is transparent. This enables heterogeneous lookup which avoids the cost
of instantiating an instance of the `Key` type.
|===

'''''

[[unordered_node_map_bucket_interface]]
==== Bucket Interface

[[unordered_node_map_bucket_count]]
===== bucket++_++count

[source,highlight]
----
size_type bucket_count() const noexcept;
----

[cols=",",]
|===
|Returns: |The size of the bucket array.
|===

'''''

[[unordered_node_map_hash_policy]]
==== Hash Policy

[[unordered_node_map_load_factor]]
===== load++_++factor

[source,highlight]
----
float load_factor() const noexcept;
----

[cols=",",]
|===
|Returns:
|`static++_++cast++<++float++>++(size())/static++_++cast++<++float++>++(bucket++_++count())`,
or `0` if `bucket++_++count() == 0`.
|===

'''''

[[unordered_node_map_max_load_factor]]
===== max++_++load++_++factor

[source,highlight]
----
float max_load_factor() const noexcept;
----

[cols=",",]
|===
|Returns: |Returns the container’s maximum load factor.
|===

'''''

[[unordered_node_map_set_max_load_factor]]
===== Set max++_++load++_++factor

[source,highlight]
----
void max_load_factor(float z);
----

[cols=",",]
|===
|Effects: |Does nothing, as the user is not allowed to change this
parameter. Kept for compatibility with `boost::unordered++_++map`.
|===

'''''

[[unordered_node_map_max_load]]
===== max++_++load

[source,highlight]
----
size_type max_load() const noexcept;
----

[cols=",",]
|===
|Returns: |The maximum number of elements the container can hold without
rehashing, assuming that no further elements will be erased.

|Note: |After construction, rehash or clearance, the container’s maximum
load is at least `max++_++load++_++factor() ++*++ bucket++_++count()`.
This number may decrease on erasure under high-load conditions.
|===

'''''

[[unordered_node_map_rehash]]
===== rehash

[source,highlight]
----
void rehash(size_type n);
----

Changes if necessary the size of the bucket array so that there are at
least `n` buckets, and so that the load factor is less than or equal to
the maximum load factor. When applicable, this will either grow or
shrink the `bucket++_++count()` associated with the container.

When `size() == 0`, `rehash(0)` will deallocate the underlying buckets
array. If the provided Allocator uses fancy pointers, a default
allocation is subsequently performed.

Invalidates iterators and changes the order of elements.

[cols=",",]
|===
|Throws: |The function has no effect if an exception is thrown, unless
it is thrown by the container’s hash function or comparison function.
|===

'''''

[[unordered_node_map_reserve]]
===== reserve

[source,highlight]
----
void reserve(size_type n);
----

Equivalent to `a.rehash(ceil(n / a.max++_++load++_++factor()))`.

Similar to `rehash`, this function can be used to grow or shrink the
number of buckets in the container.

Invalidates iterators and changes the order of elements.

[cols=",",]
|===
|Throws: |The function has no effect if an exception is thrown, unless
it is thrown by the container’s hash function or comparison function.
|===

'''''

[[unordered_node_map_statistics]]
==== Statistics

[[unordered_node_map_get_stats]]
===== get++_++stats

[source,highlight]
----
stats get_stats() const;
----

[cols=",",]
|===
|Returns: |A statistical description of the insertion and lookup
operations performed by the container so far.

|Notes: |Only available if link:reference/stats.html#stats[statistics
calculation] is
link:#unordered_node_map_boost_unordered_enable_stats[enabled].
|===

'''''

[[unordered_node_map_reset_stats]]
===== reset++_++stats

[source,highlight]
----
void reset_stats() noexcept;
----

[cols=",",]
|===
|Effects: |Sets to zero the internal statistics kept by the container.

|Notes: |Only available if link:reference/stats.html#stats[statistics
calculation] is
link:#unordered_node_map_boost_unordered_enable_stats[enabled].
|===

'''''

[[unordered_node_map_deduction_guides]]
==== Deduction Guides

A deduction guide will not participate in overload resolution if any of
the following are true:

* It has an `InputIterator` template parameter and a type that does not
qualify as an input iterator is deduced for that parameter.
* It has an `Allocator` template parameter and a type that does not
qualify as an allocator is deduced for that parameter.
* It has a `Hash` template parameter and an integral type or a type that
qualifies as an allocator is deduced for that parameter.
* It has a `Pred` template parameter and a type that qualifies as an
allocator is deduced for that parameter.

A `size++_++­type` parameter type in a deduction guide refers to the
`size++_++­type` member type of the container type deduced by the
deduction guide. Its default value coincides with the default value of
the constructor selected.

[[unordered_node_map_iter_value_type]]
===== _iter-value-type_

....
template<class InputIterator>
  using iter-value-type =
    typename std::iterator_traits<InputIterator>::value_type; // exposition only
....

[[unordered_node_map_iter_key_type]]
===== _iter-key-type_

....
template<class InputIterator>
  using iter-key-type = std::remove_const_t<
    std::tuple_element_t<0, iter-value-type<InputIterator>>>; // exposition only
....

[[unordered_node_map_iter_mapped_type]]
===== _iter-mapped-type_

....
template<class InputIterator>
  using iter-mapped-type =
    std::tuple_element_t<1, iter-value-type<InputIterator>>;  // exposition only
....

[[unordered_node_map_iter_to_alloc_type]]
===== _iter-to-alloc-type_

....
template<class InputIterator>
  using iter-to-alloc-type = std::pair<
    std::add_const_t<std::tuple_element_t<0, iter-value-type<InputIterator>>>,
    std::tuple_element_t<1, iter-value-type<InputIterator>>>; // exposition only
....

[[unordered_node_map_equality_comparisons]]
==== Equality Comparisons

[[unordered_node_map_operator_2]]
===== operator==

[source,highlight]
----
template<class Key, class T, class Hash, class Pred, class Alloc>
  bool operator==(const unordered_node_map<Key, T, Hash, Pred, Alloc>& x,
                  const unordered_node_map<Key, T, Hash, Pred, Alloc>& y);
----

Return `true` if `x.size() == y.size()` and for every element in `x`,
there is an element in `y` with the same key, with an equal value (using
`operator==` to compare the value types).

[cols=",",]
|===
|Notes: |Behavior is undefined if the two containers don’t have
equivalent equality predicates.
|===

'''''

[[unordered_node_map_operator_3]]
===== operator!=

[source,highlight]
----
template<class Key, class T, class Hash, class Pred, class Alloc>
  bool operator!=(const unordered_node_map<Key, T, Hash, Pred, Alloc>& x,
                  const unordered_node_map<Key, T, Hash, Pred, Alloc>& y);
----

Return `false` if `x.size() == y.size()` and for every element in `x`,
there is an element in `y` with the same key, with an equal value (using
`operator==` to compare the value types).

[cols=",",]
|===
|Notes: |Behavior is undefined if the two containers don’t have
equivalent equality predicates.
|===

[[unordered_node_map_swap_2]]
==== Swap

[source,highlight]
----
template<class Key, class T, class Hash, class Pred, class Alloc>
  void swap(unordered_node_map<Key, T, Hash, Pred, Alloc>& x,
            unordered_node_map<Key, T, Hash, Pred, Alloc>& y)
    noexcept(noexcept(x.swap(y)));
----

Swaps the contents of `x` and `y`.

If `Allocator::propagate++_++on++_++container++_++swap` is declared and
`Allocator::propagate++_++on++_++container++_++swap::value` is `true`
then the containers' allocators are swapped. Otherwise, swapping with
unequal allocators results in undefined behavior.

[cols=",",]
|===
|Effects: |`x.swap(y)`
|Throws: |Nothing unless `key++_++equal` or `hasher` throw on swapping.
|===

'''''

[[unordered_node_map_erase_if]]
==== erase++_++if

[source,highlight]
----
template<class K, class T, class H, class P, class A, class Predicate>
  typename unordered_node_map<K, T, H, P, A>::size_type
    erase_if(unordered_node_map<K, T, H, P, A>& c, Predicate pred);
----

Traverses the container `c` and removes all elements for which the
supplied predicate returns `true`.

[width="100%",cols="50%,50%",]
|===
|Returns: |The number of erased elements.
|Notes: a|
Equivalent to: +

[source,highlight]
----
auto original_size = c.size();
for (auto i = c.begin(), last = c.end(); i != last; ) {
  if (pred(*i)) {
    i = c.erase(i);
  } else {
    ++i;
  }
}
return original_size - c.size();
----

Note that the references passed to `pred` are non-const.

|===

[[unordered_node_map_serialization]]
==== Serialization

`unordered++_++node++_++map`s can be archived/retrieved by means of
link:../../../../../serialization/index.html[Boost.Serialization] using
the API provided by this library. Both regular and XML archives are
supported.

[[unordered_node_map_saving_an_unordered_node_map_to_an_archive]]
===== Saving an unordered++_++node++_++map to an archive

Saves all the elements of an `unordered++_++node++_++map` `x` to an
archive (XML archive) `ar`.

[cols=",",]
|===
|Requires: |`std::remove++_++const++<++key++_++type++>++::type` and
`std::remove++_++const++<++mapped++_++type++>++::type` are serializable
(XML serializable), and they do support Boost.Serialization
`save++_++construct++_++data`/`load++_++construct++_++data` protocol
(automatically suported by
https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[DefaultConstructible]
types).
|===

'''''

[[unordered_node_map_loading_an_unordered_node_map_from_an_archive]]
===== Loading an unordered++_++node++_++map from an archive

Deletes all preexisting elements of an `unordered++_++node++_++map` `x`
and inserts from an archive (XML archive) `ar` restored copies of the
elements of the original `unordered++_++node++_++map` `other` saved to
the storage read by `ar`.

[cols=",",]
|===
|Requires: |`key++_++type` and `mapped++_++type` are constructible from
`std::remove++_++const++<++key++_++type++>++::type&&` and
`std::remove++_++const++<++mapped++_++type++>++::type&&`, respectively.
`x.key++_++equal()` is functionally equivalent to
`other.key++_++equal()`.
|===

'''''

[[unordered_node_map_saving_an_iteratorconst_iterator_to_an_archive]]
===== Saving an iterator/const++_++iterator to an archive

Saves the positional information of an `iterator` (`const++_++iterator`)
`it` to an archive (XML archive) `ar`. `it` can be and `end()` iterator.

[cols=",",]
|===
|Requires: |The `unordered++_++node++_++map` `x` pointed to by `it` has
been previously saved to `ar`, and no modifying operations have been
issued on `x` between saving of `x` and saving of `it`.
|===

'''''

[[unordered_node_map_loading_an_iteratorconst_iterator_from_an_archive]]
===== Loading an iterator/const++_++iterator from an archive

Makes an `iterator` (`const++_++iterator`) `it` point to the restored
position of the original `iterator` (`const++_++iterator`) saved to the
storage read by an archive (XML archive) `ar`.

[cols=",",]
|===
|Requires: |If `x` is the `unordered++_++node++_++map` `it` points to,
no modifying operations have been issued on `x` between loading of `x`
and loading of `it`.
|===

[[footer]]
[[footer-text]]
Last updated 2025-10-31 11:09:03 UTC
