[[header]]

[[content]]
[[unordered_set]]
== Class Template unordered_set

`boost::unordered_set` — An unordered associative container that stores
unique values.

[[unordered_set_synopsis]]
=== Synopsis

....
// #include <boost/unordered/unordered_set.hpp>

namespace boost {
namespace unordered {

  template<class Key,
           class Hash = boost::hash<Key>,
           class Pred = std::equal_to<Key>,
           class Allocator = std::allocator<Key>>
  class unordered_set {
  public:
    // types
    using key_type             = Key;
    using value_type           = Key;
    using hasher               = Hash;
    using key_equal            = Pred;
    using allocator_type       = Allocator;
    using pointer              = typename std::allocator_traits<Allocator>::pointer;
    using const_pointer        = typename std::allocator_traits<Allocator>::const_pointer;
    using reference            = value_type&;
    using const_reference      = const value_type&;
    using size_type            = std::size_t;
    using difference_type      = std::ptrdiff_t;

    using iterator             = implementation-defined;
    using const_iterator       = implementation-defined;
    using local_iterator       = implementation-defined;
    using const_local_iterator = implementation-defined;
    using node_type            = implementation-defined;
    using insert_return_type   = implementation-defined;

    // construct/copy/destroy
    unordered_set();
    explicit unordered_set(size_type n,
                           const hasher& hf = hasher(),
                           const key_equal& eql = key_equal(),
                           const allocator_type& a = allocator_type());
    template<class InputIterator>
      unordered_set(InputIterator f, InputIterator l,
                    size_type n = implementation-defined,
                    const hasher& hf = hasher(),
                    const key_equal& eql = key_equal(),
                    const allocator_type& a = allocator_type());
    unordered_set(const unordered_set& other);
    unordered_set(unordered_set&& other);
    template<class InputIterator>
      unordered_set(InputIterator f, InputIterator l, const allocator_type& a);
    explicit unordered_set(const Allocator& a);
    unordered_set(const unordered_set& other, const Allocator& a);
    unordered_set(unordered_set&& other, const Allocator& a);
    unordered_set(std::initializer_list<value_type> il,
                  size_type n = implementation-defined,
                  const hasher& hf = hasher(),
                  const key_equal& eql = key_equal(),
                  const allocator_type& a = allocator_type());
    unordered_set(size_type n, const allocator_type& a);
    unordered_set(size_type n, const hasher& hf, const allocator_type& a);
    template<class InputIterator>
      unordered_set(InputIterator f, InputIterator l, size_type n, const allocator_type& a);
    template<class InputIterator>
      unordered_set(InputIterator f, InputIterator l, size_type n, const hasher& hf,
                    const allocator_type& a);
    unordered_set(std::initializer_list<value_type> il, const allocator_type& a);
    unordered_set(std::initializer_list<value_type> il, size_type n, const allocator_type& a);
    unordered_set(std::initializer_list<value_type> il, size_type n, const hasher& hf,
                  const allocator_type& a);
    ~unordered_set();
    unordered_set& operator=(const unordered_set& other);
    unordered_set& operator=(unordered_set&& other)
      noexcept(boost::allocator_traits<Allocator>::is_always_equal::value &&
               boost::is_nothrow_move_assignable_v<Hash> &&
               boost::is_nothrow_move_assignable_v<Pred>);
    unordered_set& operator=(std::initializer_list<value_type> il);
    allocator_type get_allocator() const noexcept;

    // iterators
    iterator       begin() noexcept;
    const_iterator begin() const noexcept;
    iterator       end() noexcept;
    const_iterator end() const noexcept;
    const_iterator cbegin() const noexcept;
    const_iterator cend() const noexcept;

    // capacity
    [[nodiscard]] bool empty() const noexcept;
    size_type size() const noexcept;
    size_type max_size() const noexcept;

    // modifiers
    template<class... Args> std::pair<iterator, bool> emplace(Args&&... args);
    template<class... Args> iterator emplace_hint(const_iterator position, Args&&... args);
    std::pair<iterator, bool> insert(const value_type& obj);
    std::pair<iterator, bool> insert(value_type&& obj);
    template<class K> std::pair<iterator, bool> insert(K&& k);
    iterator insert(const_iterator hint, const value_type& obj);
    iterator insert(const_iterator hint, value_type&& obj);
    template<class K> iterator insert(const_iterator hint, K&& k);
    template<class InputIterator> void insert(InputIterator first, InputIterator last);
    void insert(std::initializer_list<value_type>);

    node_type extract(const_iterator position);
    node_type extract(const key_type& k);
    template<class K> node_type extract(K&& k);
    insert_return_type insert(node_type&& nh);
    iterator           insert(const_iterator hint, node_type&& nh);

    iterator  erase(iterator position);
    iterator  erase(const_iterator position);
    size_type erase(const key_type& k);
    template<class K> size_type erase(K&& k);
    iterator  erase(const_iterator first, const_iterator last);
    void      quick_erase(const_iterator position);
    void      erase_return_void(const_iterator position);
    void      swap(unordered_set& other)
      noexcept(boost::allocator_traits<Allocator>::is_always_equal::value &&
               boost::is_nothrow_swappable_v<Hash> &&
               boost::is_nothrow_swappable_v<Pred>);
    void      clear() noexcept;

    template<class H2, class P2>
      void merge(unordered_set<Key, H2, P2, Allocator>& source);
    template<class H2, class P2>
      void merge(unordered_set<Key, H2, P2, Allocator>&& source);
    template<class H2, class P2>
      void merge(unordered_multiset<Key, H2, P2, Allocator>& source);
    template<class H2, class P2>
      void merge(unordered_multiset<Key, H2, P2, Allocator>&& source);

    // observers
    hasher hash_function() const;
    key_equal key_eq() const;

    // set operations
    iterator         find(const key_type& k);
    const_iterator   find(const key_type& k) const;
    template<class K>
      iterator       find(const K& k);
    template<class K>
      const_iterator find(const K& k) const;
    template<typename CompatibleKey, typename CompatibleHash, typename CompatiblePredicate>
      iterator       find(CompatibleKey const& k, CompatibleHash const& hash,
                          CompatiblePredicate const& eq);
    template<typename CompatibleKey, typename CompatibleHash, typename CompatiblePredicate>
      const_iterator find(CompatibleKey const& k, CompatibleHash const& hash,
                          CompatiblePredicate const& eq) const;
    size_type        count(const key_type& k) const;
    template<class K>
      size_type      count(const K& k) const;
    bool             contains(const key_type& k) const;
    template<class K>
      bool           contains(const K& k) const;
    std::pair<iterator, iterator>               equal_range(const key_type& k);
    std::pair<const_iterator, const_iterator>   equal_range(const key_type& k) const;
    template<class K>
      std::pair<iterator, iterator>             equal_range(const K& k);
    template<class K>
      std::pair<const_iterator, const_iterator> equal_range(const K& k) const;

    // bucket interface
    size_type bucket_count() const noexcept;
    size_type max_bucket_count() const noexcept;
    size_type bucket_size(size_type n) const;
    size_type bucket(const key_type& k) const;
    template<class K> size_type bucket(const K& k) const;
    local_iterator begin(size_type n);
    const_local_iterator begin(size_type n) const;
    local_iterator end(size_type n);
    const_local_iterator end(size_type n) const;
    const_local_iterator cbegin(size_type n) const;
    const_local_iterator cend(size_type n) const;

    // hash policy
    float load_factor() const noexcept;
    float max_load_factor() const noexcept;
    void max_load_factor(float z);
    void rehash(size_type n);
    void reserve(size_type n);
  };

  // Deduction Guides
  template<class InputIterator,
           class Hash = boost::hash<iter-value-type<InputIterator>>,
           class Pred = std::equal_to<iter-value-type<InputIterator>>,
           class Allocator = std::allocator<iter-value-type<InputIterator>>>
    unordered_set(InputIterator, InputIterator, typename see below::size_type = see below,
                  Hash = Hash(), Pred = Pred(), Allocator = Allocator())
      -> unordered_set<iter-value-type<InputIterator>, Hash, Pred, Allocator>;

  template<class T, class Hash = boost::hash<T>, class Pred = std::equal_to<T>,
           class Allocator = std::allocator<T>>
    unordered_set(std::initializer_list<T>, typename see below::size_type = see below,
                  Hash = Hash(), Pred = Pred(), Allocator = Allocator())
      -> unordered_set<T, Hash, Pred, Allocator>;

  template<class InputIterator, class Allocator>
    unordered_set(InputIterator, InputIterator, typename see below::size_type, Allocator)
      -> unordered_set<iter-value-type<InputIterator>,
                       boost::hash<iter-value-type<InputIterator>>,
                       std::equal_to<iter-value-type<InputIterator>>, Allocator>;

  template<class InputIterator, class Allocator>
    unordered_set(InputIterator, InputIterator, Allocator)
      -> unordered_set<iter-value-type<InputIterator>,
                       boost::hash<iter-value-type<InputIterator>>,
                       std::equal_to<iter-value-type<InputIterator>>, Allocator>;

  template<class InputIterator, class Hash, class Allocator>
    unordered_set(InputIterator, InputIterator, typename see below::size_type, Hash, Allocator)
      -> unordered_set<iter-value-type<InputIterator>, Hash,
                       std::equal_to<iter-value-type<InputIterator>>, Allocator>;

  template<class T, class Allocator>
    unordered_set(std::initializer_list<T>, typename see below::size_type, Allocator)
      -> unordered_set<T, boost::hash<T>, std::equal_to<T>, Allocator>;

  template<class T, class Allocator>
    unordered_set(std::initializer_list<T>, Allocator)
      -> unordered_set<T, boost::hash<T>, std::equal_to<T>, Allocator>;

  template<class T, class Hash, class Allocator>
    unordered_set(std::initializer_list<T>, typename see below::size_type, Hash, Allocator)
      -> unordered_set<T, Hash, std::equal_to<T>, Allocator>;

} // namespace unordered
} // namespace boost
....

'''''

[[unordered_set_description]]
=== 描述

*Template Parameters*

[width="100%",cols="50%,50%",]
|===
|_Key_ |`Key` must be
https://en.cppreference.com/w/cpp/named_req/Erasable[Erasable] from the
container (i.e. `allocator_traits` can destroy it).

|_Hash_ |A unary function object type that acts a hash function for a
`Key`. It takes a single argument of type `Key` and returns a value of
type `std::size_t`.

|_Pred_ |A binary function object that implements an equivalence
relation on values of type `Key`. A binary function object that induces
an equivalence relation on values of type `Key`. It takes two arguments
of type `Key` and returns a value of type bool.

|_Allocator_ |An allocator whose value type is the same as the
container’s value type. Allocators using
https://en.cppreference.com/w/cpp/named_req/Allocator#Fancy_pointers[fancy
pointers] are supported.
|===

The elements are organized into buckets. Keys with the same hash code
are stored in the same bucket.

The number of buckets can be automatically increased by a call to
insert, or as the result of calling rehash.

[[unordered_set_configuration_macros]]
=== Configuration macros

[[unordered_set_boost_unordered_enable_serialization_compatibility_v0]]
==== `BOOST_UNORDERED_ENABLE_SERIALIZATION_COMPATIBILITY_V0`

Globally define this macro to support loading of `unordered_set`s saved
to a Boost.Serialization archive with a version of Boost prior to Boost
1.84.

[[unordered_set_typedefs]]
=== Typedefs

[source,highlight]
----
typedef implementation-defined iterator;
----

A constant iterator whose value type is `value_type`.

The iterator category is at least a forward iterator.

Convertible to `const_iterator`.

'''''

[source,highlight]
----
typedef implementation-defined const_iterator;
----

A constant iterator whose value type is `value_type`.

The iterator category is at least a forward iterator.

'''''

[source,highlight]
----
typedef implementation-defined local_iterator;
----

An iterator with the same value type, difference type and pointer and
reference type as iterator.

A `local_iterator` object can be used to iterate through a single
bucket.

'''''

[source,highlight]
----
typedef implementation-defined const_local_iterator;
----

A constant iterator with the same value type, difference type and
pointer and reference type as const_iterator.

A const_local_iterator object can be used to iterate through a single
bucket.

'''''

[source,highlight]
----
typedef implementation-defined node_type;
----

A class for holding extracted container elements, modelling
https://en.cppreference.com/w/cpp/container/node_handle[NodeHandle].

'''''

[source,highlight]
----
typedef implementation-defined insert_return_type;
----

A specialization of an internal class template:

[source,highlight]
----
template<class Iterator, class NodeType>
struct insert_return_type // name is exposition only
{
  Iterator position;
  bool     inserted;
  NodeType node;
};
----

with `Iterator` = `iterator` and `NodeType` = `node_type`.

'''''

[[unordered_set_constructors]]
=== Constructors

[[unordered_set_default_constructor]]
==== Default Constructor

[source,highlight]
----
unordered_set();
----

Constructs an empty container using `hasher()` as the hash function,
`key_equal()` as the key equality predicate, `allocator_type()` as the
allocator and a maximum load factor of `1.0`.

[cols=",",]
|===
|Postconditions: |`size() == 0`

|Requires: |If the defaults are used, `hasher`, `key_equal` and
`allocator_type` need to be
https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[DefaultConstructible].
|===

'''''

[[unordered_set_bucket_count_constructor]]
==== Bucket Count Constructor

[source,highlight]
----
explicit unordered_set(size_type n,
                       const hasher& hf = hasher(),
                       const key_equal& eql = key_equal(),
                       const allocator_type& a = allocator_type());
----

Constructs an empty container with at least `n` buckets, using `hf` as
the hash function, `eql` as the key equality predicate, `a` as the
allocator and a maximum load factor of `1.0`.

[cols=",",]
|===
|Postconditions: |`size() == 0`

|Requires: |If the defaults are used, `hasher`, `key_equal` and
`allocator_type` need to be
https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[DefaultConstructible].
|===

'''''

[[unordered_set_iterator_range_constructor]]
==== Iterator Range Constructor

[source,highlight]
----
template<class InputIterator>
  unordered_set(InputIterator f, InputIterator l,
                size_type n = implementation-defined,
                const hasher& hf = hasher(),
                const key_equal& eql = key_equal(),
                const allocator_type& a = allocator_type());
----

Constructs an empty container with at least `n` buckets, using `hf` as
the hash function, `eql` as the key equality predicate, `a` as the
allocator and a maximum load factor of `1.0` and inserts the elements
from `[f, l)` into it.

[cols=",",]
|===
|Requires: |If the defaults are used, `hasher`, `key_equal` and
`allocator_type` need to be
https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[DefaultConstructible].
|===

'''''

[[unordered_set_copy_constructor]]
==== Copy Constructor

[source,highlight]
----
unordered_set(const unordered_set& other);
----

The copy constructor. Copies the contained elements, hash function,
predicate, maximum load factor and allocator.

If `Allocator::select_on_container_copy_construction` exists and has the
right signature, the allocator will be constructed from its result.

[cols=",",]
|===
|Requires: |`value_type` is copy constructible
|===

'''''

[[unordered_set_move_constructor]]
==== Move Constructor

[source,highlight]
----
unordered_set(unordered_set&& other);
----

The move constructor.

[cols=",",]
|===
|Notes: |This is implemented using Boost.Move.
|Requires: |`value_type` is move-constructible.
|===

'''''

[[unordered_set_iterator_range_constructor_with_allocator]]
==== Iterator Range Constructor with Allocator

[source,highlight]
----
template<class InputIterator>
  unordered_set(InputIterator f, InputIterator l, const allocator_type& a);
----

Constructs an empty container using `a` as the allocator, with the
default hash function and key equality predicate and a maximum load
factor of `1.0` and inserts the elements from `[f, l)` into it.

[cols=",",]
|===
|Requires: |`hasher`, `key_equal` need to be
https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[DefaultConstructible].
|===

'''''

[[unordered_set_allocator_constructor]]
==== Allocator Constructor

[source,highlight]
----
explicit unordered_set(const Allocator& a);
----

Constructs an empty container, using allocator `a`.

'''''

[[unordered_set_copy_constructor_with_allocator]]
==== Copy Constructor with Allocator

[source,highlight]
----
unordered_set(const unordered_set& other, const Allocator& a);
----

Constructs an container, copying `other`'s contained elements, hash
function, predicate, maximum load factor, but using allocator `a`.

'''''

[[unordered_set_move_constructor_with_allocator]]
==== Move Constructor with Allocator

[source,highlight]
----
unordered_set(unordered_set&& other, const Allocator& a);
----

Construct a container moving `other`'s contained elements, and having
the hash function, predicate and maximum load factor, but using allocate
`a`.

[cols=",",]
|===
|Notes: |This is implemented using Boost.Move.
|Requires: |`value_type` is move insertable.
|===

'''''

[[unordered_set_initializer_list_constructor]]
==== Initializer List Constructor

[source,highlight]
----
unordered_set(std::initializer_list<value_type> il,
              size_type n = implementation-defined,
              const hasher& hf = hasher(),
              const key_equal& eql = key_equal(),
              const allocator_type& a = allocator_type());
----

Constructs an empty container with at least `n` buckets, using `hf` as
the hash function, `eql` as the key equality predicate, `a` as the
allocator and a maximum load factor of `1.0` and inserts the elements
from `il` into it.

[cols=",",]
|===
|Requires: |If the defaults are used, `hasher`, `key_equal` and
`allocator_type` need to be
https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[DefaultConstructible].
|===

'''''

[[unordered_set_bucket_count_constructor_with_allocator]]
==== Bucket Count Constructor with Allocator

[source,highlight]
----
unordered_set(size_type n, const allocator_type& a);
----

Constructs an empty container with at least `n` buckets, using `hf` as
the hash function, the default hash function and key equality predicate,
`a` as the allocator and a maximum load factor of `1.0`.

[cols=",",]
|===
|Postconditions: |`size() == 0`

|Requires: |`hasher` and `key_equal` need to be
https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[DefaultConstructible].
|===

'''''

[[unordered_set_bucket_count_constructor_with_hasher_and_allocator]]
==== Bucket Count Constructor with Hasher and Allocator

[source,highlight]
----
unordered_set(size_type n, const hasher& hf, const allocator_type& a);
----

Constructs an empty container with at least `n` buckets, using `hf` as
the hash function, the default key equality predicate, `a` as the
allocator and a maximum load factor of `1.0`.

[cols=",",]
|===
|Postconditions: |`size() == 0`

|Requires: |`key_equal` needs to be
https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[DefaultConstructible].
|===

'''''

[[unordered_set_iterator_range_constructor_with_bucket_count_and_allocator]]
==== Iterator Range Constructor with Bucket Count and Allocator

[source,highlight]
----
template<class InputIterator>
  unordered_set(InputIterator f, InputIterator l, size_type n, const allocator_type& a);
----

Constructs an empty container with at least `n` buckets, using `a` as
the allocator, with the default hash function and key equality predicate
and a maximum load factor of `1.0` and inserts the elements from
`[f, l)` into it.

[cols=",",]
|===
|Requires: |`hasher`, `key_equal` need to be
https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[DefaultConstructible].
|===

'''''

[[unordered_set_iterator_range_constructor_with_bucket_count_and_hasher]]
==== Iterator Range Constructor with Bucket Count and Hasher

[source,highlight]
----
template<class InputIterator>
  unordered_set(InputIterator f, InputIterator l, size_type n, const hasher& hf,
                const allocator_type& a);
----

Constructs an empty container with at least `n` buckets, using `hf` as
the hash function, `a` as the allocator, with the default key equality
predicate and a maximum load factor of `1.0` and inserts the elements
from `[f, l)` into it.

[cols=",",]
|===
|Requires: |`key_equal` needs to be
https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[DefaultConstructible].
|===

'''''

[[unordered_set_initializer_list_constructor_with_allocator]]
==== initializer_list Constructor with Allocator

[source,highlight]
----
unordered_set(std::initializer_list<value_type> il, const allocator_type& a);
----

Constructs an empty container using `a` as the allocator and a maximum
load factor of 1.0 and inserts the elements from `il` into it.

[cols=",",]
|===
|Requires: |`hasher` and `key_equal` need to be
https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[DefaultConstructible].
|===

'''''

[[unordered_set_initializer_list_constructor_with_bucket_count_and_allocator]]
==== initializer_list Constructor with Bucket Count and Allocator

[source,highlight]
----
unordered_set(std::initializer_list<value_type> il, size_type n, const allocator_type& a);
----

Constructs an empty container with at least `n` buckets, using `a` as
the allocator and a maximum load factor of 1.0 and inserts the elements
from `il` into it.

[cols=",",]
|===
|Requires: |`hasher` and `key_equal` need to be
https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[DefaultConstructible].
|===

'''''

[[unordered_set_initializer_list_constructor_with_bucket_count_and_hasher_and_allocator]]
==== initializer_list Constructor with Bucket Count and Hasher and Allocator

[source,highlight]
----
unordered_set(std::initializer_list<value_type> il, size_type n, const hasher& hf,
              const allocator_type& a);
----

Constructs an empty container with at least `n` buckets, using `hf` as
the hash function, `a` as the allocator and a maximum load factor of 1.0
and inserts the elements from `il` into it.

[cols=",",]
|===
|Requires: |`key_equal` needs to be
https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[DefaultConstructible].
|===

'''''

[[unordered_set_destructor]]
=== Destructor

[source,highlight]
----
~unordered_set();
----

[cols=",",]
|===
|Note: |The destructor is applied to every element, and all memory is
deallocated
|===

'''''

[[unordered_set_assignment]]
=== Assignment

[[unordered_set_copy_assignment]]
==== Copy Assignment

[source,highlight]
----
unordered_set& operator=(const unordered_set& other);
----

The assignment operator. Copies the contained elements, hash function,
predicate and maximum load factor but not the allocator.

If `Alloc::propagate_on_container_copy_assignment` exists and
`Alloc::propagate_on_container_copy_assignment::value` is `true`, the
allocator is overwritten, if not the copied elements are created using
the existing allocator.

[cols=",",]
|===
|Requires: |`value_type` is copy constructible
|===

'''''

[[unordered_set_move_assignment]]
==== Move Assignment

[source,highlight]
----
unordered_set& operator=(unordered_set&& other)
  noexcept(boost::allocator_traits<Allocator>::is_always_equal::value &&
           boost::is_nothrow_move_assignable_v<Hash> &&
           boost::is_nothrow_move_assignable_v<Pred>);
----

The move assignment operator.

If `Alloc::propagate_on_container_move_assignment` exists and
`Alloc::propagate_on_container_move_assignment::value` is `true`, the
allocator is overwritten, if not the moved elements are created using
the existing allocator.

[cols=",",]
|===
|Requires: |`value_type` is move constructible.
|===

'''''

[[unordered_set_initializer_list_assignment]]
==== Initializer List Assignment

[source,highlight]
----
unordered_set& operator=(std::initializer_list<value_type> il);
----

Assign from values in initializer list. All existing elements are either
overwritten by the new elements or destroyed.

[cols=",",]
|===
|Requires: |`value_type` is
https://en.cppreference.com/w/cpp/named_req/CopyInsertable[CopyInsertable]
into the container and
https://en.cppreference.com/w/cpp/named_req/CopyAssignable[CopyAssignable].
|===

'''''

[[unordered_set_iterators]]
=== Iterators

[[unordered_set_begin]]
==== begin

[source,highlight]
----
iterator       begin() noexcept;
const_iterator begin() const noexcept;
----

[cols=",",]
|===
|Returns: |An iterator referring to the first element of the container,
or if the container is empty the past-the-end value for the container.
|===

'''''

[[unordered_set_end]]
==== end

[source,highlight]
----
iterator       end() noexcept;
const_iterator end() const noexcept;
----

[cols=",",]
|===
|Returns: |An iterator which refers to the past-the-end value for the
container.
|===

'''''

[[unordered_set_cbegin]]
==== cbegin

[source,highlight]
----
const_iterator cbegin() const noexcept;
----

[cols=",",]
|===
|Returns: |A `const_iterator` referring to the first element of the
container, or if the container is empty the past-the-end value for the
container.
|===

'''''

[[unordered_set_cend]]
==== cend

[source,highlight]
----
const_iterator cend() const noexcept;
----

[cols=",",]
|===
|Returns: |A `const_iterator` which refers to the past-the-end value for
the container.
|===

'''''

[[unordered_set_size_and_capacity]]
=== Size and Capacity

[[unordered_set_empty]]
==== empty

[source,highlight]
----
[[nodiscard]] bool empty() const noexcept;
----

[cols=",",]
|===
|Returns: |`size() == 0`
|===

'''''

[[unordered_set_size]]
==== size

[source,highlight]
----
size_type size() const noexcept;
----

[cols=",",]
|===
|Returns: |`std::distance(begin(), end())`
|===

'''''

[[unordered_set_max_size]]
==== max_size

[source,highlight]
----
size_type max_size() const noexcept;
----

[cols=",",]
|===
|Returns: |`size()` of the largest possible container.
|===

'''''

[[unordered_set_modifiers]]
=== Modifiers

[[unordered_set_emplace]]
==== emplace

[source,highlight]
----
template<class... Args> std::pair<iterator, bool> emplace(Args&&... args);
----

Inserts an object, constructed with the arguments `args`, in the
container if and only if there is no element in the container with an
equivalent value.

[width="100%",cols="50%,50%",]
|===
|Requires: |`value_type` is
https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[EmplaceConstructible]
into `X` from `args`.

|Returns: a|
The bool component of the return type is true if an insert took place. +

If an insert took place, then the iterator points to the newly inserted
element. Otherwise, it points to the element with equivalent value.

|Throws: |If an exception is thrown by an operation other than a call to
`hasher` the function has no effect.

|Notes: a|
Can invalidate iterators, but only if the insert causes the load factor
to be greater to or equal to the maximum load factor. +

Pointers and references to elements are never invalidated.

|===

'''''

[[unordered_set_emplace_hint]]
==== emplace_hint

[source,highlight]
----
template<class... Args> iterator emplace_hint(const_iterator position, Args&&... args);
----

Inserts an object, constructed with the arguments `args`, in the
container if and only if there is no element in the container with an
equivalent value.

`position` is a suggestion to where the element should be inserted.

[width="100%",cols="50%,50%",]
|===
|Requires: |`value_type` is
https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[EmplaceConstructible]
into `X` from `args`.

|Returns: |If an insert took place, then the iterator points to the
newly inserted element. Otherwise, it points to the element with
equivalent key.

|Throws: |If an exception is thrown by an operation other than a call to
`hasher` the function has no effect.

|Notes: a|
The standard is fairly vague on the meaning of the hint. But the only
practical way to use it, and the only way that Boost.Unordered supports
is to point to an existing element with the same key. +

Can invalidate iterators, but only if the insert causes the load factor
to be greater to or equal to the maximum load factor. +

Pointers and references to elements are never invalidated.

|===

'''''

[[unordered_set_copy_insert]]
==== Copy Insert

[source,highlight]
----
std::pair<iterator, bool> insert(const value_type& obj);
----

Inserts `obj` in the container if and only if there is no element in the
container with an equivalent key.

[width="100%",cols="50%,50%",]
|===
|Requires: |`value_type` is
https://en.cppreference.com/w/cpp/named_req/CopyInsertable[CopyInsertable].

|Returns: a|
The bool component of the return type is true if an insert took place. +

If an insert took place, then the iterator points to the newly inserted
element. Otherwise, it points to the element with equivalent key.

|Throws: |If an exception is thrown by an operation other than a call to
`hasher` the function has no effect.

|Notes: a|
Can invalidate iterators, but only if the insert causes the load factor
to be greater to or equal to the maximum load factor. +

Pointers and references to elements are never invalidated.

|===

'''''

[[unordered_set_move_insert]]
==== Move Insert

[source,highlight]
----
std::pair<iterator, bool> insert(value_type&& obj);
----

Inserts `obj` in the container if and only if there is no element in the
container with an equivalent key.

[width="100%",cols="50%,50%",]
|===
|Requires: |`value_type` is
https://en.cppreference.com/w/cpp/named_req/MoveInsertable[MoveInsertable].

|Returns: a|
The bool component of the return type is true if an insert took place. +

If an insert took place, then the iterator points to the newly inserted
element. Otherwise, it points to the element with equivalent key.

|Throws: |If an exception is thrown by an operation other than a call to
`hasher` the function has no effect.

|Notes: a|
Can invalidate iterators, but only if the insert causes the load factor
to be greater to or equal to the maximum load factor. +

Pointers and references to elements are never invalidated.

|===

'''''

[[unordered_set_transparent_insert]]
==== Transparent Insert

[source,highlight]
----
template<class K> std::pair<iterator, bool> insert(K&& k);
----

Inserts an element constructed from `std::forward<K>(k)` in the
container if and only if there is no element in the container with an
equivalent key.

[width="100%",cols="50%,50%",]
|===
|Requires: |`value_type` is
https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[EmplaceConstructible]
from `k`.

|Returns: a|
The bool component of the return type is true if an insert took place. +

If an insert took place, then the iterator points to the newly inserted
element. Otherwise, it points to the element with equivalent key.

|Throws: |If an exception is thrown by an operation other than a call to
`hasher` the function has no effect.

|Notes: a|
Can invalidate iterators, but only if the insert causes the load factor
to be greater to or equal to the maximum load factor. +

Pointers and references to elements are never invalidated. +

This overload only participates in overload resolution if
`Hash::is_transparent` and `Pred::is_transparent` are valid member
typedefs and neither `iterator` nor `const_iterator` are implicitly
convertible from `K`. The library assumes that `Hash` is callable with
both `K` and `Key` and that `Pred` is transparent. This enables
heterogeneous lookup which avoids the cost of instantiating an instance
of the `Key` type.

|===

'''''

[[unordered_set_copy_insert_with_hint]]
==== Copy Insert with Hint

[source,highlight]
----
iterator insert(const_iterator hint, const value_type& obj);
----

Inserts `obj` in the container if and only if there is no element in the
container with an equivalent key.

`hint` is a suggestion to where the element should be inserted.

[width="100%",cols="50%,50%",]
|===
|Requires: |`value_type` is
https://en.cppreference.com/w/cpp/named_req/CopyInsertable[CopyInsertable].

|Returns: |If an insert took place, then the iterator points to the
newly inserted element. Otherwise, it points to the element with
equivalent key.

|Throws: |If an exception is thrown by an operation other than a call to
`hasher` the function has no effect.

|Notes: a|
The standard is fairly vague on the meaning of the hint. But the only
practical way to use it, and the only way that Boost.Unordered supports
is to point to an existing element with the same key. +

Can invalidate iterators, but only if the insert causes the load factor
to be greater to or equal to the maximum load factor. +

Pointers and references to elements are never invalidated.

|===

'''''

[[unordered_set_move_insert_with_hint]]
==== Move Insert with Hint

[source,highlight]
----
iterator insert(const_iterator hint, value_type&& obj);
----

Inserts `obj` in the container if and only if there is no element in the
container with an equivalent key.

`hint` is a suggestion to where the element should be inserted.

[width="100%",cols="50%,50%",]
|===
|Requires: |`value_type` is
https://en.cppreference.com/w/cpp/named_req/MoveInsertable[MoveInsertable].

|Returns: |If an insert took place, then the iterator points to the
newly inserted element. Otherwise, it points to the element with
equivalent key.

|Throws: |If an exception is thrown by an operation other than a call to
`hasher` the function has no effect.

|Notes: a|
The standard is fairly vague on the meaning of the hint. But the only
practical way to use it, and the only way that Boost.Unordered supports
is to point to an existing element with the same key. +

Can invalidate iterators, but only if the insert causes the load factor
to be greater to or equal to the maximum load factor. +

Pointers and references to elements are never invalidated.

|===

'''''

[[unordered_set_transparent_insert_with_hint]]
==== Transparent Insert with Hint

[source,highlight]
----
template<class K> iterator insert(const_iterator hint, K&& k);
----

Inserts an element constructed from `std::forward<K>(k)` in the
container if and only if there is no element in the container with an
equivalent key.

`hint` is a suggestion to where the element should be inserted.

[width="100%",cols="50%,50%",]
|===
|Requires: |`value_type` is
https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[EmplaceConstructible]
from `k`.

|Returns: |If an insert took place, then the iterator points to the
newly inserted element. Otherwise, it points to the element with
equivalent key.

|Throws: |If an exception is thrown by an operation other than a call to
`hasher` the function has no effect.

|Notes: a|
The standard is fairly vague on the meaning of the hint. But the only
practical way to use it, and the only way that Boost.Unordered supports
is to point to an existing element with the same key. +

Can invalidate iterators, but only if the insert causes the load factor
to be greater to or equal to the maximum load factor. +

Pointers and references to elements are never invalidated. +

This overload only participates in overload resolution if
`Hash::is_transparent` and `Pred::is_transparent` are valid member
typedefs and neither `iterator` nor `const_iterator` are implicitly
convertible from `K`. The library assumes that `Hash` is callable with
both `K` and `Key` and that `Pred` is transparent. This enables
heterogeneous lookup which avoids the cost of instantiating an instance
of the `Key` type.

|===

'''''

[[unordered_set_insert_iterator_range]]
==== Insert Iterator Range

[source,highlight]
----
template<class InputIterator> void insert(InputIterator first, InputIterator last);
----

Inserts a range of elements into the container. Elements are inserted if
and only if there is no element in the container with an equivalent key.

[width="100%",cols="50%,50%",]
|===
|Requires: |`value_type` is
https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[EmplaceConstructible]
into `X` from `*first`.

|Throws: |When inserting a single element, if an exception is thrown by
an operation other than a call to `hasher` the function has no effect.

|Notes: a|
Can invalidate iterators, but only if the insert causes the load factor
to be greater to or equal to the maximum load factor. +

Pointers and references to elements are never invalidated.

|===

'''''

[[unordered_set_insert_initializer_list]]
==== Insert Initializer List

[source,highlight]
----
void insert(std::initializer_list<value_type>);
----

Inserts a range of elements into the container. Elements are inserted if
and only if there is no element in the container with an equivalent key.

[width="100%",cols="50%,50%",]
|===
|Requires: |`value_type` is
https://en.cppreference.com/w/cpp/named_req/CopyInsertable[CopyInsertable]
into the container.

|Throws: |When inserting a single element, if an exception is thrown by
an operation other than a call to `hasher` the function has no effect.

|Notes: a|
Can invalidate iterators, but only if the insert causes the load factor
to be greater to or equal to the maximum load factor. +

Pointers and references to elements are never invalidated.

|===

'''''

[[unordered_set_extract_by_iterator]]
==== Extract by Iterator

[source,highlight]
----
node_type extract(const_iterator position);
----

Removes the element pointed to by `position`.

[cols=",",]
|===
|Returns: |A `node_type` owning the element.

|Notes: |In C++17 a node extracted using this method can be inserted
into a compatible `unordered_multiset`, but that is not supported yet.
|===

'''''

[[unordered_set_extract_by_value]]
==== Extract by Value

[source,highlight]
----
node_type extract(const key_type& k);
template<class K> node_type extract(K&& k);
----

Removes an element with key equivalent to `k`.

[width="100%",cols="50%,50%",]
|===
|Returns: |A `node_type` owning the element if found, otherwise an empty
`node_type`.

|Throws: |Only throws an exception if it is thrown by `hasher` or
`key_equal`.

|Notes: a|
In C++17 a node extracted using this method can be inserted into a
compatible `unordered_multiset`, but that is not supported yet. +

The `template<class K>` overload only participates in overload
resolution if `Hash::is_transparent` and `Pred::is_transparent` are
valid member typedefs and neither `iterator` nor `const_iterator` are
implicitly convertible from `K`. The library assumes that `Hash` is
callable with both `K` and `Key` and that `Pred` is transparent. This
enables heterogeneous lookup which avoids the cost of instantiating an
instance of the `Key` type.

|===

'''''

[[unordered_set_insert_with_node_handle]]
==== Insert with `node_handle`

[source,highlight]
----
insert_return_type insert(node_type&& nh);
----

If `nh` is empty, has no effect.

Otherwise inserts the element owned by `nh` if and only if there is no
element in the container with an equivalent key.

[width="100%",cols="50%,50%",]
|===
|Requires: |`nh` is empty or `nh.get_allocator()` is equal to the
container’s allocator.

|Returns: a|
If `nh` was empty, returns an `insert_return_type` with: `inserted`
equal to `false`, `position` equal to `end()` and `node` empty. +

Otherwise if there was already an element with an equivalent key,
returns an `insert_return_type` with: `inserted` equal to `false`,
`position` pointing to a matching element and `node` contains the node
from `nh`. +

Otherwise if the insertion succeeded, returns an `insert_return_type`
with: `inserted` equal to `true`, `position` pointing to the newly
inserted element and `node` empty.

|Throws: |If an exception is thrown by an operation other than a call to
`hasher` the function has no effect.

|Notes: a|
Can invalidate iterators, but only if the insert causes the load factor
to be greater to or equal to the maximum load factor. +

Pointers and references to elements are never invalidated. +

In C++17 this can be used to insert a node extracted from a compatible
`unordered_multiset`, but that is not supported yet.

|===

'''''

[[unordered_set_insert_with_hint_and_node_handle]]
==== Insert with Hint and `node_handle`

[source,highlight]
----
iterator insert(const_iterator hint, node_type&& nh);
----

If `nh` is empty, has no effect.

Otherwise inserts the element owned by `nh` if and only if there is no
element in the container with an equivalent key.

If there is already an element in the container with an equivalent key
has no effect on `nh` (i.e. `nh` still contains the node.)

`hint` is a suggestion to where the element should be inserted.

[width="100%",cols="50%,50%",]
|===
|Requires: |`nh` is empty or `nh.get_allocator()` is equal to the
container’s allocator.

|Returns: a|
If `nh` was empty returns `end()`. +

If there was already an element in the container with an equivalent key
returns an iterator pointing to that. +

Otherwise returns an iterator pointing to the newly inserted element.

|Throws: |If an exception is thrown by an operation other than a call to
`hasher` the function has no effect.

|Notes: a|
The standard is fairly vague on the meaning of the hint. But the only
practical way to use it, and the only way that Boost.Unordered supports
is to point to an existing element with the same key. +

Can invalidate iterators, but only if the insert causes the load factor
to be greater to or equal to the maximum load factor. +

Pointers and references to elements are never invalidated. +

This can be used to insert a node extracted from a compatible
`unordered_multiset`.

|===

'''''

[[unordered_set_erase_by_position]]
==== Erase by Position

[source,highlight]
----
iterator erase(iterator position);
iterator erase(const_iterator position);
----

Erase the element pointed to by `position`.

[cols=",",]
|===
|Returns: |The iterator following `position` before the erasure.

|Throws: |Only throws an exception if it is thrown by `hasher` or
`key_equal`.

|Notes: |In older versions this could be inefficient because it had to
search through several buckets to find the position of the returned
iterator. The data structure has been changed so that this is no longer
the case, and the alternative erase methods have been deprecated.
|===

'''''

[[unordered_set_erase_by_value]]
==== Erase by Value

[source,highlight]
----
size_type erase(const key_type& k);
template<class K> size_type erase(K&& k);
----

Erase all elements with key equivalent to `k`.

[cols=",",]
|===
|Returns: |The number of elements erased.

|Throws: |Only throws an exception if it is thrown by `hasher` or
`key_equal`.

|Notes: |The `template<class K>` overload only participates in overload
resolution if `Hash::is_transparent` and `Pred::is_transparent` are
valid member typedefs and neither `iterator` nor `const_iterator` are
implicitly convertible from `K`. The library assumes that `Hash` is
callable with both `K` and `Key` and that `Pred` is transparent. This
enables heterogeneous lookup which avoids the cost of instantiating an
instance of the `Key` type.
|===

'''''

[[unordered_set_erase_range]]
==== Erase Range

[source,highlight]
----
iterator erase(const_iterator first, const_iterator last);
----

Erases the elements in the range from `first` to `last`.

[width="100%",cols="50%,50%",]
|===
|Returns: |The iterator following the erased elements - i.e. `last`.

|Throws: a|
Only throws an exception if it is thrown by `hasher` or `key_equal`. +

In this implementation, this overload doesn’t call either function
object’s methods so it is no throw, but this might not be true in other
implementations.

|===

'''''

[[unordered_set_quick_erase]]
==== quick_erase

[source,highlight]
----
void quick_erase(const_iterator position);
----

Erase the element pointed to by `position`.

[width="100%",cols="50%,50%",]
|===
|Throws: a|
Only throws an exception if it is thrown by `hasher` or `key_equal`. +

In this implementation, this overload doesn’t call either function
object’s methods so it is no throw, but this might not be true in other
implementations.

|Notes: |This method was implemented because returning an iterator to
the next element from erase was expensive, but the container has been
redesigned so that is no longer the case. So this method is now
deprecated.
|===

'''''

[[unordered_set_erase_return_void]]
==== erase_return_void

[source,highlight]
----
void erase_return_void(const_iterator position);
----

Erase the element pointed to by `position`.

[width="100%",cols="50%,50%",]
|===
|Throws: a|
Only throws an exception if it is thrown by `hasher` or `key_equal`. +

In this implementation, this overload doesn’t call either function
object’s methods so it is no throw, but this might not be true in other
implementations.

|Notes: |This method was implemented because returning an iterator to
the next element from erase was expensive, but the container has been
redesigned so that is no longer the case. So this method is now
deprecated.
|===

'''''

[[unordered_set_swap]]
==== swap

[source,highlight]
----
void swap(unordered_set& other)
  noexcept(boost::allocator_traits<Allocator>::is_always_equal::value &&
           boost::is_nothrow_swappable_v<Hash> &&
           boost::is_nothrow_swappable_v<Pred>);
----

Swaps the contents of the container with the parameter.

If `Allocator::propagate_on_container_swap` is declared and
`Allocator::propagate_on_container_swap::value` is `true` then the
containers' allocators are swapped. Otherwise, swapping with unequal
allocators results in undefined behavior.

[cols=",",]
|===
|Throws: |Doesn’t throw an exception unless it is thrown by the copy
constructor or copy assignment operator of `key_equal` or `hasher`.

|Notes: |The exception specifications aren’t quite the same as the C++11
standard, as the equality predicate and hash function are swapped using
their copy constructors.
|===

'''''

[[unordered_set_clear]]
==== clear

[source,highlight]
----
void clear() noexcept;
----

Erases all elements in the container.

[cols=",",]
|===
|Postconditions: |`size() == 0`
|Throws: |Never throws an exception.
|===

'''''

[[unordered_set_merge]]
==== merge

[source,highlight]
----
template<class H2, class P2>
  void merge(unordered_set<Key, H2, P2, Allocator>& source);
template<class H2, class P2>
  void merge(unordered_set<Key, H2, P2, Allocator>&& source);
template<class H2, class P2>
  void merge(unordered_multiset<Key, H2, P2, Allocator>& source);
template<class H2, class P2>
  void merge(unordered_multiset<Key, H2, P2, Allocator>&& source);
----

Attempt to "merge" two containers by iterating `source` and extracting
any node in `source` that is not contained in `*this` and then inserting
it into `*this`.

Because `source` can have a different hash function and key equality
predicate, the key of each node in `source` is rehashed using
`this->hash_function()` and then, if required, compared using
`this->key_eq()`.

The behavior of this function is undefined if
`this->get_allocator() != source.get_allocator()`.

This function does not copy or move any elements and instead simply
relocates the nodes from `source` into `*this`.

[width="100%",cols="50%,50%",]
|===
|Notes: a|
* Pointers and references to transferred elements remain valid.
* Invalidates iterators to transferred elements.
* Invalidates iterators belonging to `*this`.
* Iterators to non-transferred elements in `source` remain valid.

|===

'''''

[[unordered_set_observers]]
=== Observers

[[unordered_set_get_allocator]]
==== get_allocator

[source,highlight]
----
allocator_type get_allocator() const;
----

'''''

[[unordered_set_hash_function]]
==== hash_function

[source,highlight]
----
hasher hash_function() const;
----

[cols=",",]
|===
|Returns: |The container’s hash function.
|===

'''''

[[unordered_set_key_eq]]
==== key_eq

[source,highlight]
----
key_equal key_eq() const;
----

[cols=",",]
|===
|Returns: |The container’s key equality predicate
|===

'''''

[[unordered_set_lookup]]
=== Lookup

[[unordered_set_find]]
==== find

[source,highlight]
----
iterator         find(const key_type& k);
const_iterator   find(const key_type& k) const;
template<class K>
  iterator       find(const K& k);
template<class K>
  const_iterator find(const K& k) const;
template<typename CompatibleKey, typename CompatibleHash, typename CompatiblePredicate>
  iterator       find(CompatibleKey const& k, CompatibleHash const& hash,
                      CompatiblePredicate const& eq);
template<typename CompatibleKey, typename CompatibleHash, typename CompatiblePredicate>
  const_iterator find(CompatibleKey const& k, CompatibleHash const& hash,
                      CompatiblePredicate const& eq) const;
----

[width="100%",cols="50%,50%",]
|===
|Returns: |An iterator pointing to an element with key equivalent to
`k`, or `b.end()` if no such element exists.

|Notes: a|
The templated overloads containing `CompatibleKey`, `CompatibleHash` and
`CompatiblePredicate` are non-standard extensions which allow you to use
a compatible hash function and equality predicate for a key of a
different type in order to avoid an expensive type cast. In general, its
use is not encouraged and instead the `K` member function templates
should be used. +

The `template<class K>` overloads only participate in overload
resolution if `Hash::is_transparent` and `Pred::is_transparent` are
valid member typedefs. The library assumes that `Hash` is callable with
both `K` and `Key` and that `Pred` is transparent. This enables
heterogeneous lookup which avoids the cost of instantiating an instance
of the `Key` type.

|===

'''''

[[unordered_set_count]]
==== count

[source,highlight]
----
size_type        count(const key_type& k) const;
template<class K>
  size_type      count(const K& k) const;
----

[cols=",",]
|===
|Returns: |The number of elements with key equivalent to `k`.

|Notes: |The `template<class K>` overload only participates in overload
resolution if `Hash::is_transparent` and `Pred::is_transparent` are
valid member typedefs. The library assumes that `Hash` is callable with
both `K` and `Key` and that `Pred` is transparent. This enables
heterogeneous lookup which avoids the cost of instantiating an instance
of the `Key` type.
|===

'''''

[[unordered_set_contains]]
==== contains

[source,highlight]
----
bool             contains(const key_type& k) const;
template<class K>
  bool           contains(const K& k) const;
----

[cols=",",]
|===
|Returns: |A boolean indicating whether or not there is an element with
key equal to `key` in the container

|Notes: |The `template<class K>` overload only participates in overload
resolution if `Hash::is_transparent` and `Pred::is_transparent` are
valid member typedefs. The library assumes that `Hash` is callable with
both `K` and `Key` and that `Pred` is transparent. This enables
heterogeneous lookup which avoids the cost of instantiating an instance
of the `Key` type.
|===

'''''

[[unordered_set_equal_range]]
==== equal_range

[source,highlight]
----
std::pair<iterator, iterator>               equal_range(const key_type& k);
std::pair<const_iterator, const_iterator>   equal_range(const key_type& k) const;
template<class K>
  std::pair<iterator, iterator>             equal_range(const K& k);
template<class K>
  std::pair<const_iterator, const_iterator> equal_range(const K& k) const;
----

[cols=",",]
|===
|Returns: |A range containing all elements with key equivalent to `k`.
If the container doesn’t contain any such elements, returns
`std::make_pair(b.end(), b.end())`.

|Notes: |The `template<class K>` overloads only participate in overload
resolution if `Hash::is_transparent` and `Pred::is_transparent` are
valid member typedefs. The library assumes that `Hash` is callable with
both `K` and `Key` and that `Pred` is transparent. This enables
heterogeneous lookup which avoids the cost of instantiating an instance
of the `Key` type.
|===

'''''

[[unordered_set_bucket_interface]]
=== Bucket Interface

[[unordered_set_bucket_count]]
==== bucket_count

[source,highlight]
----
size_type bucket_count() const noexcept;
----

[cols=",",]
|===
|Returns: |桶的数量。
|===

'''''

[[unordered_set_max_bucket_count]]
==== max_bucket_count

[source,highlight]
----
size_type max_bucket_count() const noexcept;
----

[cols=",",]
|===
|Returns: |桶数量的上限值。
|===

'''''

[[unordered_set_bucket_size]]
==== bucket_size

[source,highlight]
----
size_type bucket_size(size_type n) const;
----

[cols=",",]
|===
|Requires: |`n < bucket_count()`
|Returns: |编号为`n`的桶中的元素数量。
|===

'''''

[[unordered_set_bucket]]
==== bucket

[source,highlight]
----
size_type bucket(const key_type& k) const;
template<class K> size_type bucket(const K& k) const;
----

[cols=",",]
|===
|Returns: |The index of the bucket which would contain an element with
key `k`.

|Postconditions: |The return value is less than `bucket_count()`.

|Notes: |The `template<class K>` overload only participates in overload
resolution if `Hash::is_transparent` and `Pred::is_transparent` are
valid member typedefs. The library assumes that `Hash` is callable with
both `K` and `Key` and that `Pred` is transparent. This enables
heterogeneous lookup which avoids the cost of instantiating an instance
of the `Key` type.
|===

'''''

[[unordered_set_begin_2]]
==== begin

[source,highlight]
----
local_iterator begin(size_type n);
const_local_iterator begin(size_type n) const;
----

[cols=",",]
|===
|Requires: |`n` shall be in the range `[0, bucket_count())`.

|Returns: |A local iterator pointing the first element in the bucket
with index `n`.
|===

'''''

[[unordered_set_end_2]]
==== end

[source,highlight]
----
local_iterator end(size_type n);
const_local_iterator end(size_type n) const;
----

[cols=",",]
|===
|Requires: |`n` shall be in the range `[0, bucket_count())`.

|Returns: |A local iterator pointing the 'one past the end' element in
the bucket with index `n`.
|===

'''''

[[unordered_set_cbegin_2]]
==== cbegin

[source,highlight]
----
const_local_iterator cbegin(size_type n) const;
----

[cols=",",]
|===
|Requires: |`n` shall be in the range `[0, bucket_count())`.

|Returns: |A constant local iterator pointing the first element in the
bucket with index `n`.
|===

'''''

[[unordered_set_cend_2]]
==== cend

[source,highlight]
----
const_local_iterator cend(size_type n) const;
----

[cols=",",]
|===
|Requires: |`n` shall be in the range `[0, bucket_count())`.

|Returns: |A constant local iterator pointing the 'one past the end'
element in the bucket with index `n`.
|===

'''''

[[unordered_set_hash_policy]]
=== Hash Policy

[[unordered_set_load_factor]]
==== load_factor

[source,highlight]
----
float load_factor() const noexcept;
----

[cols=",",]
|===
|Returns: |每个桶的平均元素数量。
|===

'''''

[[unordered_set_max_load_factor]]
==== max_load_factor

[source,highlight]
----
float max_load_factor() const noexcept;
----

[cols=",",]
|===
|Returns: |返回当前最大负载因子。
|===

'''''

[[unordered_set_set_max_load_factor]]
==== Set max_load_factor

[source,highlight]
----
void max_load_factor(float z);
----

[cols=",",]
|===
|Effects: |Changes the container’s maximum load factor, using `z` as a
hint.
|===

'''''

[[unordered_set_rehash]]
==== rehash

[source,highlight]
----
void rehash(size_type n);
----

Changes the number of buckets so that there are at least `n` buckets,
and so that the load factor is less than or equal to the maximum load
factor. When applicable, this will either grow or shrink the
`bucket_count()` associated with the container.

When `size() == 0`, `rehash(0)` will deallocate the underlying buckets
array.

Invalidates iterators, and changes the order of elements. Pointers and
references to elements are not invalidated.

[cols=",",]
|===
|Throws: |The function has no effect if an exception is thrown, unless
it is thrown by the container’s hash function or comparison function.
|===

'''''

[[unordered_set_reserve]]
==== reserve

[source,highlight]
----
void reserve(size_type n);
----

Equivalent to `a.rehash(ceil(n / a.max_load_factor()))`, or
`a.rehash(1)` if `n > 0` and
`a.max_load_factor() == std::numeric_limits<float>::infinity()`.

Similar to `rehash`, this function can be used to grow or shrink the
number of buckets in the container.

Invalidates iterators, and changes the order of elements. Pointers and
references to elements are not invalidated.

[cols=",",]
|===
|Throws: |The function has no effect if an exception is thrown, unless
it is thrown by the container’s hash function or comparison function.
|===

[[unordered_set_deduction_guides]]
=== 推导指南

A deduction guide will not participate in overload resolution if any of
the following are true:

* It has an `InputIterator` template parameter and a type that does not
qualify as an input iterator is deduced for that parameter.
* It has an `Allocator` template parameter and a type that does not
qualify as an allocator is deduced for that parameter.
* It has a `Hash` template parameter and an integral type or a type that
qualifies as an allocator is deduced for that parameter.
* It has a `Pred` template parameter and a type that qualifies as an
allocator is deduced for that parameter.

A `size_­type` parameter type in a deduction guide refers to the
`size_­type` member type of the container type deduced by the deduction
guide. Its default value coincides with the default value of the
constructor selected.

[[unordered_set_iter_value_type]]
==== _iter-value-type_

....
template<class InputIterator>
  using iter-value-type =
    typename std::iterator_traits<InputIterator>::value_type; // exposition only
....

[[unordered_set_equality_comparisons]]
=== Equality Comparisons

[[unordered_set_operator]]
==== operator==

[source,highlight]
----
template<class Key, class Hash, class Pred, class Alloc>
  bool operator==(const unordered_set<Key, Hash, Pred, Alloc>& x,
                  const unordered_set<Key, Hash, Pred, Alloc>& y);
----

Return `true` if `x.size() == y.size()` and for every element in `x`,
there is an element in `y` with the same key, with an equal value (using
`operator==` to compare the value types).

[cols=",",]
|===
|Notes: |Behavior is undefined if the two containers don’t have
equivalent equality predicates.
|===

'''''

[[unordered_set_operator_2]]
==== operator!=

[source,highlight]
----
template<class Key, class Hash, class Pred, class Alloc>
  bool operator!=(const unordered_set<Key, Hash, Pred, Alloc>& x,
                  const unordered_set<Key, Hash, Pred, Alloc>& y);
----

Return `false` if `x.size() == y.size()` and for every element in `x`,
there is an element in `y` with the same key, with an equal value (using
`operator==` to compare the value types).

[cols=",",]
|===
|Notes: |Behavior is undefined if the two containers don’t have
equivalent equality predicates.
|===

'''''

[[unordered_set_swap_2]]
=== 交换

[source,highlight]
----
template<class Key, class Hash, class Pred, class Alloc>
  void swap(unordered_set<Key, Hash, Pred, Alloc>& x,
            unordered_set<Key, Hash, Pred, Alloc>& y)
    noexcept(noexcept(x.swap(y)));
----

Swaps the contents of `x` and `y`.

If `Allocator::propagate_on_container_swap` is declared and
`Allocator::propagate_on_container_swap::value` is `true` then the
containers' allocators are swapped. Otherwise, swapping with unequal
allocators results in undefined behavior.

[cols=",",]
|===
|Effects: |`x.swap(y)`

|Throws: |Doesn’t throw an exception unless it is thrown by the copy
constructor or copy assignment operator of `key_equal` or `hasher`.

|Notes: |The exception specifications aren’t quite the same as the C++11
standard, as the equality predicate and hash function are swapped using
their copy constructors.
|===

'''''

[[unordered_set_erase_if]]
=== erase_if

[source,highlight]
----
template<class K, class H, class P, class A, class Predicate>
  typename unordered_set<K, H, P, A>::size_type
    erase_if(unordered_set<K, H, P, A>& c, Predicate pred);
----

Traverses the container `c` and removes all elements for which the
supplied predicate returns `true`.

[width="100%",cols="50%,50%",]
|===
|Returns: |The number of erased elements.
|Notes: a|
Equivalent to: +

[source,highlight]
----
auto original_size = c.size();
for (auto i = c.begin(), last = c.end(); i != last; ) {
  if (pred(*i)) {
    i = c.erase(i);
  } else {
    ++i;
  }
}
return original_size - c.size();
----

|===

[[unordered_set_serialization]]
=== Serialization

`unordered_set`s can be archived/retrieved by means of
link:../../../../../serialization/index.html[Boost.Serialization] using
the API provided by this library. Both regular and XML archives are
supported.

[[unordered_set_saving_an_unordered_set_to_an_archive]]
==== Saving an unordered_set to an archive

Saves all the elements of an `unordered_set` `x` to an archive (XML
archive) `ar`.

[cols=",",]
|===
|Requires: |`value_type` is serializable (XML serializable), and it
supports Boost.Serialization `save_construct_data`/`load_construct_data`
protocol (automatically suported by
https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[DefaultConstructible]
types).
|===

'''''

[[unordered_set_loading_an_unordered_set_from_an_archive]]
==== Loading an unordered_set from an archive

Deletes all preexisting elements of an `unordered_set` `x` and inserts
from an archive (XML archive) `ar` restored copies of the elements of
the original `unordered_set` `other` saved to the storage read by `ar`.

[cols=",",]
|===
|Requires: |`value_type` is
https://en.cppreference.com/w/cpp/named_req/MoveInsertable[MoveInsertable].
`x.key_equal()` is functionally equivalent to `other.key_equal()`.

|Note: |If the archive was saved using a release of Boost prior to Boost
1.84, the configuration macro
`BOOST_UNORDERED_ENABLE_SERIALIZATION_COMPATIBILITY_V0` has to be
globally defined for this operation to succeed; otherwise, an exception
is thrown.
|===

'''''

[[unordered_set_saving_an_iteratorconst_iterator_to_an_archive]]
==== Saving an iterator/const_iterator to an archive

Saves the positional information of an `iterator` (`const_iterator`)
`it` to an archive (XML archive) `ar`. `it` can be and `end()` iterator.

[cols=",",]
|===
|Requires: |The `unordered_set` `x` pointed to by `it` has been
previously saved to `ar`, and no modifying operations have been issued
on `x` between saving of `x` and saving of `it`.
|===

'''''

[[unordered_set_loading_an_iteratorconst_iterator_from_an_archive]]
==== Loading an iterator/const_iterator from an archive

Makes an `iterator` (`const_iterator`) `it` point to the restored
position of the original `iterator` (`const_iterator`) saved to the
storage read by an archive (XML archive) `ar`.

[cols=",",]
|===
|Requires: |If `x` is the `unordered_set` `it` points to, no modifying
operations have been issued on `x` between loading of `x` and loading of
`it`.
|===

[[footer]]
[[footer-text]]
Last updated 2025-10-31 21:42:55 UTC
