[[header]]
== Change Log

[[content]]
[[changes_release_1_89_0]]
=== Release 1.89.0

* Deprecated `boost::unordered::hash++_++is++_++avalanching` is now a
using-declaration of `boost::hash++_++is++_++avalanching` in
`++<++boost/container++_++hash/hash++_++is++_++avalanching.hpp++>++`.
Use that header directly instead.
`++<++boost/unordered/hash++_++traits.hpp++>++` will be removed in the
future.
* Added `pull(const++_++iterator)` to open-addressing containers. This
operation allows for efficient removal and retrieval of an element via
move construction.

[[changes_release_1_88_0]]
=== Release 1.88.0

* Migrated the documentation to a multipage format using Antora.

[[changes_release_1_87_0_major_update]]
=== Release 1.87.0 - Major update

* Added concurrent, node-based containers
`boost::concurrent++_++node++_++map` and
`boost::concurrent++_++node++_++set`.
* Added `insert++_++and++_++visit(x, f1, f2)` and similar operations to
concurrent containers, which allow for visitation of an element right
after insertion (by contrast, `insert++_++or++_++visit(x, f)` only
visits the element if insertion did _not_ take place).
* Made visitation exclusive-locked within certain
`boost::concurrent++_++flat++_++set` operations to allow for safe
mutable modification of elements
(https://github.com/boostorg/unordered/pull/265[PR#265]).
* In Visual Studio Natvis, supported any container with an allocator
that uses fancy pointers. This applies to any fancy pointer type, as
long as the proper Natvis customization point "Intrinsic" functions are
written for the fancy pointer type.
* Added GDB pretty-printers for all containers and iterators. For a
container with an allocator that uses fancy pointers, these only work if
the proper pretty-printer is written for the fancy pointer type itself.
* Fixed `std::initializer++_++list` assignment issues for
open-addressing containers
(https://github.com/boostorg/unordered/pull/277[PR#277]).
* Allowed non-copyable callables to be passed to the
`std::initializer++_++list` overloads of
`insert++_{++and++|++or}++_[++c++]++visit` for concurrent containers, by
internally passing a `std::reference++_++wrapper` of the callable to the
iterator-pair overloads.

[[changes_release_1_86_0]]
=== Release 1.86.0

* Added container `pmr` aliases when header
`++<++memory++_++resource++>++` is available. The alias
`boost::unordered::pmr::++[++container++]++` refers to
`boost::unordered::++[++container++]++` with a
`std::pmr::polymorphic++_++allocator` allocator type.
* Equipped open-addressing and concurrent containers to internally
calculate and provide statistical metrics affected by the quality of the
hash function. This functionality is enabled by the global macro
`BOOST++_++UNORDERED++_++ENABLE++_++STATS`.
* Avalanching hash functions must now be marked via an
`is++_++avalanching` typedef with an embedded `value` constant set to
`true` (typically, defining `is++_++avalanching` as
`std::true++_++type`). `using is++_++avalanching = void` is deprecated
but allowed for backwards compatibility.
* Added Visual Studio Natvis framework custom visualizations for
containers and iterators. This works for all containers with an
allocator using raw pointers. In this release, containers and iterators
are not supported if their allocator uses fancy pointers. This may be
addressed in later releases.

[[changes_release_1_85_0]]
=== Release 1.85.0

* Optimized `emplace()` for a `value++_++type` or `init++_++type` (if
applicable) argument to bypass creating an intermediate object. The
argument is already the same type as the would-be intermediate object.
* Optimized `emplace()` for `k,v` arguments on map containers to delay
constructing the object until it is certain that an element should be
inserted. This optimization happens when the map’s `key++_++type` is
move constructible or when the `k` argument is a `key++_++type`.
* Fixed support for allocators with `explicit` copy constructors
(https://github.com/boostorg/unordered/pull/234[PR#234]).
* Fixed bug in the `const` version of
`unordered++_++multimap::find(k, hash, eq)`
(https://github.com/boostorg/unordered/pull/238[PR#238]).

[[changes_release_1_84_0_major_update]]
=== Release 1.84.0 - Major update

* Added `boost::concurrent++_++flat++_++set`.
* Added `++[++c++]++visit++_++while` operations to concurrent
containers, with serial and parallel variants.
* Added efficient move construction of
`boost::unordered++_++flat++_++(map++|++set)` from
`boost::concurrent++_++flat++_++(map++|++set)` and vice versa.
* Added bulk visitation to concurrent containers for increased lookup
performance.
* Added debug-mode mechanisms for detecting illegal reentrancies into a
concurrent container from user code.
* Added Boost.Serialization support to all containers and their
(non-local) iterator types.
* Added support for fancy pointers to open-addressing and concurrent
containers. This enables scenarios like the use of Boost.Interprocess
allocators to construct containers in shared memory.
* Fixed bug in member of pointer operator for local iterators of
closed-addressing containers
(https://github.com/boostorg/unordered/pull/221[PR#221], credit goes to
GitHub user vslashg for finding and fixing this issue).
* Starting with this release, `boost::unordered++_[++multi++]++set` and
`boost::unordered++_[++multi++]++map` only work with C{plus}{plus}11
onwards.

[[changes_release_1_83_0_major_update]]
=== Release 1.83.0 - Major update

* Added `boost::concurrent++_++flat++_++map`, a fast, thread-safe
hashmap based on open addressing.
* Sped up iteration of open-addressing containers.
* In open-addressing containers, `erase(iterator)`, which previously
returned nothing, now returns a proxy object convertible to an iterator
to the next element. This enables the typical `it = c.erase(it)` idiom
without incurring any performance penalty when the returned proxy is not
used.

[[changes_release_1_82_0_major_update]]
=== Release 1.82.0 - Major update

* C{plus}{plus}03 support is planned for deprecation. Boost 1.84.0 will
no longer support C{plus}{plus}03 mode and C{plus}{plus}11 will become
the new minimum for using the library.
* Added node-based, open-addressing containers
`boost::unordered++_++node++_++map` and
`boost::unordered++_++node++_++set`.
* Extended heterogeneous lookup to more member functions as specified in
https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/p2363r5.html[P2363].
* Replaced the previous post-mixing process for open-addressing
containers with a new algorithm based on extended multiplication by a
constant.
* Fixed bug in internal emplace() impl where stack-local types were not
properly constructed using the Allocator of the container which breaks
uses-allocator construction.

[[changes_release_1_81_0_major_update]]
=== Release 1.81.0 - Major update

* Added fast containers `boost::unordered++_++flat++_++map` and
`boost::unordered++_++flat++_++set` based on open addressing.
* Added CTAD deduction guides for all containers.
* Added missing constructors as specified in
https://cplusplus.github.io/LWG/issue2713[LWG issue 2713].

[[changes_release_1_80_0_major_update]]
=== Release 1.80.0 - Major update

* Refactor internal implementation to be dramatically faster
* Allow `final` Hasher and KeyEqual objects
* Update documentation, adding benchmark graphs and notes on the new
internal data structures

[[changes_release_1_79_0]]
=== Release 1.79.0

* Improved C{plus}{plus}20 support:
+
** All containers have been updated to support heterogeneous `count`,
`equal++_++range` and `find`.
** All containers now implement the member function `contains`.
** `erase++_++if` has been implemented for all containers.
* Improved C{plus}{plus}23 support:
+
** All containers have been updated to support heterogeneous `erase` and
`extract`.
* Changed behavior of `reserve` to eagerly allocate
(https://github.com/boostorg/unordered/pull/59[PR#59]).
* Various warning fixes in the test suite.
* Update code to internally use `boost::allocator++_++traits`.
* Switch to Fibonacci hashing.
* Update documentation to be written in AsciiDoc instead of QuickBook.

[[changes_release_1_67_0]]
=== Release 1.67.0

* Improved C{plus}{plus}17 support:
+
** Add template deduction guides from the standard.
** Use a simple implementation of `optional` in node handles, so that
they’re closer to the standard.
** Add missing `noexcept` specifications to `swap`, `operator=` and node
handles, and change the implementation to match. Using
`std::allocator++_++traits::is++_++always++_++equal`, or our own
implementation when not available, and
`boost::is++_++nothrow++_++swappable` in the implementation.
* Improved C{plus}{plus}20 support:
+
** Use `boost::to++_++address`, which has the proposed C{plus}{plus}20
semantics, rather than the old custom implementation.
* Add `element++_++type` to iterators, so that `std::pointer++_++traits`
will work.
* Use `std::piecewise++_++construct` on recent versions of Visual
C{plus}{plus}, and other uses of the Dinkumware standard library, now
using Boost.Predef to check compiler and library versions.
* Use `std::iterator++_++traits` rather than the boost iterator traits
in order to remove dependency on Boost.Iterator.
* Remove iterators' inheritance from `std::iterator`, which is
deprecated in C{plus}{plus}17, thanks to Daniela Engert
(https://github.com/boostorg/unordered/pull/7[PR#7]).
* Stop using `BOOST++_++DEDUCED++_++TYPENAME`.
* Update some Boost include paths.
* Rename some internal methods, and variables.
* Various testing improvements.
* Miscellaneous internal changes.

[[changes_release_1_66_0]]
=== Release 1.66.0

* Simpler move construction implementation.
* Documentation fixes
(https://github.com/boostorg/unordered/pull/6[GitHub #6]).

[[changes_release_1_65_0]]
=== Release 1.65.0

* Add deprecated attributes to `quick++_++erase` and
`erase++_++return++_++void`. I really will remove them in a future
version this time.
* Small standards compliance fixes:
+
** `noexpect` specs for `swap` free functions.
** Add missing `insert(P&&)` methods.

[[changes_release_1_64_0]]
=== Release 1.64.0

* Initial support for new C{plus}{plus}17 member functions:
`insert++_++or++_++assign` and `try++_++emplace` in `unordered++_++map`,
* Initial support for `merge` and `extract`. Does not include
transferring nodes between `unordered++_++map` and
`unordered++_++multimap` or between `unordered++_++set` and
`unordered++_++multiset` yet. That will hopefully be in the next version
of Boost.

[[changes_release_1_63_0]]
=== Release 1.63.0

* Check hint iterator in `insert`/`emplace++_++hint`.
* Fix some warnings, mostly in the tests.
* Manually write out `emplace++_++args` for small numbers of arguments -
should make template error messages a little more bearable.
* Remove superfluous use of `boost::forward` in emplace arguments, which
fixes emplacing string literals in old versions of Visual C{plus}{plus}.
* Fix an exception safety issue in assignment. If bucket allocation
throws an exception, it can overwrite the hash and equality functions
while leaving the existing elements in place. This would mean that the
function objects wouldn’t match the container elements, so elements
might be in the wrong bucket and equivalent elements would be
incorrectly handled.
* Various reference documentation improvements.
* Better allocator support
(https://svn.boost.org/trac/boost/ticket/12459[#12459]).
* Make the no argument constructors implicit.
* Implement missing allocator aware constructors.
* Fix assigning the hash/key equality functions for empty containers.
* Remove unary/binary++_++function from the examples in the
documentation. They are removed in C{plus}{plus}17.
* Support 10 constructor arguments in emplace. It was meant to support
up to 10 arguments, but an off by one error in the preprocessor code
meant it only supported up to 9.

[[changes_release_1_62_0]]
=== Release 1.62.0

* Remove use of deprecated `boost::iterator`.
* Remove `BOOST++_++NO++_++STD++_++DISTANCE` workaround.
* Remove `BOOST++_++UNORDERED++_++DEPRECATED++_++EQUALITY` warning.
* Simpler implementation of assignment, fixes an exception safety issue
for `unordered++_++multiset` and `unordered++_++multimap`. Might be a
little slower.
* Stop using return value SFINAE which some older compilers have issues
with.

[[changes_release_1_58_0]]
=== Release 1.58.0

* Remove unnecessary template parameter from const iterators.
* Rename private `iterator` typedef in some iterator classes, as it
confuses some traits classes.
* Fix move assignment with stateful,
propagate++_++on++_++container++_++move++_++assign allocators
(https://svn.boost.org/trac/boost/ticket/10777[#10777]).
* Fix rare exception safety issue in move assignment.
* Fix potential overflow when calculating number of buckets to allocate
(https://github.com/boostorg/unordered/pull/4[GitHub #4]).

[[changes_release_1_57_0]]
=== Release 1.57.0

* Fix the `pointer` typedef in iterators
(https://svn.boost.org/trac/boost/ticket/10672[#10672]).
* Fix Coverity warning
(https://github.com/boostorg/unordered/pull/2[GitHub #2]).

[[changes_release_1_56_0]]
=== Release 1.56.0

* Fix some shadowed variable warnings
(https://svn.boost.org/trac/boost/ticket/9377[#9377]).
* Fix allocator use in documentation
(https://svn.boost.org/trac/boost/ticket/9719[#9719]).
* Always use prime number of buckets for integers. Fixes performance
regression when inserting consecutive integers, although makes other
uses slower (https://svn.boost.org/trac/boost/ticket/9282[#9282]).
* Only construct elements using allocators, as specified in
C{plus}{plus}11 standard.

[[changes_release_1_55_0]]
=== Release 1.55.0

* Avoid some warnings
(https://svn.boost.org/trac/boost/ticket/8851[#8851],
https://svn.boost.org/trac/boost/ticket/8874[#8874]).
* Avoid exposing some detail functions via. ADL on the iterators.
* Follow the standard by only using the allocators' construct and
destroy methods to construct and destroy stored elements. Don’t use them
for internal data like pointers.

[[changes_release_1_54_0]]
=== Release 1.54.0

* Mark methods specified in standard as `noexpect`. More to come in the
next release.
* If the hash function and equality predicate are known to both have
nothrow move assignment or construction then use them.

[[changes_release_1_53_0]]
=== Release 1.53.0

* Remove support for the old pre-standard variadic pair constructors,
and equality implementation. Both have been deprecated since Boost 1.48.
* Remove use of deprecated config macros.
* More internal implementation changes, including a much simpler
implementation of `erase`.

[[changes_release_1_52_0]]
=== Release 1.52.0

* Faster assign, which assigns to existing nodes where possible, rather
than creating entirely new nodes and copy constructing.
* Fixed bug in `erase++_++range`
(https://svn.boost.org/trac/boost/ticket/7471[#7471]).
* Reverted some of the internal changes to how nodes are created,
especially for C{plus}{plus}11 compilers. 'construct' and 'destroy'
should work a little better for C{plus}{plus}11 allocators.
* Simplified the implementation a bit. Hopefully more robust.

[[changes_release_1_51_0]]
=== Release 1.51.0

* Fix construction/destruction issue when using a C{plus}{plus}11
compiler with a C{plus}{plus}03 allocator
(https://svn.boost.org/trac/boost/ticket/7100[#7100]).
* Remove a `try..catch` to support compiling without exceptions.
* Adjust SFINAE use to try to support g{plus}{plus} 3.4
(https://svn.boost.org/trac/boost/ticket/7175[#7175]).
* Updated to use the new config macros.

[[changes_release_1_50_0]]
=== Release 1.50.0

* Fix equality for `unordered++_++multiset` and
`unordered++_++multimap`.
* https://svn.boost.org/trac/boost/ticket/6857[Ticket 6857]: Implement
`reserve`.
* https://svn.boost.org/trac/boost/ticket/6771[Ticket 6771]: Avoid gcc’s
`-Wfloat-equal` warning.
* https://svn.boost.org/trac/boost/ticket/6784[Ticket 6784]: Fix some
Sun specific code.
* https://svn.boost.org/trac/boost/ticket/6190[Ticket 6190]: Avoid gcc’s
`-Wshadow` warning.
* https://svn.boost.org/trac/boost/ticket/6905[Ticket 6905]: Make
namespaces in macros compatible with `bcp` custom namespaces. Fixed by
Luke Elliott.
* Remove some of the smaller prime number of buckets, as they may make
collisions quite probable (e.g. multiples of 5 are very common because
we used base 10).
* On old versions of Visual C{plus}{plus}, use the container library’s
implementation of `allocator++_++traits`, as it’s more likely to work.
* On machines with 64 bit std::size++_++t, use power of 2 buckets, with
Thomas Wang’s hash function to pick which one to use. As modulus is very
slow for 64 bit values.
* Some internal changes.

[[changes_release_1_49_0]]
=== Release 1.49.0

* Fix warning due to accidental odd assignment.
* Slightly better error messages.

[[changes_release_1_48_0_major_update]]
=== Release 1.48.0 - Major update

This is major change which has been converted to use Boost.Move’s move
emulation, and be more compliant with the C{plus}{plus}11 standard. See
the link:compliance.html[compliance section] for details.

The container now meets C{plus}{plus}11’s complexity requirements, but
to do so uses a little more memory. This means that `quick++_++erase`
and `erase++_++return++_++void` are no longer required, they’ll be
removed in a future version.

C{plus}{plus}11 support has resulted in some breaking changes:

* Equality comparison has been changed to the C{plus}{plus}11
specification. In a container with equivalent keys, elements in a group
with equal keys used to have to be in the same order to be considered
equal, now they can be a permutation of each other. To use the old
behavior define the macro
`BOOST++_++UNORDERED++_++DEPRECATED++_++EQUALITY`.
* The behaviour of swap is different when the two containers to be
swapped has unequal allocators. It used to allocate new nodes using the
appropriate allocators, it now swaps the allocators if the allocator has
a member structure `propagate++_++on++_++container++_++swap`, such that
`propagate++_++on++_++container++_++swap::value` is true.
* Allocator’s `construct` and `destroy` functions are called with raw
pointers, rather than the allocator’s `pointer` type.
* `emplace` used to emulate the variadic pair constructors that appeared
in early C{plus}{plus}0x drafts. Since they were removed it no longer
does so. It does emulate the new `piecewise++_++construct` pair
constructors - only you need to use `boost::piecewise++_++construct`. To
use the old emulation of the variadic constructors define
`BOOST++_++UNORDERED++_++DEPRECATED++_++PAIR++_++CONSTRUCT`.

[[changes_release_1_45_0]]
=== Release 1.45.0

* Fix a bug when inserting into an `unordered++_++map` or
`unordered++_++set` using iterators which returns `value++_++type` by
copy.

[[changes_release_1_43_0]]
=== Release 1.43.0

* https://svn.boost.org/trac/boost/ticket/3966[Ticket 3966]:
`erase++_++return++_++void` is now `quick++_++erase`, which is the
http://home.roadrunner.com/~hinnant/issue_review/lwg-active.html#579[current
forerunner for resolving the slow erase by iterator], although there’s a
strong possibility that this may change in the future. The old method
name remains for backwards compatibility but is considered deprecated
and will be removed in a future release.
* Use Boost.Exception.
* Stop using deprecated `BOOST++_++HAS++_*++` macros.

[[changes_release_1_42_0]]
=== Release 1.42.0

* Support instantiating the containers with incomplete value types.
* Reduced the number of warnings (mostly in tests).
* Improved codegear compatibility.
* https://svn.boost.org/trac/boost/ticket/3693[Ticket 3693]: Add
`erase++_++return++_++void` as a temporary workaround for the current
`erase` which can be inefficient because it has to find the next element
to return an iterator.
* Add templated find overload for compatible keys.
* https://svn.boost.org/trac/boost/ticket/3773[Ticket 3773]: Add missing
`std` qualifier to `ptrdiff++_++t`.
* Some code formatting changes to fit almost all lines into 80
characters.

[[changes_release_1_41_0_major_update]]
=== Release 1.41.0 - Major update

* The original version made heavy use of macros to sidestep some of the
older compilers' poor template support. But since I no longer support
those compilers and the macro use was starting to become a maintenance
burden it has been rewritten to use templates instead of macros for the
implementation classes.
* The container object is now smaller thanks to using
`boost::compressed++_++pair` for EBO and a slightly different function
buffer - now using a bool instead of a member pointer.
* Buckets are allocated lazily which means that constructing an empty
container will not allocate any memory.

[[changes_release_1_40_0]]
=== Release 1.40.0

* https://svn.boost.org/trac/boost/ticket/2975[Ticket 2975]: Store the
prime list as a preprocessor sequence - so that it will always get the
length right if it changes again in the future.
* https://svn.boost.org/trac/boost/ticket/1978[Ticket 1978]: Implement
`emplace` for all compilers.
* https://svn.boost.org/trac/boost/ticket/2908[Ticket 2908],
https://svn.boost.org/trac/boost/ticket/3096[Ticket 3096]: Some
workarounds for old versions of borland, including adding explicit
destructors to all containers.
* https://svn.boost.org/trac/boost/ticket/3082[Ticket 3082]: Disable
incorrect Visual C{plus}{plus} warnings.
* Better configuration for C{plus}{plus}0x features when the headers
aren’t available.
* Create less buckets by default.

[[changes_release_1_39_0]]
=== Release 1.39.0

* https://svn.boost.org/trac/boost/ticket/2756[Ticket 2756]: Avoid a
warning on Visual C{plus}{plus} 2009.
* Some other minor internal changes to the implementation, tests and
documentation.
* Avoid an unnecessary copy in `operator++[]++`.
* https://svn.boost.org/trac/boost/ticket/2975[Ticket 2975]: Fix length
of prime number list.

[[changes_release_1_38_0]]
=== Release 1.38.0

* Use link:../../../../core/swap.html[`boost::swap`].
* https://svn.boost.org/trac/boost/ticket/2237[Ticket 2237]: Document
that the equality and inequality operators are undefined for two objects
if their equality predicates aren’t equivalent. Thanks to Daniel
Krügler.
* https://svn.boost.org/trac/boost/ticket/1710[Ticket 1710]: Use a
larger prime number list. Thanks to Thorsten Ottosen and Hervé
Brönnimann.
* Use link:../../../../type_traits/index.html[aligned storage] to store
the types. This changes the way the allocator is used to construct
nodes. It used to construct the node with two calls to the allocator’s
`construct` method - once for the pointers and once for the value. It
now constructs the node with a single call to construct and then
constructs the value using in place construction.
* Add support for C{plus}{plus}0x initializer lists where they’re
available (currently only g{plus}{plus} 4.4 in C{plus}{plus}0x mode).

[[changes_release_1_37_0]]
=== Release 1.37.0

* Rename overload of `emplace` with hint, to `emplace++_++hint` as
specified in
http://www.open-std.org/JTC1/SC22/WG21/docs/papers/2008/n2691.pdf[n2691].
* Provide forwarding headers at
`++<++boost/unordered/unordered++_++map++_++fwd.hpp++>++` and
`++<++boost/unordered/unordered++_++set++_++fwd.hpp++>++`.
* Move all the implementation inside `boost/unordered`, to assist
modularization and hopefully make it easier to track Release subversion.

[[changes_release_1_36_0]]
=== Release 1.36.0

First official release.

* Rearrange the internals.
* Move semantics - full support when rvalue references are available,
emulated using a cut down version of the Adobe move library when they
are not.
* Emplace support when rvalue references and variadic template are
available.
* More efficient node allocation when rvalue references and variadic
template are available.
* Added equality operators.

[[changes_boost_1_35_0_add_on_31st_march_2008]]
=== Boost 1.35.0 Add-on - 31st March 2008

Unofficial release uploaded to vault, to be used with Boost 1.35.0.
Incorporated many of the suggestions from the review.

* Improved portability thanks to Boost regression testing.
* Fix lots of typos, and clearer text in the documentation.
* Fix floating point to `std::size++_++t` conversion when calculating
sizes from the max load factor, and use `double` in the calculation for
greater accuracy.
* Fix some errors in the examples.

[[changes_review_version]]
=== Review Version

Initial review version, for the review conducted from 7th December 2007
to 16th December 2007.

[[footer]]
[[footer-text]]
Last updated 2025-10-31 10:41:04 UTC
