[[header]]
== 引 言

[[content]]
https://en.wikipedia.org/wiki/Hash_table[Hash tables] are extremely
popular computer data structures and can be found under one form or
another in virtually any programming language. Whereas other associative
structures such as rb-trees (used in C{plus}{plus} by `std::set` and
`std::map`) have logarithmic-time complexity for insertion and lookup,
hash tables, if configured properly, perform these operations in
constant time on average, and are generally much faster.

C{plus}{plus}11引入了__无序关联容器__
`std::unordered++_++set`、`std::unordered++_++map`、`std::unordered++_++multiset`与`std::unordered++_++multimap`，但自那时起哈希表的研究从未止步：CPU架构的进步，诸如更强大的缓存、
https://en.wikipedia.org/wiki/Single_instruction_multiple_data[SIMD]操作以及日益普及的
https://en.wikipedia.org/wiki/Multi-core_processor[多核处理器]
，为改进基于哈希的数据结构开辟了新可能，并催生了2011版规范中无序关联容器根本无法实现的新用例。

Boost.Unordered提供了一系列具有不同标准兼容级别、性能表现及目标使用场景的哈希容器：

.Table 1. Boost.Unordered containers
[width="100%",cols="34%,33%,33%",]
|===
| |*基于节点* |*平坦*

|*闭寻址* |`boost::unordered++_++set` +
`boost::unordered++_++map` +
`boost::unordered++_++multiset` +
`boost::unordered++_++multimap` |

|*开放寻址法* |`boost::unordered++_++node++_++set` +
`boost::unordered++_++node++_++map`
|`boost::unordered++_++flat++_++set` +
`boost::unordered++_++flat++_++map`

|*并发* |`boost::concurrent++_++node++_++set` +
`boost::concurrent++_++node++_++map`
|`boost::concurrent++_++flat++_++set` +
`boost::concurrent++_++flat++_++map`
|===

* **闭寻址容器**完全符合C{plus}{plus}对无序关联容器的规范要求，且在标准接口规定的技术约束下，实现了当前业界最快的处理方案之一。
* **开放寻址容器**依赖更快的数据结构和算法（典型场景下速度最快可高出两倍以上），并通过微调标准接口以适配实现。其提供两种变体：*平坦结构*（速度最快）和**节点结构**（在重散列时保障指针稳定性，代价则是较慢的运行效率）。
* 最后，**并发容器**专为高性能多线程场景设计与实现。其接口与常规C{plus}{plus}容器截然不同，同时提供平面版本和基于节点的版本。

Boost.Unordered中的所有集合（set）与映射（map）容器的实例化方式分别与`std::unordered++_++set`和`std::unordered++_++map`相同：

[source,highlight]
----
namespace boost {
    template <
        class Key,
        class Hash = boost::hash<Key>,
        class Pred = std::equal_to<Key>,
        class Alloc = std::allocator<Key> >
    class unordered_set;
    // same for unordered_multiset, unordered_flat_set, unordered_node_set,
    // concurrent_flat_set and concurrent_node_set

    template <
        class Key, class Mapped,
        class Hash = boost::hash<Key>,
        class Pred = std::equal_to<Key>,
        class Alloc = std::allocator<std::pair<Key const, Mapped> > >
    class unordered_map;
    // same for unordered_multimap, unordered_flat_map, unordered_node_map,
    // concurrent_flat_map and concurrent_node_map
}
----

Storing an object in an unordered associative container requires both a
key equality function and a hash function. The default function objects
in the standard containers support a few basic types including integer
types, floating point types, pointer types, and the standard strings.
Since Boost.Unordered uses
link:../../../../container_hash/index.html[boost::hash] it also supports
some other types, including standard containers. To use any types not
supported by these methods you have to extend Boost.Hash to support the
type or use your own custom equality predicates and hash functions. See
the link:hash_equality.html#hash_equality[Equality Predicates and Hash
Functions], section for more details.

[[footer]]
[[footer-text]]
Last updated 2025-10-22 17:11:30 UTC
