[[header]]
== 引 言

[[content]]
https://en.wikipedia.org/wiki/Hash_table[Hash tables] are extremely
popular computer data structures and can be found under one form or
another in virtually any programming language. Whereas other associative
structures such as rb-trees (used in C{plus}{plus} by `std::set` and
`std::map`) have logarithmic-time complexity for insertion and lookup,
hash tables, if configured properly, perform these operations in
constant time on average, and are generally much faster.

C{plus}{plus}11 引入了无序关联容器
`std::unordered++_++set`、`std::unordered++_++map`、`std::unordered++_++multiset`
与 `std::unordered++_++multimap`，但哈希表的研究从未止步：得益于 CPU
架构的进步——包括更强大的缓存性能、https://en.wikipedia.org/wiki/Single_instruction,_multiple_data[SIMD]
指令集以及日益普及的https://en.wikipedia.org/wiki/Multi-core_processor[多核处理器]——如今不仅可实现性能更优的哈希数据结构，更能达成
2011 年指定的无序关联容器无法企及的全新应用场景。

Boost.Unordered
提供了一系列散列容器产品目录，涵盖不同的标准合规性级别、性能表现及适用场景：

.Table 1. Boost.Unordered containers
[width="100%",cols="34%,33%,33%",]
|===
| |*基于节点的* |*扁平*

|*闭散列* |`boost::unordered++_++set` +
`boost::unordered++_++map` +
`boost::unordered++_++multiset` +
`boost::unordered++_++multimap` |

|*开放地址法* |`boost::unordered++_++node++_++set` +
`boost::unordered++_++node++_++map`
|`boost::unordered++_++flat++_++set` +
`boost::unordered++_++flat++_++map`

|*并发* |`boost::concurrent++_++node++_++set` +
`boost::concurrent++_++node++_++map`
|`boost::concurrent++_++flat++_++set` +
`boost::concurrent++_++flat++_++map`
|===

* **闭地址容器**完全符合C{plus}{plus}无序关联容器的规范要求，在所需标准接口的技术限制下，具备业内领先的运行速度实现。
* **开放寻址容器**采用更快速的数据结构和算法（在典型场景下性能远超两倍以上），同时为适配实现方案而对标准接口进行了轻微调整。其提供两种变体：*扁平化容器*（速度最快）和**节点容器**——后者保证重新哈希时指针稳定性，但速度较慢。
* 最后，**并发容器**专为高性能多线程场景设计实现。其接口与普通C{plus}{plus}容器存在根本性差异，且同时提供扁平化存储和基于节点的实现变体。

Boost.Unordered 中的所有集合和映射的实例化方式分别与
`std::unordered++_++set` 和 `std::unordered++_++map` 类似：

[source,highlight]
----
namespace boost {
    template <
        class Key,
        class Hash = boost::hash<Key>,
        class Pred = std::equal_to<Key>,
        class Alloc = std::allocator<Key> >
    class unordered_set;
    // same for unordered_multiset, unordered_flat_set, unordered_node_set,
    // concurrent_flat_set and concurrent_node_set

    template <
        class Key, class Mapped,
        class Hash = boost::hash<Key>,
        class Pred = std::equal_to<Key>,
        class Alloc = std::allocator<std::pair<Key const, Mapped> > >
    class unordered_map;
    // same for unordered_multimap, unordered_flat_map, unordered_node_map,
    // concurrent_flat_map and concurrent_node_map
}
----

Storing an object in an unordered associative container requires both a
key equality function and a hash function. The default function objects
in the standard containers support a few basic types including integer
types, floating point types, pointer types, and the standard strings.
Since Boost.Unordered uses
link:../../../../container_hash/index.html[boost::hash] it also supports
some other types, including standard containers. To use any types not
supported by these methods you have to extend Boost.Hash to support the
type or use your own custom equality predicates and hash functions. See
the link:hash_equality.html#hash_equality[Equality Predicates and Hash
Functions], section for more details.

[[footer]]
[[footer-text]]
Last updated 2025-10-17 20:53:16 UTC
