[[header]]
== 引言

[[content]]
https://en.wikipedia.org/wiki/Hash_table[哈希表]是极为流行的计算机数据结构，几乎可以在任何一种编程语言中以某种形式存在。尽管其他关联式结构（如红黑树——在C{plus}{plus}中由`std::set`和`std::map`使用）的插入与查找操作具备对数时间复杂度，但哈希表若配置得当，平均而言可在常数时间内完成这些操作，且执行效率通常显著更高。

C{plus}{plus} introduced _unordered associative containers_
`std::unordered++_++set`, `std::unordered++_++map`,
`std::unordered++_++multiset` and `std::unordered++_++multimap` in
C{plus}{plus}11, but research on hash tables hasn’t stopped since:
advances in CPU architectures such as more powerful caches,
https://en.wikipedia.org/wiki/Single_instruction,_multiple_data[SIMD]
operations and increasingly available
https://en.wikipedia.org/wiki/Multi-core_processor[multicore processors]
open up possibilities for improved hash-based data structures and new
use cases that are simply beyond reach of unordered associative
containers as specified in 2011.

Boost.Unordered offers a catalog of hash containers with different
standards compliance levels, performances and intented usage scenarios:

.Table 1. Boost.Unordered containers
[width="100%",cols="34%,33%,33%",]
|===
| |*Node-based* |*Flat*

|*Closed addressing* |`boost::unordered++_++set` +
`boost::unordered++_++map` +
`boost::unordered++_++multiset` +
`boost::unordered++_++multimap` |

|*Open addressing* |`boost::unordered++_++node++_++set` +
`boost::unordered++_++node++_++map`
|`boost::unordered++_++flat++_++set` +
`boost::unordered++_++flat++_++map`

|*Concurrent* |`boost::concurrent++_++node++_++set` +
`boost::concurrent++_++node++_++map`
|`boost::concurrent++_++flat++_++set` +
`boost::concurrent++_++flat++_++map`
|===

* *Closed-addressing containers* are fully compliant with the
C{plus}{plus} specification for unordered associative containers and
feature one of the fastest implementations in the market within the
technical constraints imposed by the required standard interface.
* *Open-addressing containers* rely on much faster data structures and
algorithms (more than 2 times faster in typical scenarios) while
slightly diverging from the standard interface to accommodate the
implementation. There are two variants: *flat* (the fastest) and
*node-based*, which provide pointer stability under rehashing at the
expense of being slower.
* Finally, *concurrent containers* are designed and implemented to be
used in high-performance multithreaded scenarios. Their interface is
radically different from that of regular C{plus}{plus} containers. Flat
and node-based variants are provided.

在无序关联容器中存储对象需要同时具备键相等函数和哈希函数。标准容器中的默认函数对象支持若干基本类型，包括整数类型、浮点类型、指针类型以及标准字符串。由于
Boost.Unordered 使用
link:../../../../container_hash/index.html[boost::hash]，因此它还支持其他一些类型，包括标准容器。若要使用这些方法不支持的任意类型，您必须扩展
Boost.Hash
以支持该类型，或使用自定义的相等谓词和哈希函数。有关更多详细信息，请参阅
link:hash_equality.html#hash_equality[相等谓词与哈希函数] 一节。

[source,highlight]
----
namespace boost {
    template <
        class Key,
        class Hash = boost::hash<Key>,
        class Pred = std::equal_to<Key>,
        class Alloc = std::allocator<Key> >
    class unordered_set;
    // same for unordered_multiset, unordered_flat_set, unordered_node_set,
    // concurrent_flat_set and concurrent_node_set

    template <
        class Key, class Mapped,
        class Hash = boost::hash<Key>,
        class Pred = std::equal_to<Key>,
        class Alloc = std::allocator<std::pair<Key const, Mapped> > >
    class unordered_map;
    // same for unordered_multimap, unordered_flat_map, unordered_node_map,
    // concurrent_flat_map and concurrent_node_map
}
----

Storing an object in an unordered associative container requires both a
key equality function and a hash function. The default function objects
in the standard containers support a few basic types including integer
types, floating point types, pointer types, and the standard strings.
Since Boost.Unordered uses
link:../../../../container_hash/index.html[boost::hash] it also supports
some other types, including standard containers. To use any types not
supported by these methods you have to extend Boost.Hash to support the
type or use your own custom equality predicates and hash functions. See
the link:hash_equality.html#hash_equality[Equality Predicates and Hash
Functions], section for more details.

[[footer]]
[[footer-text]]
Last updated 2025-10-23 19:02:00 UTC
