[[header]]
== Regular Containers

[[content]]
[[preamble]]
Boost.Unordered closed-addressing containers
(`boost::unordered++_++set`, `boost::unordered++_++map`,
`boost::unordered++_++multiset` and `boost::unordered++_++multimap`) are
fully conformant with the C{plus}{plus} specification for unordered
associative containers, so for those who know how to use
`std::unordered++_++set`, `std::unordered++_++map`, etc., their homonyms
in Boost.Unordered are drop-in replacements. The interface of
open-addressing containers (`boost::unordered++_++node++_++set`,
`boost::unordered++_++node++_++map`, `boost::unordered++_++flat++_++set`
and `boost::unordered++_++flat++_++map`) is very similar, but they
present some minor differences listed in the dedicated
link:compliance.html#compliance_open_addressing_containers[standard
compliance section].

For readers without previous experience with hash containers but
familiar with normal associative containers (`std::set`, `std::map`,
`std::multiset` and `std::multimap`), Boost.Unordered containers are
used in a similar manner:

[source,highlight]
----
typedef boost::unordered_map<std::string, int> map;
map x;
x["one"] = 1;
x["two"] = 2;
x["three"] = 3;

assert(x.at("one") == 1);
assert(x.find("missing") == x.end());
----

But since the elements aren’t ordered, the output of:

[source,highlight]
----
for(const map::value_type& i: x) {
    std::cout<<i.first<<","<<i.second<<"\n";
}
----

can be in any order. For example, it might be:

[source,highlight]
----
two,2
one,1
three,3
----

There are other differences, which are listed in the
link:regular.html#comparison[Comparison with Associative Containers]
section.

[[regular_iterator_invalidation]]
=== Iterator Invalidation

It is not specified how member functions other than `rehash` and
`reserve` affect the bucket count, although `insert` can only invalidate
iterators when the insertion causes the container’s load to be greater
than the maximum allowed. For most implementations this means that
`insert` will only change the number of buckets when this happens.
Iterators can be invalidated by calls to `insert`, `rehash` and
`reserve`.

As for pointers and references, they are never invalidated for
node-based containers (`boost::unordered++_[++multi++]++set`,
`boost::unordered++_[++multi++]++map`,
`boost::unordered++_++node++_++set`,
`boost::unordered++_++node++_++map`), but they will be when rehashing
occurs for `boost::unordered++_++flat++_++set` and
`boost::unordered++_++flat++_++map`: this is because these containers
store elements directly into their holding buckets, so when allocating a
new bucket array the elements must be transferred by means of move
construction.

In a similar manner to using `reserve` for `vector`s, it can be a good
idea to call `reserve` before inserting a large number of elements. This
will get the expensive rehashing out of the way and let you store
iterators, safe in the knowledge that they won’t be invalidated. If you
are inserting `n` elements into container `x`, you could first call:

[source,highlight]
----
x.reserve(n);
----

Note::
  `reserve(n)` reserves space for at least `n` elements, allocating
  enough buckets so as to not exceed the maximum load factor.
  +
  Because the maximum load factor is defined as the number of elements
  divided by the total number of available buckets, this function is
  logically equivalent to:
  +
[source,highlight]
----
x.rehash(std::ceil(n / x.max_load_factor()))
----
  +
  See the
  link:reference/unordered_map.html#unordered_map_rehash[reference for
  more details] on the `rehash` function.

[[comparison]]
=== Comparison with Associative Containers

.Table 1 Interface differences
[width="100%",cols="50%,50%",options="header",]
|===
|Associative Containers |Unordered Associative Containers
|Parameterized by an ordering relation `Compare` |Iterators, pointers
and references to the container’s elements are never invalidated.

|Keys can be compared using `key++_++compare` which is accessed by
member function `key++_++comp()`, values can be compared using
`value++_++compare` which is accessed by member function
`value++_++comp()`. |Iterators iterate through the container in the
order defined by the comparison object.

|Constructors have optional extra parameters for the comparison object.
|No equivalent

|Keys `k1`, `k2` are considered equivalent if
`!Compare(k1, k2) && !Compare(k2, k1)`. |Can be compared using the `==`,
`!=`, `++<++`, `++<++=`, `++>++`, `++>++=` operators.

|Member function `lower++_++bound(k)` and `upper++_++bound(k)` |No
equivalent. Since the elements aren’t ordered `lower++_++bound` and
`upper++_++bound` would be meaningless.

|`equal++_++range(k)` returns an empty range at the position that `k`
would be inserted if `k` isn’t present in the container.
|`equal++_++range(k)` returns a range at the end of the container if `k`
isn’t present in the container. It can’t return a positioned range as
`k` could be inserted into multiple place. +
*Closed-addressing containers:* To find out the bucket that `k` would be
inserted into use `bucket(k)`. But remember that an insert can cause the
container to rehash - meaning that the element can be inserted into a
different bucket.

|`iterator`, `const++_++iterator` are of the bidirectional category.
|`iterator`, `const++_++iterator` are of at least the forward category.

|Iterators, pointers and references to the container’s elements are
never invalidated.
|link:regular.html#regular_iterator_invalidation[Iterators can be
invalidated by calls to insert or rehash]. +
*Node-based containers:* Pointers and references to the container’s
elements are never invalidated. +
*Flat containers:* Pointers and references to the container’s elements
are invalidated when rehashing occurs.

|Iterators iterate through the container in the order defined by the
comparison object. |Iterators iterate through the container in an
arbitrary order, that can change as elements are inserted, although
equivalent elements are always adjacent.

|Construction of empty container |constant

|Can be compared using the `==`, `!=`, `++<++`, `++<++=`, `++>++`,
`++>++=` operators. |Construction of container from a range of _N_
elements

| |When inserting with a hint, implementations are permitted to ignore
the hint.
|===

'''''

.Table 2 Complexity Guarantees
[width="100%",cols="34%,33%,33%",options="header",]
|===
|Operation |Associative Containers |Unordered Associative Containers
|Erase a single element by iterator |Amortized constant |Average case:
O(1), Worst case: O(`size()`)

|Erase a range of _N_ elements |O(log(`size()`) {plus} _N_) |Average
case: O(_N_), Worst case: O(`size()`)

|Clearing the container |O(`size()`) |O(`size()`)

|Find |logarithmic |Average case: O(1), Worst case: O(`size()`)

|Count |O(log(`size()`) {plus} `count(k)`) |Average case: O(1), Worst
case: O(`size()`)

|equal++_++range(k) |logarithmic |Average case: O(`count(k)`), Worst
case: O(`size()`)

|`lower++_++bound`,`upper++_++bound` |logarithmic |n/a

|Erase a range of _N_ elements |O(log(`size()`) {plus} _N_) |Average
case: O(_N_), Worst case: O(`size()`)

|Clearing the container |O(`size()`) |O(`size()`)

|Find |O(`size()`) |n/a

|Count |logarithmic |n/a

|`equal++_++range(k)` |O(`size()`) |Average case: O(`count(k)`), Worst
case: O(`size()`)

|`lower++_++bound`,`upper++_++bound` |O(`size()`) |n/a
|===

[[footer]]
[[footer-text]]
Last updated 2025-10-31 11:10:31 UTC
